// Backup list of publicly accessible traffic camera feeds.
// Primary ingestion is loaded dynamically from Caltrans catalog in CameraLayer.
export const CAMERA_FEEDS = [
    {
        id: 'nasa-iss-live-houston',
        name: 'NASA ISS Live Stream',
        lat: 29.5593,
        lng: -95.0839,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/21X5lGlDOfg?autoplay=1&rel=0',
        fallbackUrl: null,
        detailsUrl: 'https://www.nasa.gov/nasatv',
        city: 'Houston',
        mediaType: 'embed',
        refreshSeconds: 20,
        provider: 'NASA TV',
        type: 'space',
    },
    {
        id: 'caltrans-d1-us101-north-sr20',
        name: 'US-101 North of SR-20',
        lat: 39.250296,
        lng: -123.211287,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101northofsr20lookingnorth/us101northofsr20lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101northofsr20lookingnorth.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-west-us101',
        name: 'SR-20 West of US-101',
        lat: 39.40581,
        lng: -123.36904,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20westofus101lookingeast/sr20westofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20westofus101lookingeast.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-east-us101',
        name: 'SR-20 East of US-101',
        lat: 39.237775,
        lng: -123.167075,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20eastofus101lookingeast/sr20eastofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20eastofus101lookingeast.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-us101-south-sr36',
        name: 'US-101 South of SR-36',
        lat: 40.525005,
        lng: -124.149926,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101southofsr36lookingnorth/us101southofsr36lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101southofsr36lookingnorth.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-antlers-bridge',
        name: 'Antlers Bridge',
        lat: 40.88504,
        lng: -122.38379,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/antlersbridge/antlersbridge.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/antlersbridge.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-black-butte',
        name: 'Black Butte',
        lat: 41.35411,
        lng: -122.3559,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/blackbutte/blackbutte.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/blackbutte.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-fawndale',
        name: 'Fawndale',
        lat: 40.73079,
        lng: -122.32045,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/fawndale/fawndale.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/fawndale.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-grass-lake',
        name: 'Grass Lake',
        lat: 41.63331,
        lng: -122.19312,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/grasslake/grasslake.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/grasslake.htm',
        city: 'California',
        type: 'traffic',
    },
];

// Static airspace restricted zones (simplified GeoJSON)
export const RESTRICTED_AIRSPACE = [
    {
        id: 'dc-sfra',
        name: 'Washington DC SFRA',
        type: 'Restricted',
        center: [-77.0369, 38.9072],
        radius: 55000, // meters
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'dc-frz',
        name: 'Washington DC FRZ',
        type: 'Prohibited',
        center: [-77.0369, 38.9072],
        radius: 25000,
        color: 'rgba(255, 0, 0, 0.25)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
    },
    {
        id: 'area51',
        name: 'Area 51 / Groom Lake',
        type: 'Restricted',
        center: [-115.8111, 37.235],
        radius: 40000,
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'camp-david',
        name: 'Camp David TFR',
        type: 'Prohibited',
        center: [-77.463, 39.648],
        radius: 18500,
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 0, 0, 0.6)',
    },
    {
        id: 'heathrow',
        name: 'London Heathrow CTR',
        type: 'Controlled',
        center: [-0.4543, 51.4700],
        radius: 15000,
        color: 'rgba(0, 180, 255, 0.1)',
        borderColor: 'rgba(0, 180, 255, 0.4)',
    },
];

// Publicly documented no-access / highly restricted places.
export const FORBIDDEN_ZONES = [
    {
        id: 'north-sentinel-island',
        name: 'North Sentinel Island',
        country: 'India',
        center: [92.233, 11.556],
        radius: 9000,
        type: 'Tribal Protection Zone',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Protected uncontacted tribe area. Entry is prohibited.',
        access: 'Prohibited by law',
        source: 'Government-protected tribal reserve',
        reference: 'https://en.wikipedia.org/wiki/North_Sentinel_Island',
        color: 'rgba(255, 0, 0, 0.22)',
        borderColor: 'rgba(255, 50, 50, 0.82)',
    },
    {
        id: 'chernobyl-exclusion-zone',
        name: 'Chernobyl Exclusion Zone',
        country: 'Ukraine',
        center: [30.221, 51.276],
        radius: 30000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Long-term radiation contamination after nuclear disaster.',
        access: 'Permit only / controlled tours',
        source: 'State exclusion regime',
        reference: 'https://en.wikipedia.org/wiki/Chernobyl_Exclusion_Zone',
        color: 'rgba(255, 80, 0, 0.2)',
        borderColor: 'rgba(255, 130, 0, 0.8)',
    },
    {
        id: 'fukushima-exclusion-zone',
        name: 'Fukushima Restricted Zone',
        country: 'Japan',
        center: [141.032, 37.421],
        radius: 20000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Nuclear contamination control area after 2011 disaster.',
        access: 'Controlled re-entry zones only',
        source: 'Government evacuation/restriction orders',
        reference: 'https://en.wikipedia.org/wiki/Fukushima_Daiichi_nuclear_disaster',
        color: 'rgba(255, 80, 0, 0.18)',
        borderColor: 'rgba(255, 140, 0, 0.76)',
    },
    {
        id: 'korean-dmz',
        name: 'Korean Demilitarized Zone',
        country: 'Korea Peninsula',
        center: [126.676, 37.956],
        radius: 42000,
        type: 'Demilitarized Buffer',
        status: 'NO CIVILIAN ENTRY',
        severity: 'EXTREME',
        reason: 'Heavily fortified border buffer between North and South Korea.',
        access: 'Military controlled',
        source: 'Armistice border regime',
        reference: 'https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone',
        color: 'rgba(255, 0, 0, 0.18)',
        borderColor: 'rgba(255, 40, 40, 0.8)',
    },
    {
        id: 'area-51',
        name: 'Area 51',
        country: 'United States',
        center: [-115.8111, 37.235],
        radius: 26000,
        type: 'Military Test Range',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Classified military facility with strict perimeter enforcement.',
        access: 'Prohibited',
        source: 'US military restricted area',
        reference: 'https://en.wikipedia.org/wiki/Area_51',
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 30, 30, 0.85)',
    },
    {
        id: 'diego-garcia-base',
        name: 'Diego Garcia Military Facility',
        country: 'British Indian Ocean Territory',
        center: [72.411, -7.313],
        radius: 16000,
        type: 'Military Facility',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Strategic military island installation.',
        access: 'Authorized personnel only',
        source: 'Military installation restrictions',
        reference: 'https://en.wikipedia.org/wiki/Diego_Garcia',
        color: 'rgba(255, 35, 35, 0.18)',
        borderColor: 'rgba(255, 90, 90, 0.78)',
    },
    {
        id: 'snake-island-brazil',
        name: 'Ilha da Queimada Grande (Snake Island)',
        country: 'Brazil',
        center: [-46.675, -24.488],
        radius: 6500,
        type: 'Ecological Prohibition',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'Protected island with extreme venomous snake density.',
        access: 'Navy/research only',
        source: 'Brazilian environmental / naval control',
        reference: 'https://en.wikipedia.org/wiki/Ilha_da_Queimada_Grande',
        color: 'rgba(255, 70, 0, 0.16)',
        borderColor: 'rgba(255, 120, 0, 0.78)',
    },
    {
        id: 'surtsey-island',
        name: 'Surtsey Island',
        country: 'Iceland',
        center: [-20.605, 63.303],
        radius: 7000,
        type: 'Scientific Reserve',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Protected natural laboratory for ecological succession research.',
        access: 'Scientists with permission only',
        source: 'UNESCO/State protection',
        reference: 'https://en.wikipedia.org/wiki/Surtsey',
        color: 'rgba(255, 160, 0, 0.14)',
        borderColor: 'rgba(255, 190, 0, 0.72)',
    },
    {
        id: 'niihau-island',
        name: 'Niihau Island',
        country: 'United States',
        center: [-160.154, 21.899],
        radius: 15000,
        type: 'Private Restricted Island',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Privately owned island with controlled access.',
        access: 'Owner-approved only',
        source: 'Private ownership restrictions',
        reference: 'https://en.wikipedia.org/wiki/Niihau',
        color: 'rgba(255, 180, 0, 0.14)',
        borderColor: 'rgba(255, 210, 0, 0.72)',
    },
    {
        id: 'lascaux-cave',
        name: 'Lascaux Cave',
        country: 'France',
        center: [1.167, 45.053],
        radius: 2200,
        type: 'Heritage Preservation',
        status: 'CLOSED',
        severity: 'MEDIUM',
        reason: 'Original cave closed to preserve prehistoric paintings.',
        access: 'No public entry',
        source: 'Cultural heritage preservation',
        reference: 'https://en.wikipedia.org/wiki/Lascaux',
        color: 'rgba(255, 140, 0, 0.16)',
        borderColor: 'rgba(255, 170, 0, 0.74)',
    },
    {
        id: 'mezhgorye-closed-city',
        name: 'Mezhgorye Closed City',
        country: 'Russia',
        center: [57.817, 54.049],
        radius: 12000,
        type: 'Closed Administrative Area',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Closed city with restricted external access.',
        access: 'Government authorization only',
        source: 'Closed city regime',
        reference: 'https://en.wikipedia.org/wiki/Mezhgorye,_Republic_of_Bashkortostan',
        color: 'rgba(255, 60, 60, 0.15)',
        borderColor: 'rgba(255, 100, 100, 0.75)',
    },
    {
        id: 'zone-rouge-france',
        name: 'Zone Rouge',
        country: 'France',
        center: [5.43, 49.22],
        radius: 17000,
        type: 'War Remnants Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'WWI unexploded ordnance and contamination zone.',
        access: 'Restricted / controlled activity',
        source: 'French state safety restrictions',
        reference: 'https://en.wikipedia.org/wiki/Zone_Rouge',
        color: 'rgba(255, 90, 0, 0.14)',
        borderColor: 'rgba(255, 130, 0, 0.72)',
    },
    {
        id: 'bikini-atoll',
        name: 'Bikini Atoll Nuclear Test Site',
        country: 'Marshall Islands',
        center: [165.386, 11.606],
        radius: 24000,
        type: 'Nuclear Legacy Zone',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Historic nuclear test area with long-term contamination concerns.',
        access: 'Controlled access',
        source: 'Nuclear test legacy restrictions',
        reference: 'https://en.wikipedia.org/wiki/Bikini_Atoll',
        color: 'rgba(255, 90, 0, 0.16)',
        borderColor: 'rgba(255, 140, 0, 0.75)',
    },
    {
        id: 'punggye-ri-test-site',
        name: 'Punggye-ri Test Site Zone',
        country: 'North Korea',
        center: [129.083, 41.3],
        radius: 10000,
        type: 'Nuclear Test Security Zone',
        status: 'NO PUBLIC ENTRY',
        severity: 'EXTREME',
        reason: 'Restricted military zone associated with underground nuclear testing.',
        access: 'Prohibited',
        source: 'State military security controls',
        reference: 'https://en.wikipedia.org/wiki/Punggye-ri_Nuclear_Test_Site',
        color: 'rgba(255, 30, 30, 0.2)',
        borderColor: 'rgba(255, 80, 80, 0.85)',
    },
    {
        id: 'mount-weather',
        name: 'Mount Weather Emergency Operations Center',
        country: 'United States',
        center: [-77.886, 39.062],
        radius: 7000,
        type: 'Government Security Site',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'High-security continuity-of-government facility.',
        access: 'Authorized personnel only',
        source: 'Federal security restrictions',
        reference: 'https://en.wikipedia.org/wiki/Mount_Weather_Emergency_Operations_Center',
        color: 'rgba(255, 40, 40, 0.16)',
        borderColor: 'rgba(255, 80, 80, 0.75)',
    },
    {
        id: 'heard-island-reserve',
        name: 'Heard Island & McDonald Islands Reserve',
        country: 'Australia',
        center: [73.51, -53.08],
        radius: 22000,
        type: 'Environmental Protection Zone',
        status: 'PERMIT REQUIRED',
        severity: 'MEDIUM',
        reason: 'Remote subantarctic reserve with strict permit-only entry controls.',
        access: 'Permit required',
        source: 'Australian Antarctic Division permit regime',
        reference: 'https://www.antarctica.gov.au/about-antarctica/australian-antarctic-territory/heard-island/',
        color: 'rgba(255, 140, 0, 0.12)',
        borderColor: 'rgba(255, 175, 0, 0.68)',
    },
];
