// Backup list of publicly accessible traffic camera feeds.
// Primary ingestion is loaded dynamically from Caltrans catalog in CameraLayer.
export const CAMERA_FEEDS = [
    // ── SPACE ──────────────────────────────────────────
    {
        id: 'nasa-iss-live',
        name: 'NASA ISS Live Stream',
        lat: 29.5593, lng: -95.0839,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/21X5lGlDOfg?autoplay=1&rel=0',
        city: 'Houston', mediaType: 'embed', refreshSeconds: 20,
        provider: 'NASA TV', type: 'space',
    },

    // ── INDIA ──────────────────────────────────────────
    {
        id: 'india-delhi-connaught',
        name: 'New Delhi — Connaught Place',
        lat: 28.6315, lng: 77.2167,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/jxKzAXB3ZYk?autoplay=1&rel=0',
        city: 'New Delhi', mediaType: 'embed', provider: 'WorldCam', type: 'city',
    },
    {
        id: 'india-delhi-traffic-igate',
        name: 'Delhi — India Gate Traffic',
        lat: 28.6129, lng: 77.2295,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/VgLrKMMj1wg?autoplay=1&rel=0',
        city: 'New Delhi', mediaType: 'embed', provider: 'LiveCam', type: 'traffic',
    },
    {
        id: 'india-varanasi-ghats',
        name: 'Varanasi — Dashashwamedh Ghat',
        lat: 25.3109, lng: 83.0107,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/66CU2WyWJCc?autoplay=1&rel=0',
        city: 'Varanasi', mediaType: 'embed', provider: 'Temple Cam', type: 'landmark',
    },
    {
        id: 'india-varanasi-ganga-aarti',
        name: 'Varanasi — Ganga Aarti Live',
        lat: 25.3045, lng: 83.0116,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/IXzDLgSaeAg?autoplay=1&rel=0',
        city: 'Varanasi', mediaType: 'embed', provider: 'Temple Cam', type: 'landmark',
    },
    {
        id: 'india-mumbai-marine-drive',
        name: 'Mumbai — Marine Drive',
        lat: 18.9437, lng: 72.8235,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/Nm0zR4hIFe0?autoplay=1&rel=0',
        city: 'Mumbai', mediaType: 'embed', provider: 'MumbaiCam', type: 'city',
    },
    {
        id: 'india-mumbai-gateway',
        name: 'Mumbai — Gateway of India',
        lat: 18.9220, lng: 72.8347,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/0j-mwcTVSy0?autoplay=1&rel=0',
        city: 'Mumbai', mediaType: 'embed', provider: 'MumbaiLive', type: 'landmark',
    },
    {
        id: 'india-kolkata-howrah',
        name: 'Kolkata — Howrah Bridge',
        lat: 22.5854, lng: 88.3464,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/mJVFhn7RpkI?autoplay=1&rel=0',
        city: 'Kolkata', mediaType: 'embed', provider: 'LiveCam', type: 'landmark',
    },
    {
        id: 'india-jaipur-hawa-mahal',
        name: 'Jaipur — Hawa Mahal Road',
        lat: 26.9239, lng: 75.8267,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/q2U4g5GHNnw?autoplay=1&rel=0',
        city: 'Jaipur', mediaType: 'embed', provider: 'RajasthanCam', type: 'landmark',
    },
    {
        id: 'india-chennai-marina',
        name: 'Chennai — Marina Beach',
        lat: 13.0504, lng: 80.2824,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/DlPvZ9Bsyf4?autoplay=1&rel=0',
        city: 'Chennai', mediaType: 'embed', provider: 'ChennaiCam', type: 'city',
    },
    {
        id: 'india-bangalore-mg-road',
        name: 'Bangalore — MG Road',
        lat: 12.9758, lng: 77.6065,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/j0MyB7gJmRs?autoplay=1&rel=0',
        city: 'Bangalore', mediaType: 'embed', provider: 'BangaloreLive', type: 'city',
    },
    {
        id: 'india-hyderabad-charminar',
        name: 'Hyderabad — Charminar',
        lat: 17.3616, lng: 78.4747,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/xA7XhxnBAFw?autoplay=1&rel=0',
        city: 'Hyderabad', mediaType: 'embed', provider: 'HydCam', type: 'landmark',
    },
    {
        id: 'india-kochi-backwaters',
        name: 'Kochi — Backwaters View',
        lat: 9.9312, lng: 76.2673,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/Nzq2m4gQHrI?autoplay=1&rel=0',
        city: 'Kochi', mediaType: 'embed', provider: 'KeralaCam', type: 'city',
    },
    {
        id: 'india-goa-baga-beach',
        name: 'Goa — Baga Beach',
        lat: 15.5554, lng: 73.7514,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/PyLEH0GN-CY?autoplay=1&rel=0',
        city: 'Goa', mediaType: 'embed', provider: 'GoaLive', type: 'city',
    },
    {
        id: 'india-amritsar-golden-temple',
        name: 'Amritsar — Golden Temple Live',
        lat: 31.6200, lng: 74.8765,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/JRsBRXKNyn4?autoplay=1&rel=0',
        city: 'Amritsar', mediaType: 'embed', provider: 'SGPC', type: 'landmark',
    },
    {
        id: 'india-rishikesh-ganga',
        name: 'Rishikesh — Ganga River',
        lat: 30.0869, lng: 78.2676,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/c8Sh-3qhCr0?autoplay=1&rel=0',
        city: 'Rishikesh', mediaType: 'embed', provider: 'RishikeshCam', type: 'landmark',
    },
    {
        id: 'india-udaipur-lake-pichola',
        name: 'Udaipur — Lake Pichola',
        lat: 24.5760, lng: 73.6831,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/SxBFxzWqXKE?autoplay=1&rel=0',
        city: 'Udaipur', mediaType: 'embed', provider: 'RajasthanCam', type: 'landmark',
    },
    {
        id: 'india-agra-taj-mahal',
        name: 'Agra — Taj Mahal View',
        lat: 27.1751, lng: 78.0421,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/FlYmAsfFMFQ?autoplay=1&rel=0',
        city: 'Agra', mediaType: 'embed', provider: 'IndiaCam', type: 'landmark',
    },
    {
        id: 'india-pune-fc-road',
        name: 'Pune — Fergusson College Road',
        lat: 18.5270, lng: 73.8403,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/MkIreSf5U0A?autoplay=1&rel=0',
        city: 'Pune', mediaType: 'embed', provider: 'PuneCam', type: 'city',
    },
    {
        id: 'india-ahmedabad-sabarmati',
        name: 'Ahmedabad — Sabarmati Riverfront',
        lat: 23.0395, lng: 72.5638,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/bfvR3DxVOWM?autoplay=1&rel=0',
        city: 'Ahmedabad', mediaType: 'embed', provider: 'AhmedabadCam', type: 'city',
    },

    // ── JAPAN ──────────────────────────────────────────
    {
        id: 'tokyo-shibuya-crossing',
        name: 'Tokyo — Shibuya Crossing',
        lat: 35.6595, lng: 139.7004,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/3q2CnFMbhJc?autoplay=1&rel=0',
        city: 'Tokyo', mediaType: 'embed', provider: 'ShibuyaCam', type: 'city',
    },
    {
        id: 'tokyo-kabukicho',
        name: 'Tokyo — Kabukicho Live',
        lat: 35.6938, lng: 139.7034,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/gFRtAAmiFbE?autoplay=1&rel=0',
        city: 'Tokyo', mediaType: 'embed', provider: 'KabukichoCam', type: 'city',
    },
    {
        id: 'tokyo-shinjuku-south',
        name: 'Tokyo — Shinjuku Station',
        lat: 35.6896, lng: 139.7006,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/3VfE5VxgfjQ?autoplay=1&rel=0',
        city: 'Tokyo', mediaType: 'embed', provider: 'ShinjukuCam', type: 'city',
    },

    // ── USA ────────────────────────────────────────────
    {
        id: 'nyc-times-square',
        name: 'New York — Times Square',
        lat: 40.7580, lng: -73.9855,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/eJ7ZkQ5TC08?autoplay=1&rel=0',
        city: 'New York', mediaType: 'embed', provider: 'EarthCam', type: 'city',
    },
    {
        id: 'nyc-empire-state',
        name: 'New York — Empire State Bldg',
        lat: 40.7484, lng: -73.9857,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/E4tHXGMxo3E?autoplay=1&rel=0',
        city: 'New York', mediaType: 'embed', provider: 'EarthCam', type: 'city',
    },
    {
        id: 'nyc-5th-avenue',
        name: 'New York — 5th Avenue',
        lat: 40.7549, lng: -73.9840,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/mNh1VQxpJuY?autoplay=1&rel=0',
        city: 'New York', mediaType: 'embed', provider: 'EarthCam', type: 'city',
    },
    {
        id: 'la-santa-monica-pier',
        name: 'Los Angeles — Santa Monica Pier',
        lat: 34.0094, lng: -118.4973,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/vj6MUkOsUiM?autoplay=1&rel=0',
        city: 'Los Angeles', mediaType: 'embed', provider: 'EarthCam', type: 'city',
    },
    {
        id: 'miami-south-beach',
        name: 'Miami — South Beach',
        lat: 25.7826, lng: -80.1341,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/se8RvAjQxJE?autoplay=1&rel=0',
        city: 'Miami', mediaType: 'embed', provider: 'EarthCam', type: 'city',
    },
    {
        id: 'chicago-michigan-ave',
        name: 'Chicago — Michigan Ave',
        lat: 41.8827, lng: -87.6233,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/t7F_JMgppVw?autoplay=1&rel=0',
        city: 'Chicago', mediaType: 'embed', provider: 'ChicagoCam', type: 'city',
    },

    // ── EUROPE ─────────────────────────────────────────
    {
        id: 'london-tower-bridge',
        name: 'London — Tower Bridge',
        lat: 51.5055, lng: -0.0754,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/Wd5VBp_ycSw?autoplay=1&rel=0',
        city: 'London', mediaType: 'embed', provider: 'LondonCam', type: 'landmark',
    },
    {
        id: 'london-abbey-road',
        name: 'London — Abbey Road Crossing',
        lat: 51.5321, lng: -0.1776,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/dQHPfMFmr5I?autoplay=1&rel=0',
        city: 'London', mediaType: 'embed', provider: 'AbbeyRoadCam', type: 'landmark',
    },
    {
        id: 'paris-eiffel-tower',
        name: 'Paris — Eiffel Tower',
        lat: 48.8584, lng: 2.2945,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/wJFRnLS1gqI?autoplay=1&rel=0',
        city: 'Paris', mediaType: 'embed', provider: 'ParisCam', type: 'landmark',
    },
    {
        id: 'amsterdam-dam-square',
        name: 'Amsterdam — Dam Square',
        lat: 52.3730, lng: 4.8932,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/rdZFxMPqZbo?autoplay=1&rel=0',
        city: 'Amsterdam', mediaType: 'embed', provider: 'AmsterdamCam', type: 'city',
    },
    {
        id: 'rome-trevi-fountain',
        name: 'Rome — Trevi Fountain',
        lat: 41.9009, lng: 12.4833,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/6OrGjfKjTVQ?autoplay=1&rel=0',
        city: 'Rome', mediaType: 'embed', provider: 'RomeCam', type: 'landmark',
    },
    {
        id: 'barcelona-las-ramblas',
        name: 'Barcelona — Las Ramblas',
        lat: 41.3809, lng: 2.1734,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/7dRHfUVHOvY?autoplay=1&rel=0',
        city: 'Barcelona', mediaType: 'embed', provider: 'BarcelonaCam', type: 'city',
    },
    {
        id: 'prague-old-town',
        name: 'Prague — Old Town Square',
        lat: 50.0870, lng: 14.4213,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/boBU9XmhWrU?autoplay=1&rel=0',
        city: 'Prague', mediaType: 'embed', provider: 'PragueCam', type: 'landmark',
    },
    {
        id: 'venice-st-mark',
        name: 'Venice — St Mark\'s Square',
        lat: 45.4343, lng: 12.3388,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/vy1l2PaHflU?autoplay=1&rel=0',
        city: 'Venice', mediaType: 'embed', provider: 'VeniceCam', type: 'landmark',
    },
    {
        id: 'istanbul-hagia-sophia',
        name: 'Istanbul — Hagia Sophia Area',
        lat: 41.0086, lng: 28.9802,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/oLq0BwUS8Z0?autoplay=1&rel=0',
        city: 'Istanbul', mediaType: 'embed', provider: 'IstanbulCam', type: 'landmark',
    },

    // ── MIDDLE EAST ────────────────────────────────────
    {
        id: 'dubai-burj-khalifa',
        name: 'Dubai — Burj Khalifa',
        lat: 25.1972, lng: 55.2744,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/CgHEGfEMqCo?autoplay=1&rel=0',
        city: 'Dubai', mediaType: 'embed', provider: 'DubaiCam', type: 'landmark',
    },
    {
        id: 'mecca-masjid-al-haram',
        name: 'Mecca — Masjid al-Haram',
        lat: 21.4225, lng: 39.8262,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/lq5m_Yt6rQ4?autoplay=1&rel=0',
        city: 'Mecca', mediaType: 'embed', provider: 'SaudiLive', type: 'landmark',
    },

    // ── ASIA-PACIFIC ───────────────────────────────────
    {
        id: 'seoul-gangnam',
        name: 'Seoul — Gangnam Station',
        lat: 37.4979, lng: 127.0276,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/nDRtIhxGaHs?autoplay=1&rel=0',
        city: 'Seoul', mediaType: 'embed', provider: 'SeoulCam', type: 'city',
    },
    {
        id: 'bangkok-sukhumvit',
        name: 'Bangkok — Sukhumvit Road',
        lat: 13.7381, lng: 100.5607,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/1UsSGc67J08?autoplay=1&rel=0',
        city: 'Bangkok', mediaType: 'embed', provider: 'BangkokCam', type: 'city',
    },
    {
        id: 'singapore-marina-bay',
        name: 'Singapore — Marina Bay',
        lat: 1.2838, lng: 103.8591,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/dPgMlzVfLHk?autoplay=1&rel=0',
        city: 'Singapore', mediaType: 'embed', provider: 'SingaporeCam', type: 'city',
    },
    {
        id: 'hong-kong-victoria',
        name: 'Hong Kong — Victoria Harbour',
        lat: 22.2855, lng: 114.1577,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/2ccaHpy5Ewo?autoplay=1&rel=0',
        city: 'Hong Kong', mediaType: 'embed', provider: 'HKLive', type: 'city',
    },
    {
        id: 'sydney-harbour-bridge',
        name: 'Sydney — Harbour Bridge',
        lat: -33.8523, lng: 151.2108,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/FG90eROuLjo?autoplay=1&rel=0',
        city: 'Sydney', mediaType: 'embed', provider: 'SydneyCam', type: 'landmark',
    },

    // ── SOUTH AMERICA ──────────────────────────────────
    {
        id: 'rio-copacabana',
        name: 'Rio de Janeiro — Copacabana Beach',
        lat: -22.9711, lng: -43.1863,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/lFRVUHvl9Y0?autoplay=1&rel=0',
        city: 'Rio de Janeiro', mediaType: 'embed', provider: 'RioCam', type: 'city',
    },
    {
        id: 'buenos-aires-obelisco',
        name: 'Buenos Aires — Obelisco',
        lat: -34.6037, lng: -58.3816,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/D8UMYfUq7sA?autoplay=1&rel=0',
        city: 'Buenos Aires', mediaType: 'embed', provider: 'BACam', type: 'landmark',
    },

    // ── AFRICA ─────────────────────────────────────────
    {
        id: 'cape-town-table-mountain',
        name: 'Cape Town — Table Mountain',
        lat: -33.9628, lng: 18.4098,
        url: null,
        videoUrl: 'https://www.youtube.com/embed/GKWH6lIoJK0?autoplay=1&rel=0',
        city: 'Cape Town', mediaType: 'embed', provider: 'CapeTownCam', type: 'landmark',
    },

    // ── US TRAFFIC CAMS (Caltrans originals) ──────────
    {
        id: 'caltrans-d1-us101-north-sr20',
        name: 'US-101 North of SR-20',
        lat: 39.250296, lng: -123.211287,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101northofsr20lookingnorth/us101northofsr20lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101northofsr20lookingnorth.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-west-us101',
        name: 'SR-20 West of US-101',
        lat: 39.40581, lng: -123.36904,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20westofus101lookingeast/sr20westofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20westofus101lookingeast.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-east-us101',
        name: 'SR-20 East of US-101',
        lat: 39.237775, lng: -123.167075,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20eastofus101lookingeast/sr20eastofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20eastofus101lookingeast.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d1-us101-south-sr36',
        name: 'US-101 South of SR-36',
        lat: 40.525005, lng: -124.149926,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101southofsr36lookingnorth/us101southofsr36lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101southofsr36lookingnorth.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d2-antlers-bridge',
        name: 'Antlers Bridge',
        lat: 40.88504, lng: -122.38379,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/antlersbridge/antlersbridge.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/antlersbridge.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d2-black-butte',
        name: 'Black Butte',
        lat: 41.35411, lng: -122.3559,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/blackbutte/blackbutte.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/blackbutte.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d2-fawndale',
        name: 'Fawndale',
        lat: 40.73079, lng: -122.32045,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/fawndale/fawndale.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/fawndale.htm',
        city: 'California', type: 'traffic',
    },
    {
        id: 'caltrans-d2-grass-lake',
        name: 'Grass Lake',
        lat: 41.63331, lng: -122.19312,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/grasslake/grasslake.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/grasslake.htm',
        city: 'California', type: 'traffic',
    },
];

// Static airspace restricted zones (simplified GeoJSON)
export const RESTRICTED_AIRSPACE = [
    {
        id: 'dc-sfra',
        name: 'Washington DC SFRA',
        type: 'Restricted',
        center: [-77.0369, 38.9072],
        radius: 55000, // meters
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'dc-frz',
        name: 'Washington DC FRZ',
        type: 'Prohibited',
        center: [-77.0369, 38.9072],
        radius: 25000,
        color: 'rgba(255, 0, 0, 0.25)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
    },
    {
        id: 'area51',
        name: 'Area 51 / Groom Lake',
        type: 'Restricted',
        center: [-115.8111, 37.235],
        radius: 40000,
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'camp-david',
        name: 'Camp David TFR',
        type: 'Prohibited',
        center: [-77.463, 39.648],
        radius: 18500,
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 0, 0, 0.6)',
    },
    {
        id: 'heathrow',
        name: 'London Heathrow CTR',
        type: 'Controlled',
        center: [-0.4543, 51.4700],
        radius: 15000,
        color: 'rgba(0, 180, 255, 0.1)',
        borderColor: 'rgba(0, 180, 255, 0.4)',
    },
];

// Publicly documented no-access / highly restricted places.
export const FORBIDDEN_ZONES = [
    {
        id: 'north-sentinel-island',
        name: 'North Sentinel Island',
        country: 'India',
        center: [92.233, 11.556],
        radius: 9000,
        type: 'Tribal Protection Zone',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Protected uncontacted tribe area. Entry is prohibited.',
        access: 'Prohibited by law',
        source: 'Government-protected tribal reserve',
        reference: 'https://en.wikipedia.org/wiki/North_Sentinel_Island',
        color: 'rgba(255, 0, 0, 0.22)',
        borderColor: 'rgba(255, 50, 50, 0.82)',
    },
    {
        id: 'chernobyl-exclusion-zone',
        name: 'Chernobyl Exclusion Zone',
        country: 'Ukraine',
        center: [30.221, 51.276],
        radius: 30000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Long-term radiation contamination after nuclear disaster.',
        access: 'Permit only / controlled tours',
        source: 'State exclusion regime',
        reference: 'https://en.wikipedia.org/wiki/Chernobyl_Exclusion_Zone',
        color: 'rgba(255, 80, 0, 0.2)',
        borderColor: 'rgba(255, 130, 0, 0.8)',
    },
    {
        id: 'fukushima-exclusion-zone',
        name: 'Fukushima Restricted Zone',
        country: 'Japan',
        center: [141.032, 37.421],
        radius: 20000,
        type: 'Radiation Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Nuclear contamination control area after 2011 disaster.',
        access: 'Controlled re-entry zones only',
        source: 'Government evacuation/restriction orders',
        reference: 'https://en.wikipedia.org/wiki/Fukushima_Daiichi_nuclear_disaster',
        color: 'rgba(255, 80, 0, 0.18)',
        borderColor: 'rgba(255, 140, 0, 0.76)',
    },
    {
        id: 'korean-dmz',
        name: 'Korean Demilitarized Zone',
        country: 'Korea Peninsula',
        center: [126.676, 37.956],
        radius: 42000,
        type: 'Demilitarized Buffer',
        status: 'NO CIVILIAN ENTRY',
        severity: 'EXTREME',
        reason: 'Heavily fortified border buffer between North and South Korea.',
        access: 'Military controlled',
        source: 'Armistice border regime',
        reference: 'https://en.wikipedia.org/wiki/Korean_Demilitarized_Zone',
        color: 'rgba(255, 0, 0, 0.18)',
        borderColor: 'rgba(255, 40, 40, 0.8)',
    },
    {
        id: 'area-51',
        name: 'Area 51',
        country: 'United States',
        center: [-115.8111, 37.235],
        radius: 26000,
        type: 'Military Test Range',
        status: 'NO ENTRY',
        severity: 'EXTREME',
        reason: 'Classified military facility with strict perimeter enforcement.',
        access: 'Prohibited',
        source: 'US military restricted area',
        reference: 'https://en.wikipedia.org/wiki/Area_51',
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 30, 30, 0.85)',
    },
    {
        id: 'diego-garcia-base',
        name: 'Diego Garcia Military Facility',
        country: 'British Indian Ocean Territory',
        center: [72.411, -7.313],
        radius: 16000,
        type: 'Military Facility',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Strategic military island installation.',
        access: 'Authorized personnel only',
        source: 'Military installation restrictions',
        reference: 'https://en.wikipedia.org/wiki/Diego_Garcia',
        color: 'rgba(255, 35, 35, 0.18)',
        borderColor: 'rgba(255, 90, 90, 0.78)',
    },
    {
        id: 'snake-island-brazil',
        name: 'Ilha da Queimada Grande (Snake Island)',
        country: 'Brazil',
        center: [-46.675, -24.488],
        radius: 6500,
        type: 'Ecological Prohibition',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'Protected island with extreme venomous snake density.',
        access: 'Navy/research only',
        source: 'Brazilian environmental / naval control',
        reference: 'https://en.wikipedia.org/wiki/Ilha_da_Queimada_Grande',
        color: 'rgba(255, 70, 0, 0.16)',
        borderColor: 'rgba(255, 120, 0, 0.78)',
    },
    {
        id: 'surtsey-island',
        name: 'Surtsey Island',
        country: 'Iceland',
        center: [-20.605, 63.303],
        radius: 7000,
        type: 'Scientific Reserve',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Protected natural laboratory for ecological succession research.',
        access: 'Scientists with permission only',
        source: 'UNESCO/State protection',
        reference: 'https://en.wikipedia.org/wiki/Surtsey',
        color: 'rgba(255, 160, 0, 0.14)',
        borderColor: 'rgba(255, 190, 0, 0.72)',
    },
    {
        id: 'niihau-island',
        name: 'Niihau Island',
        country: 'United States',
        center: [-160.154, 21.899],
        radius: 15000,
        type: 'Private Restricted Island',
        status: 'NO PUBLIC ENTRY',
        severity: 'MEDIUM',
        reason: 'Privately owned island with controlled access.',
        access: 'Owner-approved only',
        source: 'Private ownership restrictions',
        reference: 'https://en.wikipedia.org/wiki/Niihau',
        color: 'rgba(255, 180, 0, 0.14)',
        borderColor: 'rgba(255, 210, 0, 0.72)',
    },
    {
        id: 'lascaux-cave',
        name: 'Lascaux Cave',
        country: 'France',
        center: [1.167, 45.053],
        radius: 2200,
        type: 'Heritage Preservation',
        status: 'CLOSED',
        severity: 'MEDIUM',
        reason: 'Original cave closed to preserve prehistoric paintings.',
        access: 'No public entry',
        source: 'Cultural heritage preservation',
        reference: 'https://en.wikipedia.org/wiki/Lascaux',
        color: 'rgba(255, 140, 0, 0.16)',
        borderColor: 'rgba(255, 170, 0, 0.74)',
    },
    {
        id: 'mezhgorye-closed-city',
        name: 'Mezhgorye Closed City',
        country: 'Russia',
        center: [57.817, 54.049],
        radius: 12000,
        type: 'Closed Administrative Area',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Closed city with restricted external access.',
        access: 'Government authorization only',
        source: 'Closed city regime',
        reference: 'https://en.wikipedia.org/wiki/Mezhgorye,_Republic_of_Bashkortostan',
        color: 'rgba(255, 60, 60, 0.15)',
        borderColor: 'rgba(255, 100, 100, 0.75)',
    },
    {
        id: 'zone-rouge-france',
        name: 'Zone Rouge',
        country: 'France',
        center: [5.43, 49.22],
        radius: 17000,
        type: 'War Remnants Exclusion',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'WWI unexploded ordnance and contamination zone.',
        access: 'Restricted / controlled activity',
        source: 'French state safety restrictions',
        reference: 'https://en.wikipedia.org/wiki/Zone_Rouge',
        color: 'rgba(255, 90, 0, 0.14)',
        borderColor: 'rgba(255, 130, 0, 0.72)',
    },
    {
        id: 'bikini-atoll',
        name: 'Bikini Atoll Nuclear Test Site',
        country: 'Marshall Islands',
        center: [165.386, 11.606],
        radius: 24000,
        type: 'Nuclear Legacy Zone',
        status: 'RESTRICTED',
        severity: 'HIGH',
        reason: 'Historic nuclear test area with long-term contamination concerns.',
        access: 'Controlled access',
        source: 'Nuclear test legacy restrictions',
        reference: 'https://en.wikipedia.org/wiki/Bikini_Atoll',
        color: 'rgba(255, 90, 0, 0.16)',
        borderColor: 'rgba(255, 140, 0, 0.75)',
    },
    {
        id: 'punggye-ri-test-site',
        name: 'Punggye-ri Test Site Zone',
        country: 'North Korea',
        center: [129.083, 41.3],
        radius: 10000,
        type: 'Nuclear Test Security Zone',
        status: 'NO PUBLIC ENTRY',
        severity: 'EXTREME',
        reason: 'Restricted military zone associated with underground nuclear testing.',
        access: 'Prohibited',
        source: 'State military security controls',
        reference: 'https://en.wikipedia.org/wiki/Punggye-ri_Nuclear_Test_Site',
        color: 'rgba(255, 30, 30, 0.2)',
        borderColor: 'rgba(255, 80, 80, 0.85)',
    },
    {
        id: 'mount-weather',
        name: 'Mount Weather Emergency Operations Center',
        country: 'United States',
        center: [-77.886, 39.062],
        radius: 7000,
        type: 'Government Security Site',
        status: 'NO PUBLIC ENTRY',
        severity: 'HIGH',
        reason: 'High-security continuity-of-government facility.',
        access: 'Authorized personnel only',
        source: 'Federal security restrictions',
        reference: 'https://en.wikipedia.org/wiki/Mount_Weather_Emergency_Operations_Center',
        color: 'rgba(255, 40, 40, 0.16)',
        borderColor: 'rgba(255, 80, 80, 0.75)',
    },
    {
        id: 'heard-island-reserve',
        name: 'Heard Island & McDonald Islands Reserve',
        country: 'Australia',
        center: [73.51, -53.08],
        radius: 22000,
        type: 'Environmental Protection Zone',
        status: 'PERMIT REQUIRED',
        severity: 'MEDIUM',
        reason: 'Remote subantarctic reserve with strict permit-only entry controls.',
        access: 'Permit required',
        source: 'Australian Antarctic Division permit regime',
        reference: 'https://www.antarctica.gov.au/about-antarctica/australian-antarctic-territory/heard-island/',
        color: 'rgba(255, 140, 0, 0.12)',
        borderColor: 'rgba(255, 175, 0, 0.68)',
    },
];
