// Backup list of publicly accessible traffic camera feeds.
// Primary ingestion is loaded dynamically from Caltrans catalog in CameraLayer.
export const CAMERA_FEEDS = [
    {
        id: 'caltrans-d1-us101-north-sr20',
        name: 'US-101 North of SR-20',
        lat: 39.250296,
        lng: -123.211287,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101northofsr20lookingnorth/us101northofsr20lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101northofsr20lookingnorth.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-west-us101',
        name: 'SR-20 West of US-101',
        lat: 39.40581,
        lng: -123.36904,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20westofus101lookingeast/sr20westofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20westofus101lookingeast.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-sr20-east-us101',
        name: 'SR-20 East of US-101',
        lat: 39.237775,
        lng: -123.167075,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/sr20eastofus101lookingeast/sr20eastofus101lookingeast.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/sr20eastofus101lookingeast.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d1-us101-south-sr36',
        name: 'US-101 South of SR-36',
        lat: 40.525005,
        lng: -124.149926,
        url: 'https://cwwp2.dot.ca.gov/data/d1/cctv/image/us101southofsr36lookingnorth/us101southofsr36lookingnorth.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d1/us101southofsr36lookingnorth.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-antlers-bridge',
        name: 'Antlers Bridge',
        lat: 40.88504,
        lng: -122.38379,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/antlersbridge/antlersbridge.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/antlersbridge.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-black-butte',
        name: 'Black Butte',
        lat: 41.35411,
        lng: -122.3559,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/blackbutte/blackbutte.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/blackbutte.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-fawndale',
        name: 'Fawndale',
        lat: 40.73079,
        lng: -122.32045,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/fawndale/fawndale.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/fawndale.htm',
        city: 'California',
        type: 'traffic',
    },
    {
        id: 'caltrans-d2-grass-lake',
        name: 'Grass Lake',
        lat: 41.63331,
        lng: -122.19312,
        url: 'https://cwwp2.dot.ca.gov/data/d2/cctv/image/grasslake/grasslake.jpg',
        videoUrl: 'https://cwwp2.dot.ca.gov/vm/loc/d2/grasslake.htm',
        city: 'California',
        type: 'traffic',
    },
];

// Static airspace restricted zones (simplified GeoJSON)
export const RESTRICTED_AIRSPACE = [
    {
        id: 'dc-sfra',
        name: 'Washington DC SFRA',
        type: 'Restricted',
        center: [-77.0369, 38.9072],
        radius: 55000, // meters
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'dc-frz',
        name: 'Washington DC FRZ',
        type: 'Prohibited',
        center: [-77.0369, 38.9072],
        radius: 25000,
        color: 'rgba(255, 0, 0, 0.25)',
        borderColor: 'rgba(255, 0, 0, 0.8)',
    },
    {
        id: 'area51',
        name: 'Area 51 / Groom Lake',
        type: 'Restricted',
        center: [-115.8111, 37.235],
        radius: 40000,
        color: 'rgba(255, 0, 0, 0.15)',
        borderColor: 'rgba(255, 0, 0, 0.5)',
    },
    {
        id: 'camp-david',
        name: 'Camp David TFR',
        type: 'Prohibited',
        center: [-77.463, 39.648],
        radius: 18500,
        color: 'rgba(255, 0, 0, 0.2)',
        borderColor: 'rgba(255, 0, 0, 0.6)',
    },
    {
        id: 'heathrow',
        name: 'London Heathrow CTR',
        type: 'Controlled',
        center: [-0.4543, 51.4700],
        radius: 15000,
        color: 'rgba(0, 180, 255, 0.1)',
        borderColor: 'rgba(0, 180, 255, 0.4)',
    },
];
