// Generated authentic vehicle fleets for MEA_FLEETS

export const MEA_FLEETS = {
  // ==========================================
  // AE (20 Vehicles)
  // ==========================================
  AE: [
    {
      brand: "Toyota",
      category: "King of the Desert",
      name: "Land Cruiser 300",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser 300 VXR 3.5L Twin-Turbo",
      shortModel: "Land Cruiser 300",
      shortLabel: "\ud83d\ude99 Land Cruiser",
      powertrain: "3.5L V6 Twin-Turbo DOHC (409 hp, 650 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (110 L dual tank)`,
      driverMode: "Multi-Terrain Select \u00b7 Crawl Control \u00b7 Dune Mode",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Nissan",
      category: "Hero of All Terrain",
      name: "Nissan Patrol V8",
      icon: "\ud83d\ude99",
      model: "Nissan Patrol NISMO 5.6L V8 Desert Spec",
      shortModel: "Patrol V8 NISMO",
      shortLabel: "\ud83d\ude99 Patrol V8",
      powertrain: "5.6L V8 Naturally Aspirated Takumi-Tuned (428 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (140 L Desert Cruiser)`,
      driverMode: "Hydraulic Body Motion Control (HBMC) \u00b7 Sand Mode",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Lexus",
      category: "VIP Luxury SUV",
      name: "Lexus LX 600",
      icon: "\ud83d\ude99",
      model: "Lexus LX 600 VIP 4-Seater Ultra Luxury",
      shortModel: "Lexus LX 600",
      shortLabel: "\ud83d\ude99 Lexus LX 600",
      powertrain: "3.5L V6 Twin-Turbo Dual VVT-i (409 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (110 L)`,
      driverMode: "Active Height Control (AHC) \u00b7 Mark Levinson 25-speaker",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Mercedes-AMG",
      category: "Iconic Desert Luxury",
      name: "Mercedes G 63 AMG",
      icon: "\ud83d\ude99",
      model: "Mercedes-AMG G 63 V8 Biturbo Edition 55",
      shortModel: "AMG G 63",
      shortLabel: "\ud83d\ude99 AMG G 63",
      powertrain: "4.0L V8 Biturbo Handcrafted AMG (577 hp, 850 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (100 L Super 98)`,
      driverMode: "AMG RIDE CONTROL \u00b7 3 Independent Locking Differentials",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Toyota",
      category: "Dubai RTA Smart Fleet",
      name: "Dubai Taxi Camry",
      icon: "\ud83d\ude95",
      model: "Dubai RTA Toyota Camry Hybrid Smart Taxi",
      shortModel: "Dubai Taxi Camry",
      shortLabel: "\ud83d\ude95 Dubai Taxi",
      powertrain: "2.5L Dynamic Force Hybrid System (208 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery + Fuel Tank (26 km/l)`,
      driverMode: "RTA Automated Dispatch \u00b7 Telematics Speed Limiter",
      destinationList: ["Dubai International Airport DXB", "Mall of the Emirates", "Deira Gold Souk", "Burj Al Arab Jumeirah"],
    },
    {
      brand: "Porsche",
      category: "High-Performance SUV",
      name: "Porsche Cayenne GTS",
      icon: "\ud83d\ude99",
      model: "Porsche Cayenne GTS 4.0L Twin-Turbo V8",
      shortModel: "Cayenne GTS",
      shortLabel: "\ud83d\ude99 Cayenne GTS",
      powertrain: "4.0L Twin-Turbo V8 Engine (500 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (90 L Super Plus)`,
      driverMode: "Porsche Active Suspension Management (PASM) \u00b7 Sport Chrono",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Rolls-Royce",
      category: "Apex Ultra-Luxury",
      name: "Rolls-Royce Cullinan",
      icon: "\ud83d\udc51",
      model: "Rolls-Royce Cullinan Black Badge V12 AWD",
      shortModel: "Cullinan Black Badge",
      shortLabel: "\ud83d\udc51 Cullinan",
      powertrain: "6.75L Twin-Turbocharged V12 (592 hp, 900 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (100 L)`,
      driverMode: "Magic Carpet Ride \u00b7 Self-Leveling Air Suspension",
      destinationList: ["Emirates Palace Abu Dhabi", "Burj Al Arab Helipad", "DIFC Gate Village", "One&Only Royal Mirage"],
    },
    {
      brand: "Range Rover",
      category: "Executive Luxury SUV",
      name: "Range Rover SV",
      icon: "\ud83d\ude99",
      model: "Range Rover SV Autobiography Long Wheelbase",
      shortModel: "Range Rover SV",
      shortLabel: "\ud83d\ude99 Range Rover",
      powertrain: "4.4L Twin-Turbo V8 Mild Hybrid (523 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (90 L)`,
      driverMode: "Executive Class Comfort Plus \u00b7 Terrain Response 2 Dynamic",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Lamborghini",
      category: "Super Sports SUV",
      name: "Lamborghini Urus",
      icon: "\ud83c\udfce\ufe0f",
      model: "Lamborghini Urus Performante 4.0 V8 BiTurbo",
      shortModel: "Lamborghini Urus",
      shortLabel: "\ud83c\udfce\ufe0f Lambo Urus",
      powertrain: "4.0L Twin-Turbo V8 (666 hp, 0-100 km/h in 3.3s)",
      paintColor: "#eab308",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (85 L Super 98)`,
      driverMode: "ANIMA Selector: Strada / Sport / Corsa / Rally",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Tesla",
      category: "Electric Crossover",
      name: "Tesla Model Y",
      icon: "\u26a1",
      model: "Tesla Model Y Long Range AWD Gulf High-Ambient Spec",
      shortModel: "Model Y AWD",
      shortLabel: "\u26a1 Model Y",
      powertrain: "Dual Motor All-Wheel Drive Electric (384 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 78.1 kWh High-Ambient Battery (533 km WLTP)`,
      driverMode: "Cabin Overheat Protection \u00b7 Autopilot HW4",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "BMW",
      category: "Flagship Luxury Saloon",
      name: "BMW 7 Series",
      icon: "\ud83d\ude97",
      model: "BMW 740i M Sport Individual Theatre Screen",
      shortModel: "BMW 740i",
      shortLabel: "\ud83d\ude97 BMW 7 Series",
      powertrain: "3.0L TwinPower Turbo Inline-6 48V (381 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (74 L)`,
      driverMode: "BMW 31.3\" 8K Theatre Screen \u00b7 Driving Assistant Professional",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Audi",
      category: "Performance SUV Coup\u00e9",
      name: "Audi RS Q8",
      icon: "\ud83d\ude99",
      model: "Audi RS Q8 4.0 TFSI quattro Carbon Black",
      shortModel: "Audi RS Q8",
      shortLabel: "\ud83d\ude99 Audi RS Q8",
      powertrain: "4.0L V8 Twin-Turbo Mild-Hybrid (600 hp, 800 Nm)",
      paintColor: "#1e1b4b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (85 L)`,
      driverMode: "quattro Sports Differential \u00b7 RS Ceramic Brakes",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Toyota",
      category: "Desert Adventure 4x4",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser Prado 2.4L Turbo Adventure",
      shortModel: "Toyota Prado",
      shortLabel: "\ud83d\ude99 Toyota Prado",
      powertrain: "2.4L T24A-FTS Turbocharged Hybrid (326 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "Full-Time 4WD with Torsen Center Differential",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Nissan",
      category: "Dune Legend Y61",
      name: "Nissan Super Safari",
      icon: "\ud83d\ude99",
      model: "Nissan Patrol Super Safari Y61 4.8L Desert Legend",
      shortModel: "Super Safari Y61",
      shortLabel: "\ud83d\ude99 Super Safari",
      powertrain: "4.8L TB48DE DOHC Inline-6 (280 hp, 451 Nm)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Sub-Fuel Tank (135 L Total)`,
      driverMode: "Heavy-Duty Rigid Axles \u00b7 Rear Differential Lock",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Cadillac",
      category: "High-Power Luxury SUV",
      name: "Cadillac Escalade-V",
      icon: "\ud83d\ude99",
      model: "Cadillac Escalade-V 6.2L Supercharged V8 AWD",
      shortModel: "Escalade-V",
      shortLabel: "\ud83d\ude99 Escalade-V",
      powertrain: "6.2L Hand-Built Supercharged V8 (682 hp, 653 lb-ft)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (24 gal)`,
      driverMode: "Super Cruise Hands-Free \u00b7 Curved 38-inch OLED Display",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Genesis",
      category: "Korean Executive SUV",
      name: "Genesis GV80",
      icon: "\ud83d\ude99",
      model: "Genesis GV80 3.5T Prestige All-Wheel Drive",
      shortModel: "Genesis GV80",
      shortLabel: "\ud83d\ude99 Genesis GV80",
      powertrain: "3.5L Twin-Turbo V6 (375 hp, 530 Nm)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "Road Preview Electronic Suspension \u00b7 Ergo Motion Seats",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Ford",
      category: "American Muscle V8",
      name: "Ford Mustang GT",
      icon: "\ud83c\udfce\ufe0f",
      model: "Ford Mustang GT Premium 5.0L Coyote V8 6-Speed",
      shortModel: "Mustang GT 5.0",
      shortLabel: "\ud83c\udfce\ufe0f Mustang GT",
      powertrain: "5.0L Coyote Naturally Aspirated V8 (486 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16 gal)`,
      driverMode: "Active Valve Performance Dual Exhaust \u00b7 Track Apps",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Ferrari",
      category: "V12 Four-Door Thoroughbred",
      name: "Ferrari Purosangue",
      icon: "\ud83c\udfce\ufe0f",
      model: "Ferrari Purosangue 6.5L V12 Naturally Aspirated",
      shortModel: "Purosangue V12",
      shortLabel: "\ud83c\udfce\ufe0f Purosangue",
      powertrain: "6.5L 65\u00b0 Naturally Aspirated V12 (725 hp, 716 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (100 L Super 98)`,
      driverMode: "Ferrari Active Suspension Technology (FAST) \u00b7 4RM-S evo",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "McLaren",
      category: "Supercar Spider",
      name: "McLaren 750S",
      icon: "\ud83c\udfce\ufe0f",
      model: "McLaren 750S Spider 4.0L Twin-Turbo V8",
      shortModel: "McLaren 750S",
      shortLabel: "\ud83c\udfce\ufe0f McLaren 750S",
      powertrain: "4.0L M840T Twin-Turbocharged V8 (750 hp, 800 Nm)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (72 L Super 98)`,
      driverMode: "Proactive Chassis Control III \u00b7 Variable Drift Control",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
    {
      brand: "Mercedes-Maybach",
      category: "Peak Chauffeured Luxury",
      name: "Maybach S 680",
      icon: "\ud83d\udc51",
      model: "Mercedes-Maybach S 680 4MATIC 6.0L V12 Biturbo",
      shortModel: "Maybach S 680",
      shortLabel: "\ud83d\udc51 Maybach S680",
      powertrain: "6.0L V12 Biturbo Handcrafted (621 hp, 1,000 Nm)",
      paintColor: "#1f2937",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "First-Class Rear Compartment \u00b7 Active Road Noise Cancelling",
      destinationList: ["Burj Khalifa / Downtown Dubai", "Sheikh Zayed Road Corridor", "Palm Jumeirah Boardwalk", "Yas Marina Circuit, Abu Dhabi", "Dubai Mall Fashion Avenue", "Corniche Road, Abu Dhabi"],
    },
  ],
  // ==========================================
  // SA (20 Vehicles)
  // ==========================================
  SA: [
    {
      brand: "Toyota",
      category: "Bestselling Sedan in KSA",
      name: "Toyota Camry",
      icon: "\ud83d\ude97",
      model: "Toyota Camry GLX 2.5L Abdul Latif Jameel Spec",
      shortModel: "Toyota Camry",
      shortLabel: "\ud83d\ude97 Toyota Camry",
      powertrain: "2.5L 4-Cylinder DOHC Dual VVT-i (204 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.9 km/l Abdul Latif Jameel)`,
      driverMode: "Toyota Safety Sense \u00b7 Dynamic Radar Cruise",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Toyota",
      category: "King of the Saudi Desert",
      name: "Land Cruiser 300",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser 300 GXR 3.5 Twin-Turbo 4x4",
      shortModel: "Land Cruiser 300",
      shortLabel: "\ud83d\ude99 Land Cruiser",
      powertrain: "3.5L V6 Twin-Turbo Intercooler (409 hp, 650 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel Tank (110 L)`,
      driverMode: "Multi-Terrain Select with Crawl Control and Turn Assist",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Toyota",
      category: "Compact City Sedan",
      name: "Toyota Yaris",
      icon: "\ud83d\ude97",
      model: "Toyota Yaris YX 1.5L Sedan Abdul Latif Jameel",
      shortModel: "Toyota Yaris",
      shortLabel: "\ud83d\ude97 Toyota Yaris",
      powertrain: "1.5L 4-Cylinder DOHC Dual VVT-i (105 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (20.5 km/l)`,
      driverMode: "Pre-Collision System and Lane Departure Alert",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Hyundai",
      category: "Popular Executive Sedan",
      name: "Hyundai Elantra",
      icon: "\ud83d\ude97",
      model: "Hyundai Elantra Smart 2.0L MPI Sedan KSA",
      shortModel: "Hyundai Elantra",
      shortLabel: "\ud83d\ude97 Elantra KSA",
      powertrain: "2.0L Nu Smartstream MPI 4-Cylinder (159 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.3 km/l)`,
      driverMode: "SmartSense Blind-Spot View Monitor",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Toyota",
      category: "Indestructible Desert Bakkie",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux Adventure 4.0L V6 4x4 ALJ Spec",
      shortModel: "Hilux 4.0 V6",
      shortLabel: "\ud83d\udefb Hilux V6 KSA",
      powertrain: "4.0L 1GR-FE V6 Petrol (235 hp, 376 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "Rear Differential Lock \u00b7 Heavy Duty Suspension",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Nissan",
      category: "Reliable Daily Sedan",
      name: "Nissan Sunny",
      icon: "\ud83d\ude97",
      model: "Nissan Sunny SV 1.6L CVT Petromin Spec",
      shortModel: "Nissan Sunny",
      shortLabel: "\ud83d\ude97 Nissan Sunny",
      powertrain: "1.6L DOHC 16-Valve 4-Cylinder (118 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (19.3 km/l)`,
      driverMode: "Nissan Intelligent Mobility Forward Collision Warning",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Ford",
      category: "Middle East Executive Cruiser",
      name: "Ford Taurus",
      icon: "\ud83d\ude97",
      model: "Ford Taurus Titanium 2.0L EcoBoost FWD",
      shortModel: "Ford Taurus",
      shortLabel: "\ud83d\ude97 Ford Taurus",
      powertrain: "2.0L EcoBoost GTDI 4-Cylinder (232 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15.5 km/l)`,
      driverMode: "Blind Spot Information System \u00b7 13.2-inch Touchscreen",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Hyundai",
      category: "Compact Economy Sedan",
      name: "Hyundai Accent",
      icon: "\ud83d\ude97",
      model: "Hyundai Accent Smart Plus 1.5L MPI Sedan",
      shortModel: "Hyundai Accent",
      shortLabel: "\ud83d\ude97 Hyundai Accent",
      powertrain: "1.5L Smartstream MPI 4-Cylinder (115 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18.9 km/l)`,
      driverMode: "Forward Collision-Avoidance Assist",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "MG",
      category: "Popular Value Sedan",
      name: "MG 5",
      icon: "\ud83d\ude97",
      model: "MG 5 Deluxe 1.5L CVT Sedan KSA",
      shortModel: "MG 5 Sedan",
      shortLabel: "\ud83d\ude97 MG 5",
      powertrain: "1.5L DOHC 4-Cylinder 16V (118 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (19.5 km/l)`,
      driverMode: "360-degree Camera and Electric Sunroof",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Geely",
      category: "Rising Star Sedan",
      name: "Geely Emgrand",
      icon: "\ud83d\ude97",
      model: "Geely Emgrand Flagship 1.5L Wallan Spec",
      shortModel: "Geely Emgrand",
      shortLabel: "\ud83d\ude97 Geely Emgrand",
      powertrain: "1.5L DVVT 4-Cylinder (101 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.5 km/l)`,
      driverMode: "B-Segment Modular Architecture (BMA) Stability",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Changan",
      category: "Sporty Crossover Coupe",
      name: "Changan CS85",
      icon: "\ud83d\ude99",
      model: "Changan CS85 Coupe 2.0L Turbo BlueCore 8AT",
      shortModel: "Changan CS85",
      shortLabel: "\ud83d\ude99 Changan CS85",
      powertrain: "2.0L Turbo Direct Injection (233 hp, 360 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (14.1 km/l)`,
      driverMode: "Aisin 8-Speed Automatic \u00b7 Autonomous Emergency Braking",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Haval",
      category: "Family Mid-Size SUV",
      name: "Haval H6",
      icon: "\ud83d\ude99",
      model: "Haval H6 Supreme 2.0L Turbo 4WD",
      shortModel: "Haval H6",
      shortLabel: "\ud83d\ude99 Haval H6",
      powertrain: "2.0L Turbo 4-Cylinder GDI (201 hp, 320 Nm)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.7 km/l)`,
      driverMode: "Level 2 Autonomous Driving \u00b7 Auto Reversing Assist",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Lexus",
      category: "Executive Luxury Cruiser",
      name: "Lexus ES 350",
      icon: "\ud83d\ude97",
      model: "Lexus ES 350 F-Sport 3.5L V6 ALJ Edition",
      shortModel: "Lexus ES 350",
      shortLabel: "\ud83d\ude97 Lexus ES 350",
      powertrain: "3.5L V6 24-Valve DOHC Dual VVT-i (302 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.6 km/l)`,
      driverMode: "Lexus Safety System+ 2.5 \u00b7 Mark Levinson Audio",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Nissan",
      category: "Hero of the Dunes",
      name: "Nissan Patrol Platinum",
      icon: "\ud83d\ude99",
      model: "Nissan Patrol Platinum 5.6L V8 4WD Desert Hero",
      shortModel: "Patrol Platinum",
      shortLabel: "\ud83d\ude99 Nissan Patrol",
      powertrain: "5.6L V8 DOHC with VVEL and DIG (400 hp, 560 Nm)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (140 L Dual Fuel)`,
      driverMode: "Hydraulic Body Motion Control \u00b7 Sand/Rock Mode",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Toyota",
      category: "Family 7-Seater 4x4",
      name: "Toyota Fortuner",
      icon: "\ud83d\ude99",
      model: "Toyota Fortuner VX2 4.0L V6 4x4 ALJ Spec",
      shortModel: "Toyota Fortuner",
      shortLabel: "\ud83d\ude99 Fortuner V6",
      powertrain: "4.0L 1GR-FE V6 Dual VVT-i (235 hp, 376 Nm)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "Rear Differential Lock and Hill-Start Assist Control",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Kia",
      category: "Subcompact Value Sedan",
      name: "Kia Pegas",
      icon: "\ud83d\ude97",
      model: "Kia Pegas EX 1.4L MPI Automatic Al Jabr Spec",
      shortModel: "Kia Pegas",
      shortLabel: "\ud83d\ude97 Kia Pegas",
      powertrain: "1.4L Kappa MPI 4-Cylinder (95 hp)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.8 km/l)`,
      driverMode: "Electronic Stability Control and Rear Parking Sensors",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Genesis",
      category: "Korean Flagship Sedan",
      name: "Genesis G80",
      icon: "\ud83d\ude97",
      model: "Genesis G80 Royal 3.5T AWD Twin-Turbo",
      shortModel: "Genesis G80",
      shortLabel: "\ud83d\ude97 Genesis G80",
      powertrain: "3.5L Twin-Turbo V6 (375 hp, 530 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (73 L)`,
      driverMode: "Forward Attention Warning \u00b7 Lexicon Quantum Logic Audio",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Chevrolet",
      category: "Full-Size Family SUV",
      name: "Chevrolet Tahoe",
      icon: "\ud83d\ude99",
      model: "Chevrolet Tahoe Premier 5.3L V8 4WD Aljomaih",
      shortModel: "Chevy Tahoe",
      shortLabel: "\ud83d\ude99 Tahoe 4WD",
      powertrain: "5.3L EcoTec3 V8 with Dynamic Fuel Mgmt (355 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (91 L)`,
      driverMode: "Magnetic Ride Control \u00b7 10.2-inch Diagonal Touchscreen",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "Isuzu",
      category: "Heavy-Duty Work Bakkie",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max GT 3.0L Turbo Diesel 4x4 KSA",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb D-Max KSA",
      powertrain: "3.0L 4JJ3-TCX Ddi Blue Power Turbo Diesel (190 hp)",
      paintColor: "#e11d48",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (76 L)`,
      driverMode: "Rough Terrain Mode \u00b7 Terrain Command 4WD",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
    {
      brand: "GMC",
      category: "Supreme Luxury SUV",
      name: "GMC Yukon Denali",
      icon: "\ud83d\ude99",
      model: "GMC Yukon Denali Ultimate 6.2L V8 4WD KSA Spec",
      shortModel: "Yukon Denali",
      shortLabel: "\ud83d\ude99 Yukon Denali",
      powertrain: "6.2L EcoTec3 V8 with 10-Speed Transmission (420 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (91 L)`,
      driverMode: "Air Ride Adaptive Suspension \u00b7 18-Speaker Bose Performance",
      destinationList: ["Kingdom Centre / Olaya, Riyadh", "King Fahd Road, Riyadh", "Jeddah Corniche / Waterfront", "Al-Balad Historical District, Jeddah", "Corniche Al Khobar", "Haramain High-Speed Rail Corridor"],
    },
  ],
  // ==========================================
  // EG (20 Vehicles)
  // ==========================================
  EG: [
    {
      brand: "Nissan",
      category: "Locally Assembled Sedan",
      name: "Nissan Sunny",
      icon: "\ud83d\ude97",
      model: "Nissan Sunny Super Saloon 1.5L Giza Plant",
      shortModel: "Nissan Sunny",
      shortLabel: "\ud83d\ude97 Sunny Giza",
      powertrain: "1.5L HR15DE 4-Cylinder DOHC (108 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled in Giza, Egypt (15.5 km/l)`,
      driverMode: "Dual SRS Airbags \u00b7 ABS with EBD and Brake Assist",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Chery",
      category: "Egyptian-Assembled SUV",
      name: "Chery Tiggo 7",
      icon: "\ud83d\ude99",
      model: "Chery Tiggo 7 Highline 1.5T Abou Ghali Egypt",
      shortModel: "Chery Tiggo 7",
      shortLabel: "\ud83d\ude99 Tiggo 7 Egypt",
      powertrain: "1.5L Turbocharged 4-Cylinder (145 hp, 210 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled at Abou Ghali Motors, Egypt`,
      driverMode: "Panoramic Sunroof \u00b7 9-inch HD Touchscreen",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Hyundai",
      category: "Evergreen Egyptian Favorite",
      name: "Hyundai Elantra HD",
      icon: "\ud83d\ude97",
      model: "Hyundai Elantra HD 1.6L MPI GB Ghabbour Auto",
      shortModel: "Elantra HD",
      shortLabel: "\ud83d\ude97 Elantra HD",
      powertrain: "1.6L Gamma MPI 4-Cylinder (121 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% GB Ghabbour Auto Suez Plant (15 km/l)`,
      driverMode: "Air Conditioning with Micro-filter \u00b7 Electric Power Steering",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "BYD",
      category: "Cairo CNG Taxi & Sedan",
      name: "BYD F3",
      icon: "\ud83d\ude97",
      model: "BYD F3 Dual-Fuel CNG / Petrol Cairo Taxi",
      shortModel: "BYD F3 Taxi",
      shortLabel: "\ud83d\ude95 BYD F3 Taxi",
      powertrain: "1.5L Mitsubishi 4G15S Engine (107 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel: Compressed Natural Gas (CNG) + Petrol`,
      driverMode: "Eco-friendly CNG Conversion approved by Egyptian Gov",
      destinationList: ["Cairo International Airport", "Ramses Railway Station", "Giza Square", "Maadi Grand Mall"],
    },
    {
      brand: "Toyota",
      category: "Reliable Japanese Sedan",
      name: "Toyota Corolla",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla Active Plus 1.6L Dual VVT-i",
      shortModel: "Toyota Corolla",
      shortLabel: "\ud83d\ude97 Toyota Corolla",
      powertrain: "1.6L 1ZR-FE 4-Cylinder Dual VVT-i (120 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17 km/l)`,
      driverMode: "Vehicle Stability Control (VSC) \u00b7 7 Airbags",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Fiat",
      category: "Popular Italian Sedan",
      name: "Fiat Tipo",
      icon: "\ud83d\ude97",
      model: "Fiat Tipo Sedan 1.4L Fire 6-Speed Manual",
      shortModel: "Fiat Tipo",
      shortLabel: "\ud83d\ude97 Fiat Tipo",
      powertrain: "1.4L Fire 4-Cylinder 16V (95 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16 km/l)`,
      driverMode: "Uconnect 7-inch HD LIVE with Apple CarPlay",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Chery",
      category: "Accessible Family Sedan",
      name: "Chery Arrizo 5",
      icon: "\ud83d\ude97",
      model: "Chery Arrizo 5 Highline 1.5L DVVT Ghabbour",
      shortModel: "Chery Arrizo 5",
      shortLabel: "\ud83d\ude97 Arrizo 5",
      powertrain: "1.5L DVVT 4-Cylinder DOHC (114 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% GB Ghabbour Auto Assembly`,
      driverMode: "Push Start Button and Rear View Camera with Guidelines",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "MG",
      category: "Popular Compact Crossover",
      name: "MG ZS",
      icon: "\ud83d\ude99",
      model: "MG ZS Luxury 1.5L DOHC 4-Speed Mansour Auto",
      shortModel: "MG ZS",
      shortLabel: "\ud83d\ude99 MG ZS",
      powertrain: "1.5L Naturally Aspirated 4-Cylinder (119 hp)",
      paintColor: "#e11d48",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Mansour Automotive Egypt (16.2 km/l)`,
      driverMode: "Tire Pressure Monitoring System (TPMS) \u00b7 Cruise Control",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Renault",
      category: "French Styled Sedan",
      name: "Renault Megane",
      icon: "\ud83d\ude97",
      model: "Renault Megane Grand Coupe 1.3 TCe Turbo Signature",
      shortModel: "Megane Grand Coupe",
      shortLabel: "\ud83d\ude97 Renault Megane",
      powertrain: "1.3L Turbocharged TCe 4-Cylinder (150 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.5 km/l)`,
      driverMode: "Easy Link 9.3-inch Multimedia with 3D Navigation",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Suzuki",
      category: "Economical Sedan",
      name: "Suzuki Dzire",
      icon: "\ud83d\ude97",
      model: "Suzuki Dzire GLX 1.2L Dualjet AGS Automate",
      shortModel: "Suzuki Dzire",
      shortLabel: "\ud83d\ude97 Suzuki Dzire",
      powertrain: "1.2L K12M Dualjet 4-Cylinder (82 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (21 km/l)`,
      driverMode: "Auto Gear Shift (AGS) \u00b7 Engine Push Start-Stop",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Kia",
      category: "Bestselling Crossover",
      name: "Kia Sportage",
      icon: "\ud83d\ude99",
      model: "Kia Sportage Topline 1.6 T-GDi Turbo EIT Egypt",
      shortModel: "Kia Sportage",
      shortLabel: "\ud83d\ude99 Kia Sportage",
      powertrain: "1.6L T-GDi Smartstream Turbo (180 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Egyptian International Trading (EIT) Spec`,
      driverMode: "Forward Collision-Avoidance Assist \u00b7 Curved Display",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Hyundai",
      category: "Modern Crossover",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson NX4 1.6 T-GDi Ghabbour Auto",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Hyundai Tucson",
      powertrain: "1.6L T-GDi Smartstream 4-Cylinder (180 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% GB Ghabbour Auto (14.5 km/l)`,
      driverMode: "Parametric Hidden Lights \u00b7 Lane Following Assist",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Mitsubishi",
      category: "Compact City Hatchback",
      name: "Mitsubishi Mirage",
      icon: "\ud83d\ude97",
      model: "Mitsubishi Mirage Highline 1.2L MIVEC Diamond",
      shortModel: "Mitsubishi Mirage",
      shortLabel: "\ud83d\ude97 Mirage Egypt",
      powertrain: "1.2L 3-Cylinder MIVEC DOHC (78 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (22.1 km/l)`,
      driverMode: "INVECS-III CVT \u00b7 Active Stability Control (ASC)",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Opel",
      category: "German Compact",
      name: "Opel Astra Turbo",
      icon: "\ud83d\ude97",
      model: "Opel Astra 1.2 Turbo Mansour Automotive",
      shortModel: "Opel Astra",
      shortLabel: "\ud83d\ude97 Opel Astra",
      powertrain: "1.2L Turbo Direct Injection 3-Cylinder (130 hp)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Mansour Automotive Egypt (17.5 km/l)`,
      driverMode: "Pure Panel Digital Cockpit \u00b7 IntelliLux LED Headlights",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Geely",
      category: "Sporty Compact Crossover",
      name: "Geely Coolray",
      icon: "\ud83d\ude99",
      model: "Geely Coolray Flagship 1.5T Abou Ghali Auto",
      shortModel: "Geely Coolray",
      shortLabel: "\ud83d\ude99 Geely Coolray",
      powertrain: "1.5L Turbocharged 3-Cylinder (177 hp, 255 Nm)",
      paintColor: "#991b1b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Abou Ghali Motors (15.5 km/l)`,
      driverMode: "Automatic Parking Assistant \u00b7 360-degree Panoramic Camera",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Bajaj",
      category: "Egyptian Street Tuk-Tuk",
      name: "Bajaj Auto-Rickshaw",
      icon: "\ud83d\udefa",
      model: "Bajaj RE 205cc Tuk-Tuk Cairo Neighborhood Transit",
      shortModel: "Bajaj Tuk-Tuk",
      shortLabel: "\ud83d\udefa Cairo Tuk-Tuk",
      powertrain: "205cc 4-Stroke Single Cylinder DTS-i (10 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (36 km/l for narrow alleys)`,
      driverMode: "High Maneuverability in Cairo/Giza Local Transit",
      destinationList: ["Shubra Al-Kheima", "Imbaba Local Market", "Matariya Quarter", "Faisal Street, Giza"],
    },
    {
      brand: "Chevrolet",
      category: "Beloved Workhorse 'El-Dabbabah'",
      name: "Chevy El-Dabbabah",
      icon: "\ud83d\udefb",
      model: "Chevrolet T-Series El-Dabbabah Pickup 6th October",
      shortModel: "El-Dabbabah",
      shortLabel: "\ud83d\udefb El-Dabbabah",
      powertrain: "2.5L Turbo Diesel Direct Injection (79 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled in General Motors Egypt, 6th of October City`,
      driverMode: "Heavy-Duty Cargo Bed rated for agricultural and city trade",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Toyota",
      category: "Cairo Commuter Microbus",
      name: "Toyota HiAce Microbus",
      icon: "\ud83d\ude90",
      model: "Toyota HiAce 2.5 D-4D 14-Seater Cairo Microbus",
      shortModel: "Cairo Microbus",
      shortLabel: "\ud83d\ude90 Cairo Microbus",
      powertrain: "2.5L 2KD-FTV D-4D Common-Rail Diesel (101 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Heavy Passenger Transit)`,
      driverMode: "Reinforced Suspension for High-Frequency Egyptian Route Transit",
      destinationList: ["Ramses to Sixth of October City", "Helwan to Tahrir Square", "Giza to Haram Avenue", "Abbassiya to New Cairo"],
    },
    {
      brand: "Suzuki",
      category: "Affordable City Hatch",
      name: "Suzuki Alto",
      icon: "\ud83d\ude97",
      model: "Suzuki Alto 800cc Manual Modern Motors Egypt",
      shortModel: "Suzuki Alto",
      shortLabel: "\ud83d\ude97 Suzuki Alto",
      powertrain: "796cc F8D 3-Cylinder Fuel Injected (48 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (22 km/l Ultra-Saver)`,
      driverMode: "Front Power Windows \u00b7 Driver Airbag",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
    {
      brand: "Chery",
      category: "7-Seater Family Flagship",
      name: "Chery Tiggo 8 Pro",
      icon: "\ud83d\ude99",
      model: "Chery Tiggo 8 Pro Flagship 1.6 TGDI 7-Seater",
      shortModel: "Tiggo 8 Pro",
      shortLabel: "\ud83d\ude99 Tiggo 8 Pro",
      powertrain: "1.6L TGDI Direct Injection Turbo (197 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.5 km/l)`,
      driverMode: "Dual 12.3-inch Curved Displays \u00b7 Sony 8-Speaker Audio",
      destinationList: ["Tahrir Square, Cairo", "Giza Pyramids Plateau", "Zamalek / Gezira Island, Cairo", "New Administrative Capital, Cairo", "Stanley Bridge, Alexandria", "Cairo-Alexandria Desert Road"],
    },
  ],
  // ==========================================
  // ZA (20 Vehicles)
  // ==========================================
  ZA: [
    {
      brand: "Toyota",
      category: "South Africa's Undisputed Bakkie King",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux Raider 2.8 GD-6 4x4 Prospecton Durban",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Hilux Bakkie",
      powertrain: "2.8L Turbodiesel GD-6 (201 hp, 500 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built at Toyota Prospecton Plant, Durban (Diesel)`,
      driverMode: "Downhill Assist Control \u00b7 Heavy Duty Towing Hitch",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Volkswagen",
      category: "South Africa's People's Car",
      name: "VW Polo Vivo",
      icon: "\ud83d\ude97",
      model: "Volkswagen Polo Vivo 1.4 Trendline Kariega Built",
      shortModel: "Polo Vivo",
      shortLabel: "\ud83d\ude97 Polo Vivo",
      powertrain: "1.4L 4-Cylinder MPI (75 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built in Kariega (Uitenhage), Eastern Cape (16.5 km/l)`,
      driverMode: "Electronic Stability Programme (ESP) \u00b7 Tyre Pressure Monitor",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Ford",
      category: "Pretoria-Built Super Bakkie",
      name: "Ford Ranger",
      icon: "\ud83d\udefb",
      model: "Ford Ranger Wildtrak 2.0 Bi-Turbo 4x4 Silverton",
      shortModel: "Ranger Wildtrak",
      shortLabel: "\ud83d\udefb Ranger Bakkie",
      powertrain: "2.0L Bi-Turbo Diesel Panther (207 hp, 500 Nm)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built at Ford Silverton Assembly Plant, Pretoria`,
      driverMode: "SYNC 4A with 12-inch screen \u00b7 E-Shifter 10-Speed Transmission",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Isuzu",
      category: "Eastern Cape Tough Bakkie",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max 3.0 Ddi V-Cross 4x4 Struandale Gqeberha",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb D-Max Bakkie",
      powertrain: "3.0L Turbo Diesel 4JJ3 (190 hp, 450 Nm)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Manufactured in Struandale, Gqeberha (Port Elizabeth)`,
      driverMode: "Autonomous Emergency Braking \u00b7 Diff Lock",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Toyota",
      category: "Locally Built Hybrid Crossover",
      name: "Toyota Corolla Cross",
      icon: "\ud83d\ude99",
      model: "Toyota Corolla Cross 1.8 Hybrid XR Prospecton Durban",
      shortModel: "Corolla Cross SA",
      shortLabel: "\ud83d\ude99 Corolla Cross",
      powertrain: "1.8L 2ZR-FXE Full Hybrid System (121 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Manufactured at Prospecton Plant, Durban (23.3 km/l)`,
      driverMode: "Toyota Safety Sense \u00b7 Adaptive All-Speed Cruise Control",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Suzuki",
      category: "SA's Favorite Affordable Hatch",
      name: "Suzuki Swift",
      icon: "\ud83d\ude97",
      model: "Suzuki Swift 1.2 GLX Manual",
      shortModel: "Suzuki Swift",
      shortLabel: "\ud83d\ude97 Suzuki Swift",
      powertrain: "1.2L K12M Dualjet 4-Cylinder (82 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (20.4 km/l)`,
      driverMode: "7-inch Touchscreen Infotainment with Apple CarPlay",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Toyota",
      category: "Reliable Daily Hatch",
      name: "Toyota Starlet",
      icon: "\ud83d\ude97",
      model: "Toyota Starlet 1.5 XR Automatic",
      shortModel: "Toyota Starlet",
      shortLabel: "\ud83d\ude97 Starlet SA",
      powertrain: "1.5L K15B 4-Cylinder (103 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18.5 km/l)`,
      driverMode: "360-degree Panoramic View Monitor \u00b7 Cruise Control",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Hyundai",
      category: "Compact City Hatch",
      name: "Hyundai Grand i10",
      icon: "\ud83d\ude97",
      model: "Hyundai Grand i10 Fluid 1.2L Manual",
      shortModel: "Grand i10",
      shortLabel: "\ud83d\ude97 Grand i10",
      powertrain: "1.2L Kappa MPI 4-Cylinder (82 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.5 km/l)`,
      driverMode: "Rear Park Assist \u00b7 8-inch Touchscreen Display",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Nissan",
      category: "Beloved SA Half-Ton Bakkie",
      name: "Nissan NP200",
      icon: "\ud83d\udefb",
      model: "Nissan NP200 1.6 8V Rosslyn Plant Workhorse",
      shortModel: "Nissan NP200",
      shortLabel: "\ud83d\udefb NP200 Bakkie",
      powertrain: "1.6L 8-Valve Petrol K7M (85 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built at Rosslyn Plant, Pretoria (800 kg payload)`,
      driverMode: "Rubberised Cargo Bed \u00b7 High-Payload Leaf Springs",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Chery",
      category: "Popular Tech SUV",
      name: "Chery Tiggo 4 Pro",
      icon: "\ud83d\ude99",
      model: "Chery Tiggo 4 Pro 1.5T Elite CVT",
      shortModel: "Tiggo 4 Pro",
      shortLabel: "\ud83d\ude99 Tiggo 4 Pro",
      powertrain: "1.5L Turbocharged 4-Cylinder (145 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (14.7 km/l)`,
      driverMode: "10.25-inch Floating Infotainment \u00b7 Voice Command",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Haval",
      category: "Bestselling Chinese Crossover",
      name: "Haval Jolion",
      icon: "\ud83d\ude99",
      model: "Haval Jolion 1.5T Luxury 7DCT",
      shortModel: "Haval Jolion",
      shortLabel: "\ud83d\ude99 Haval Jolion",
      powertrain: "1.5L Turbo 4-Cylinder (141 hp, 210 Nm)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.3 km/l)`,
      driverMode: "Adaptive Cruise Control with Traffic Jam Assist",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Volkswagen",
      category: "Premium Hatchback from Kariega",
      name: "VW Polo",
      icon: "\ud83d\ude97",
      model: "Volkswagen Polo 1.0 TSI Life DSG Kariega Plant",
      shortModel: "VW Polo SA",
      shortLabel: "\ud83d\ude97 VW Polo",
      powertrain: "1.0L TSI 3-Cylinder Turbo (114 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built in Kariega for South Africa and Global Export`,
      driverMode: "Digital Cockpit \u00b7 Wireless App-Connect",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Toyota",
      category: "Tough 7-Seater 4x4",
      name: "Toyota Fortuner",
      icon: "\ud83d\ude99",
      model: "Toyota Fortuner 2.8 GD-6 4x4 VX Prospecton",
      shortModel: "Toyota Fortuner",
      shortLabel: "\ud83d\ude99 Fortuner SA",
      powertrain: "2.8L GD-6 Turbodiesel (201 hp, 500 Nm)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built at Toyota Prospecton Plant, Durban`,
      driverMode: "Auto-Disconnecting Differential \u00b7 JBL 11-Speaker Audio",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Kia",
      category: "Urban Compact SUV",
      name: "Kia Sonet",
      icon: "\ud83d\ude99",
      model: "Kia Sonet 1.5 EX CVT",
      shortModel: "Kia Sonet",
      shortLabel: "\ud83d\ude99 Kia Sonet",
      powertrain: "1.5L Smartstream 4-Cylinder MPI (113 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.7 km/l)`,
      driverMode: "Wireless Smartphone Charging \u00b7 Rear View Monitor",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Renault",
      category: "Punchy Urban Crossover",
      name: "Renault Kiger",
      icon: "\ud83d\ude99",
      model: "Renault Kiger 1.0 Turbo Zen CVT",
      shortModel: "Renault Kiger",
      shortLabel: "\ud83d\ude99 Renault Kiger",
      powertrain: "1.0L Turbo 3-Cylinder (99 hp)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18.5 km/l)`,
      driverMode: "205mm High Ground Clearance \u00b7 Multi-Sense Driving Modes",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Suzuki",
      category: "Spacious Family Hatch",
      name: "Suzuki Baleno",
      icon: "\ud83d\ude97",
      model: "Suzuki Baleno 1.5 GLX Automatic",
      shortModel: "Suzuki Baleno",
      shortLabel: "\ud83d\ude97 Suzuki Baleno",
      powertrain: "1.5L K15B 4-Cylinder (103 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18.5 km/l)`,
      driverMode: "Head-Up Display \u00b7 9-inch HD Display Audio",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Mahindra",
      category: "Rugged Farm Bakkie",
      name: "Mahindra Pik-Up",
      icon: "\ud83d\udefb",
      model: "Mahindra Pik-Up Karoo 2.2 mHawk 4x4 Durban Built",
      shortModel: "Mahindra Karoo",
      shortLabel: "\ud83d\udefb Mahindra Bakkie",
      powertrain: "2.2L mHawk Turbodiesel (138 hp, 320 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled at Mahindra Durban Plant`,
      driverMode: "Mechanical Locking Differential \u00b7 Bush Bar Bullbar",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Toyota",
      category: "Iconic Minibus Taxi",
      name: "Toyota Quantum Taxi",
      icon: "\ud83d\ude90",
      model: "Toyota Quantum 2.8 Ses'fikile 16-Seater Taxi Durban",
      shortModel: "Quantum Taxi",
      shortLabel: "\ud83d\ude90 Quantum Taxi",
      powertrain: "2.8L GD-6 Turbodiesel (154 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Built at Toyota Prospecton, Durban (Lifeblood of SA Transit)`,
      driverMode: "Emergency Exit Roof Hatch \u00b7 High Durability Fleet Suspension",
      destinationList: ["Noord Street Taxi Rank, JHB", "Bree Street Taxi Rank", "Station Deck Taxi Rank, Cape Town", "Warwick Junction, Durban"],
    },
    {
      brand: "BMW",
      category: "Pretoria Heritage Saloon",
      name: "BMW 3 Series",
      icon: "\ud83d\ude97",
      model: "BMW 320d M Sport Plant Rosslyn Heritage Edition",
      shortModel: "BMW 320d Rosslyn",
      shortLabel: "\ud83d\ude97 BMW 320d",
      powertrain: "2.0L TwinPower Turbo Diesel (188 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Heritage from BMW Plant Rosslyn, Pretoria (21 km/l)`,
      driverMode: "BMW Curved Display \u00b7 M Sport Suspension",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
    {
      brand: "Ford",
      category: "Luxury Family 4WD SUV",
      name: "Ford Everest",
      icon: "\ud83d\ude99",
      model: "Ford Everest Platinum 3.0 V6 4WD Silverton Built",
      shortModel: "Everest Platinum",
      shortLabel: "\ud83d\ude99 Everest V6",
      powertrain: "3.0L V6 EcoBlue Turbodiesel (247 hp, 600 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Manufactured at Ford Silverton Assembly, Pretoria`,
      driverMode: "Permanent 4WD with Terrain Management \u00b7 Active Park Assist 2.0",
      destinationList: ["Sandton City / Nelson Mandela Square, JHB", "V&A Waterfront, Cape Town", "Durban Golden Mile Beachfront", "Menlyn Maine, Pretoria", "Kruger National Park Gateway", "N1 Highway Johannesburg-Cape Town"],
    },
  ],
  // ==========================================
  // NG (20 Vehicles)
  // ==========================================
  NG: [
    {
      brand: "Toyota",
      category: "King of Nigerian Roads",
      name: "Toyota Corolla",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla LE 1.8L Nigerian Road King",
      shortModel: "Toyota Corolla",
      shortLabel: "\ud83d\ude97 Corolla Nigeria",
      powertrain: "1.8L 2ZR-FE Dual VVT-i (132 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (High Reliability for Nigerian Fuel)`,
      driverMode: "Reinforced Suspension for Pothole Resilience",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Toyota",
      category: "Legendary 'Big Daddy' Sedan",
      name: "Toyota Camry",
      icon: "\ud83d\ude97",
      model: "Toyota Camry XLE 'Muscle / Big Daddy' 2.5L",
      shortModel: "Camry Big Daddy",
      shortLabel: "\ud83d\ude97 Camry Nigeria",
      powertrain: "2.5L 2AR-FE 4-Cylinder DOHC (178 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Every Nigerian Mechanic Knows This Car)`,
      driverMode: "Heavy Duty Radiator and Tropical Climate Spec",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Toyota",
      category: "Tough Highway Bakkie",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux Double Cab 2.7L VVTi 4x4 Escort Spec",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Hilux Nigeria",
      powertrain: "2.7L 2TR-FE 4-Cylinder Petrol Dual VVT-i (164 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Heavy Industrial / Bank Escort Vehicle)`,
      driverMode: "Heavy Duty Bull Bar and Flashing Warning Beacons",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Lexus",
      category: "Nigerian Luxury Standard",
      name: "Lexus RX 350",
      icon: "\ud83d\ude99",
      model: "Lexus RX 350 AWD 3.5L V6 Nigerian Status Symbol",
      shortModel: "Lexus RX 350",
      shortLabel: "\ud83d\ude99 Lexus RX 350",
      powertrain: "3.5L 2GR-FE V6 DOHC 24V (275 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (The Signature Car of Lekki / Victoria Island)`,
      driverMode: "Mark Levinson Premium Surround \u00b7 High Ground Clearance",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Toyota",
      category: "VIP Dignitary Escort SUV",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser Prado TX-L 2.7L VIP Escort",
      shortModel: "Prado VIP Escort",
      shortLabel: "\ud83d\ude99 Toyota Prado",
      powertrain: "2.7L Dual VVT-i Petrol Engine (163 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (87 L with auxiliary tank)`,
      driverMode: "Full-Time 4WD with Siren and Escort Convoy Mode",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Mercedes-Benz",
      category: "Prestige Commercial Cruiser",
      name: "Mercedes C-Class",
      icon: "\ud83d\ude97",
      model: "Mercedes-Benz C 300 4MATIC Sedan Luxury",
      shortModel: "Mercedes C 300",
      shortLabel: "\ud83d\ude97 Mercedes C 300",
      powertrain: "2.0L Turbocharged Inline-4 (255 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Victoria Island Status Car)`,
      driverMode: "AMG Line Styling \u00b7 4MATIC All-Wheel Drive",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Toyota",
      category: "Interstate Highway Transit King",
      name: "Toyota Sienna",
      icon: "\ud83d\ude90",
      model: "Toyota Sienna LE 3.5L V6 Interstate Express Transit",
      shortModel: "Toyota Sienna",
      shortLabel: "\ud83d\ude90 Sienna Transit",
      powertrain: "3.5L 2GR-FE V6 (266 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Lagos-Benin-Abuja Interstate Hauler)`,
      driverMode: "Removable Second Row Seats for Heavy Commercial Goods",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Bajaj",
      category: "Yellow Keke Napep Tricycle",
      name: "Keke Napep Tricycle",
      icon: "\ud83d\udefa",
      model: "Bajaj RE 205cc Yellow Keke Napep Commercial Taxi",
      shortModel: "Keke Napep",
      shortLabel: "\ud83d\udefa Keke Napep",
      powertrain: "205cc 4-Stroke Air-Cooled Engine (10 hp)",
      paintColor: "#eab308",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (Navigates Lagos Traffic Jam 'Go-Slow')`,
      driverMode: "Yellow Commercial Fleet Body with Side Rain Tarpaulins",
      destinationList: ["Ikeja Under-Bridge, Lagos", "Yaba Bus Stop", "Wuse Market, Abuja", "Garki Area 1, Abuja"],
    },
    {
      brand: "Volkswagen",
      category: "Iconic Lagos Danfo Yellow Bus",
      name: "Danfo Commercial Bus",
      icon: "\ud83d\ude90",
      model: "Volkswagen Transporter T3/T4 Yellow Danfo Lagos Trot",
      shortModel: "Danfo Yellow Bus",
      shortLabel: "\ud83d\ude90 Danfo Bus",
      powertrain: "2.0L 4-Cylinder Air-Cooled / Water-Cooled Diesel",
      paintColor: "#facc15",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Unstoppable Spirit of Lagos Transit)`,
      driverMode: "Lagos State Commercial Yellow-and-Black Stripes Fleet",
      destinationList: ["Oshodi Transport Interchange, Lagos", "CMS Marina Bus Stop", "Mile 2 Interstate Terminal", "Ojuelegba Bus Stop"],
    },
    {
      brand: "Toyota",
      category: "Family Highway Cruiser",
      name: "Toyota Highlander",
      icon: "\ud83d\ude99",
      model: "Toyota Highlander Limited 3.5L V6 AWD",
      shortModel: "Highlander Limited",
      shortLabel: "\ud83d\ude99 Highlander",
      powertrain: "3.5L V6 DOHC with Dual VVT-i (295 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (72 L)`,
      driverMode: "Dynamic Torque Vectoring AWD \u00b7 3-Row Leather Seating",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Honda",
      category: "Iconic 'Evil Spirit' Sedan",
      name: "Honda Accord",
      icon: "\ud83d\ude97",
      model: "Honda Accord EX-L 'Evil Spirit / End of Discussion'",
      shortModel: "Honda Accord",
      shortLabel: "\ud83d\ude97 Accord Nigeria",
      powertrain: "2.4L DOHC i-VTEC 4-Cylinder (190 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Famous Nigerian Moniker)`,
      driverMode: "Leather Upholstery \u00b7 Sunroof and Robust Ride",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Range Rover",
      category: "Billionaire Island Spec",
      name: "Range Rover Sport",
      icon: "\ud83d\ude99",
      model: "Range Rover Sport HSE Dynamic Supercharged V6",
      shortModel: "Range Rover Sport",
      shortLabel: "\ud83d\ude99 Range Rover",
      powertrain: "3.0L Supercharged V6 (340 hp, 450 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Banana Island Luxury)`,
      driverMode: "Electronic Air Suspension with Wade Sensing",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Lexus",
      category: "Smooth Executive Sedan",
      name: "Lexus ES 350",
      icon: "\ud83d\ude97",
      model: "Lexus ES 350 Luxury Sedan 3.5L V6",
      shortModel: "Lexus ES 350",
      shortLabel: "\ud83d\ude97 Lexus ES 350",
      powertrain: "3.5L 2GR-FKS V6 (302 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Silky Smooth Luxury Ride)`,
      driverMode: "Panoramic Glass Roof \u00b7 Triple-Beam LED Headlamps",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Toyota",
      category: "Interstate 'Hummer Bus'",
      name: "Toyota HiAce Hummer Bus",
      icon: "\ud83d\ude90",
      model: "Toyota HiAce High-Roof Commuter 'Hummer Bus' 2.7L",
      shortModel: "HiAce Hummer Bus",
      shortLabel: "\ud83d\ude90 Hummer Bus",
      powertrain: "2.7L 2TR-FE 4-Cylinder Petrol (151 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Premier Interstate Luxury Passenger Transport)`,
      driverMode: "High-Roof Cabin with 16 High-Back Reclining Seats",
      destinationList: ["Jibowu Interstate Park, Lagos", "Maza-Maza Transport Terminal", "Utako Park, Abuja", "Waterlines, Port Harcourt"],
    },
    {
      brand: "Mitsubishi",
      category: "Rugged 4x4 Cruiser",
      name: "Mitsubishi Pajero",
      icon: "\ud83d\ude99",
      model: "Mitsubishi Pajero GLS 3.8L V6 Gold Badge 4x4",
      shortModel: "Mitsubishi Pajero",
      shortLabel: "\ud83d\ude99 Pajero 4x4",
      powertrain: "3.8L 24-Valve SOHC V6 MIVEC (250 hp)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (88 L with Dual Range 4WD)`,
      driverMode: "Super Select 4WD-II with Rear Differential Lock",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Lexus",
      category: "Bulletproof Luxury V8",
      name: "Lexus GX 460",
      icon: "\ud83d\ude99",
      model: "Lexus GX 460 4.6L V8 Armored / Escort Ready",
      shortModel: "Lexus GX 460",
      shortLabel: "\ud83d\ude99 Lexus GX 460",
      powertrain: "4.6L V8 32-Valve DOHC Dual VVT-i (301 hp)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Kinetic Dynamic Suspension System)`,
      driverMode: "Full-Time 4WD with Torsen Limited-Slip Differential",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Mercedes-AMG",
      category: "Banana Island King",
      name: "Mercedes G 63 AMG",
      icon: "\ud83d\ude99",
      model: "Mercedes-AMG G 63 BiTurbo Banana Island Special",
      shortModel: "AMG G 63 Lagos",
      shortLabel: "\ud83d\ude99 G 63 Lagos",
      powertrain: "4.0L V8 Biturbo Handcrafted AMG (577 hp, 850 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (100 L)`,
      driverMode: "Twin Side-Exit Exhausts \u00b7 AMG Night Package",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Innoson",
      category: "Proudly Made in Nigeria",
      name: "Innoson IVM G5T",
      icon: "\ud83d\ude99",
      model: "Innoson IVM G5T 1.5L Turbo Smart SUV Nnewi Built",
      shortModel: "Innoson IVM G5T",
      shortLabel: "\ud83d\ude99 Innoson IVM",
      powertrain: "1.5L Turbocharged Engine (171 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Manufactured in Nnewi, Anambra State, Nigeria`,
      driverMode: "Smart Keyless Entry \u00b7 Automatic Air Conditioning",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Hyundai",
      category: "Lagos-Assembled Sedan",
      name: "Hyundai Elantra",
      icon: "\ud83d\ude97",
      model: "Hyundai Elantra GLS 1.8L Stallion Motors Lagos",
      shortModel: "Elantra Stallion",
      shortLabel: "\ud83d\ude97 Elantra Lagos",
      powertrain: "1.8L Nu MPI 4-Cylinder (148 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled by Stallion Group, Lagos, Nigeria`,
      driverMode: "6-Speed Automatic Transmission with Shiftronic",
      destinationList: ["Victoria Island / Eko Atlantic, Lagos", "Lekki Phase 1 / Admiralty Way, Lagos", "Maitama District, Abuja", "Central Business District, Abuja", "GRA Phase 2, Port Harcourt", "Lagos-Ibadan Expressway"],
    },
    {
      brand: "Peugeot",
      category: "Legendary Heritage Taxi",
      name: "Peugeot 504 Vintage",
      icon: "\ud83d\ude97",
      model: "Peugeot 504 Saloon 2.0L Heritage Nigerian Taxi",
      shortModel: "Peugeot 504 Taxi",
      shortLabel: "\ud83d\ude97 Peugeot 504",
      powertrain: "2.0L XN1 Carbureted 4-Cylinder (96 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Heritage Fuel Tank (Classic French-Nigerian Tank)`,
      driverMode: "Unbreakable Long-Travel Heavy Duty Coil Spring Suspension",
      destinationList: ["Kaduna Central Market", "Kano City Gate", "Ibadan Dugbe Junction", "Enugu Okpara Square"],
    },
  ],
  // ==========================================
  // KE (20 Vehicles)
  // ==========================================
  KE: [
    {
      brand: "Toyota",
      category: "Indestructible Kenyan Hauler",
      name: "Toyota Probox",
      icon: "\ud83d\ude97",
      model: "Toyota Probox DX 1.5L Indestructible Kenyan Hauler",
      shortModel: "Toyota Probox",
      shortLabel: "\ud83d\ude97 Toyota Probox",
      powertrain: "1.5L 1NZ-FE 4-Cylinder VVT-i (109 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Carries 1 Ton of Miraa / Cabbages at 140 km/h)`,
      driverMode: "Leaf Spring Solid Rear Axle \u00b7 High Ground Clearance",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "King of Nairobi Estates",
      name: "Toyota Fielder",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla Fielder 1.5L Hybrid Estate",
      shortModel: "Toyota Fielder",
      shortLabel: "\ud83d\ude97 Toyota Fielder",
      powertrain: "1.5L 1NZ-FXE Hybrid Synergy Drive (100 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel System (26 km/l)`,
      driverMode: "Toyota Safety Sense C \u00b7 Cavernous Cargo Bay",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "Tough Safari & Farm Truck",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux 2.8L GD-6 4x4 Double Cab Kenya Spec",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Hilux Kenya",
      powertrain: "2.8L GD-6 Turbodiesel Intercooler (201 hp, 500 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Heavy Duty Kenya Farm & Safari Spec)`,
      driverMode: "Heavy Duty Bull Bar with Snorkel and Winch",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Isuzu",
      category: "Built by Isuzu East Africa",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max 3.0L Double Cab Isuzu East Africa Nairobi",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb D-Max Nairobi",
      powertrain: "3.0L 4JJ3-TCX Ddi Blue Power Turbo Diesel (190 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Assembled by Isuzu East Africa, Enterprise Road, Nairobi`,
      driverMode: "Terrain Command 4WD \u00b7 Heavy Duty Load Bed",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "Kenyan Dignitary Official 4x4",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser Prado TX-L 2.8L D-4D",
      shortModel: "Prado TX-L",
      shortLabel: "\ud83d\ude99 Toyota Prado",
      powertrain: "2.8L 1GD-FTV Turbodiesel 4x4 (201 hp, 500 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (87 L + Auxiliary Tank)`,
      driverMode: "Full-Time 4WD with Kinetic Dynamic Suspension (KDSS)",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Subaru",
      category: "Rift Valley Fast Wagon",
      name: "Subaru Outback",
      icon: "\ud83d\ude99",
      model: "Subaru Outback 2.5i Eyesight Symmetrical AWD",
      shortModel: "Subaru Outback",
      shortLabel: "\ud83d\ude99 Subaru Outback",
      powertrain: "2.5L FB25 Boxer 4-Cylinder DOHC (175 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Great Rift Valley Highway Cruiser)`,
      driverMode: "Symmetrical All-Wheel Drive with X-Mode",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "Kenyan Graffiti 'Nganya' Matatu",
      name: "Matatu Nganya Minibus",
      icon: "\ud83d\ude90",
      model: "Toyota HiAce Custom Graffiti 'Nganya' Matatu 14-Seater",
      shortModel: "Matatu Nganya",
      shortLabel: "\ud83d\ude90 Matatu Nganya",
      powertrain: "2.7L Petrol 2TR-FE (151 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Custom Airbrushed Artwork & LED Underglow & 2000W Bass`,
      driverMode: "High-Volume Sound System & Screens on Every Headrest",
      destinationList: ["Rongai to Nairobi CBD", "Kayole to Railway Station", "Ngong Road Terminal", "Eastleigh Section 1"],
    },
    {
      brand: "Toyota",
      category: "Popular Economy Hatch",
      name: "Toyota Vitz",
      icon: "\ud83d\ude97",
      model: "Toyota Vitz 1.0L Jewela 5-Door Hatchback",
      shortModel: "Toyota Vitz",
      shortLabel: "\ud83d\ude97 Toyota Vitz",
      powertrain: "1.0L 1KR-FE 3-Cylinder VVT-i (69 hp)",
      paintColor: "#e11d48",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (21.5 km/l City Fuel Saver)`,
      driverMode: "Smart Entry & Start System \u00b7 Ultra Compact Turning Circle",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Nissan",
      category: "Series-Hybrid Urban Crossover",
      name: "Nissan Note e-Power",
      icon: "\u26a1",
      model: "Nissan Note e-Power 1.2L Series Hybrid Medalist",
      shortModel: "Note e-Power",
      shortLabel: "\u26a1 Note e-Power",
      powertrain: "EM57 Electric Motor Driven (109 hp) + 1.2L Generator",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Series Hybrid (Electric drive with 34 km/l fuel economy)`,
      driverMode: "e-Pedal One-Pedal Driving \u00b7 Intelligent Forward Braking",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Mazda",
      category: "Efficient Nairobi Hatch",
      name: "Mazda Demio",
      icon: "\ud83d\ude97",
      model: "Mazda Demio 1.3L Skyactiv-G 5-Door",
      shortModel: "Mazda Demio",
      shortLabel: "\ud83d\ude97 Mazda Demio",
      powertrain: "1.3L Skyactiv-G Direct Injection (84 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (24.6 km/l Skyactiv Saver)`,
      driverMode: "i-Stop Idle Stop System \u00b7 Dynamic Stability Control",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "Luxury Urban Crossover",
      name: "Toyota Harrier",
      icon: "\ud83d\ude99",
      model: "Toyota Harrier Premium 2.0L Valvematic AWD",
      shortModel: "Toyota Harrier",
      shortLabel: "\ud83d\ude99 Toyota Harrier",
      powertrain: "2.0L 3ZR-FAE Valvematic 4-Cylinder (151 hp)",
      paintColor: "#1e1b4b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16 km/l)`,
      driverMode: "JBL Premium Sound \u00b7 Panoramic Moonroof \u00b7 Leather",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Mitsubishi",
      category: "Off-Road Heritage SUV",
      name: "Mitsubishi Pajero",
      icon: "\ud83d\ude99",
      model: "Mitsubishi Pajero Super Exceed 3.2L DI-D 4x4",
      shortModel: "Pajero 3.2 DI-D",
      shortLabel: "\ud83d\ude99 Pajero Kenya",
      powertrain: "3.2L 4M41 Common-Rail Turbo Diesel (197 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Heavy Bush Safari Ready)`,
      driverMode: "Super Select 4WD-II with Central and Rear Diff Locks",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Suzuki",
      category: "Bolt / Uber ChapChap Taxi",
      name: "Suzuki Alto",
      icon: "\ud83d\ude97",
      model: "Suzuki Alto 800cc Bolt / Uber ChapChap Nairobi Taxi",
      shortModel: "Suzuki Alto Taxi",
      shortLabel: "\ud83d\ude95 Alto ChapChap",
      powertrain: "796cc 3-Cylinder Fuel Injected (48 hp)",
      paintColor: "#facc15",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (24 km/l The Backbone of App Ride-Hailing)`,
      driverMode: "Compact Dimensions for Nairobi Traffic Weaving",
      destinationList: ["Nairobi Westlands", "Kilimani Yaya Centre", "Nairobi Railway Station", "JKIA Airport Terminal 1"],
    },
    {
      brand: "Toyota",
      category: "Spacious Family Van",
      name: "Toyota Noah",
      icon: "\ud83d\ude90",
      model: "Toyota Noah Si 2.0L 7-Seater Dual Sliding Doors",
      shortModel: "Toyota Noah",
      shortLabel: "\ud83d\ude90 Toyota Noah",
      powertrain: "2.0L 3ZR-FAE Valvematic (152 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Comfortable 7-Passenger Family Shuttle)`,
      driverMode: "Dual Power Sliding Doors \u00b7 Flat-Floor Versatility",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Honda",
      category: "Hybrid Cargo Wagon",
      name: "Honda Fit Shuttle",
      icon: "\ud83d\ude97",
      model: "Honda Fit Shuttle Hybrid 1.3L IMA Smart Selection",
      shortModel: "Fit Shuttle",
      shortLabel: "\ud83d\ude97 Fit Shuttle",
      powertrain: "1.3L i-VTEC + Integrated Motor Assist Hybrid (98 hp)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% IMA Hybrid System (25 km/l)`,
      driverMode: "Ultra Seats Flexible Cargo Space \u00b7 Eco Assist Coach",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Isuzu",
      category: "Heavy Cargo King of Mombasa Road",
      name: "Isuzu FRR Truck",
      icon: "\ud83d\ude9b",
      model: "Isuzu FRR 90 Forward Medium Truck Mombasa Road Hauler",
      shortModel: "Isuzu FRR Truck",
      shortLabel: "\ud83d\ude9b Isuzu FRR",
      powertrain: "5.2L 4HK1-TCC Turbo Intercooled Diesel (190 hp, 510 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Heavy Commercial Diesel (Built by Isuzu East Africa)`,
      driverMode: "Air-Over-Hydraulic Brakes \u00b7 10-Ton Heavy Haul Chassis",
      destinationList: ["Mombasa Port Container Terminal", "Athi River Industrial Zone", "Nairobi Inland Container Depot", "Eldoret Town Grain Silos"],
    },
    {
      brand: "Bajaj",
      category: "The Ubiquitous Kenyan Boda Boda",
      name: "Boda Boda Boxer 150",
      icon: "\ud83c\udfcd\ufe0f",
      model: "Bajaj Boxer BM 150 Commercial Boda Boda Motorcycle",
      shortModel: "Boda Boda 150",
      shortLabel: "\ud83c\udfcd\ufe0f Boda Boda",
      powertrain: "144.8cc 4-Stroke Natural Air-Cooled Engine (12 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (55 km/l Lifeblood of Kenyan Last-Mile Travel)`,
      driverMode: "Heavy-Duty Dual Spring SNS Suspension for Pillion Passenger",
      destinationList: ["Kenyatta Market, Nairobi", "Gikomba Market", "Mombasa Ferry Likoni", "Kisumu Bus Park"],
    },
    {
      brand: "Land Rover",
      category: "Classic Safari Tour Cruiser",
      name: "Defender 110 Safari",
      icon: "\ud83d\ude99",
      model: "Land Rover Defender 110 300Tdi Open-Roof Safari 4x4",
      shortModel: "Defender Safari",
      shortLabel: "\ud83d\ude99 Defender Safari",
      powertrain: "2.5L 300Tdi Direct Injection Turbodiesel (111 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Diesel Tanks (Equipped for Maasai Mara Game Drives)`,
      driverMode: "Pop-Up Safari Viewing Roof with Bean Bags for Cameras",
      destinationList: ["Maasai Mara National Reserve", "Amboseli National Park", "Tsavo East Game Track", "Lake Nakuru National Park"],
    },
    {
      brand: "Subaru",
      category: "Turbocharged Highway Beast",
      name: "Subaru Forester XT",
      icon: "\ud83d\ude99",
      model: "Subaru Forester 2.0XT Boxer DIT Turbo AWD",
      shortModel: "Forester XT Turbo",
      shortLabel: "\ud83d\ude99 Forester XT",
      powertrain: "2.0L Direct Injection Turbo Boxer (250 hp, 350 Nm)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (0-100 km/h in 6.2s)`,
      driverMode: "SI-DRIVE (Subaru Intelligent Drive) \u00b7 Symmetrical AWD",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
    {
      brand: "Toyota",
      category: "Untamable Bush Pickup",
      name: "Land Cruiser 79",
      icon: "\ud83d\udefb",
      model: "Toyota Land Cruiser 79 Series 4.5L V8 Diesel Single Cab",
      shortModel: "Land Cruiser 79",
      shortLabel: "\ud83d\udefb LC79 Bush V8",
      powertrain: "4.5L 1VD-FTV Turbo Diesel V8 (202 hp, 430 Nm)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel Tanks (180 L Remote Kenya Range)`,
      driverMode: "Rigid Live Axles Front and Rear \u00b7 Heavy Winch Bar",
      destinationList: ["Kenyatta Avenue / CBD, Nairobi", "Westlands Commercial Hub, Nairobi", "Mombasa Old Town / Fort Jesus", "Kisumu Lakefront / Dunga Beach", "Nakuru Highway / Great Rift Valley", "Thika Superhighway, Nairobi"],
    },
  ],
};
