// Generated authentic vehicle fleets for OCEANIA_FLEETS

export const OCEANIA_FLEETS = {
  // ==========================================
  // AU (20 Vehicles)
  // ==========================================
  AU: [
    {
      brand: "Toyota",
      category: "Australia's #1 Ute",
      name: "Toyota HiLux",
      icon: "\ud83d\udefb",
      model: "Toyota HiLux SR5 4x4 Double Cab 2.8 Turbo-Diesel",
      shortModel: "Toyota HiLux",
      shortLabel: "\ud83d\udefb Toyota HiLux",
      powertrain: "2.8L 1GD-FTV 4-Cyl Turbo-Diesel (201 hp, 500 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Aussie Range)`,
      driverMode: "Downhill Assist \u00b7 Rear Diff Lock \u00b7 3.5T Towing",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Ford",
      category: "Aussie-Engineered Super Ute",
      name: "Ford Ranger Raptor",
      icon: "\ud83d\udefb",
      model: "Ford Ranger Raptor 3.0L Twin-Turbo V6 EcoBoost",
      shortModel: "Ranger Raptor",
      shortLabel: "\ud83d\udefb Ranger Raptor",
      powertrain: "3.0L Twin-Turbo EcoBoost V6 (392 hp, 583 Nm)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Premium)`,
      driverMode: "FOX 2.5 Live Valve Shocks \u00b7 Baja Off-Road Mode",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Isuzu",
      category: "Tough Aussie Bakkie",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max X-TERRAIN 4x4 Crew Cab 3.0L",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb Isuzu D-Max",
      powertrain: "3.0L 4JJ3-TCX 4-Cylinder Turbo Diesel (190 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (8.0 L/100km)`,
      driverMode: "Rough Terrain Mode \u00b7 IDAS Driver Assist",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Toyota",
      category: "Hybrid Family SUV",
      name: "Toyota RAV4 Hybrid",
      icon: "\ud83d\ude99",
      model: "Toyota RAV4 Cruiser 2.5L Hybrid Electric AWD",
      shortModel: "Toyota RAV4",
      shortLabel: "\ud83d\ude99 Toyota RAV4",
      powertrain: "2.5L Dynamic Force 4-Cylinder Hybrid (219 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery + Fuel Tank (4.8 L/100km)`,
      driverMode: "Toyota Safety Sense 2.5 \u00b7 Trail Mode AWD",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "MG",
      category: "Popular Value SUV",
      name: "MG ZS",
      icon: "\ud83d\ude99",
      model: "MG ZS Excite 1.5L Auto FWD",
      shortModel: "MG ZS",
      shortLabel: "\ud83d\ude99 MG ZS",
      powertrain: "1.5L 4-Cylinder Naturally Aspirated (114 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (6.7 L/100km)`,
      driverMode: "Reverse Camera \u00b7 Apple CarPlay & Cruise",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Mitsubishi",
      category: "Family 7-Seat PHEV",
      name: "Mitsubishi Outlander",
      icon: "\ud83d\ude99",
      model: "Mitsubishi Outlander Exceed PHEV AWD 7-Seat",
      shortModel: "Outlander PHEV",
      shortLabel: "\ud83d\ude99 Outlander PHEV",
      powertrain: "2.4L Engine + Dual Motors Super All-Wheel Control",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 20 kWh Battery + Fuel Tank (84 km EV range)`,
      driverMode: "Super All-Wheel Control (S-AWC) \u00b7 MI-PILOT Assist",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Tesla",
      category: "Electric Crossover",
      name: "Tesla Model Y",
      icon: "\u26a1",
      model: "Tesla Model Y RWD Australia Edition",
      shortModel: "Model Y RWD",
      shortLabel: "\u26a1 Model Y",
      powertrain: "Single-Motor RWD Electric (299 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 60 kWh LFP Battery (455 km WLTP)`,
      driverMode: "Autopilot \u00b7 High-Efficiency Heat Pump AC",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Hyundai",
      category: "Midsize SUV",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson Highlander 2.0 CRDi Diesel AWD",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Hyundai Tucson",
      powertrain: "2.0L CRDi 4-Cylinder Turbo Diesel (183 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (6.3 L/100km)`,
      driverMode: "Hyundai SmartSense with HTRAC AWD",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Mazda",
      category: "Refined Urban SUV",
      name: "Mazda CX-5",
      icon: "\ud83d\ude99",
      model: "Mazda CX-5 Akera 2.5L Turbo Petrol AWD",
      shortModel: "Mazda CX-5",
      shortLabel: "\ud83d\ude99 Mazda CX-5",
      powertrain: "2.5L Skyactiv-G Turbo Petrol (228 hp, 420 Nm)",
      paintColor: "#991b1b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (8.2 L/100km)`,
      driverMode: "i-Activ AWD \u00b7 360-degree View Monitor",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Toyota",
      category: "Outback King 4x4",
      name: "LandCruiser 300",
      icon: "\ud83d\ude99",
      model: "Toyota LandCruiser 300 Sahara ZX 3.3L Twin-Turbo",
      shortModel: "LandCruiser 300",
      shortLabel: "\ud83d\ude99 LandCruiser",
      powertrain: "3.3L V6 Twin-Turbo Diesel (304 hp, 700 Nm)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (110 L Outback Spec)`,
      driverMode: "Electronic Kinetic Dynamic Suspension (E-KDSS)",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Holden",
      category: "Legendary Aussie V8",
      name: "Holden Commodore SS",
      icon: "\ud83c\udfce\ufe0f",
      model: "Holden Commodore SS-V Redline 6.2L LS3 V8",
      shortModel: "Commodore SS V8",
      shortLabel: "\ud83c\udfce\ufe0f Commodore SS",
      powertrain: "6.2L GM LS3 Naturally Aspirated V8 (408 hp, 570 Nm)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Aussie Muscle Heritage)`,
      driverMode: "Brembo High-Performance Brakes \u00b7 Bi-Modal Exhaust",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Ford",
      category: "Aussie Barra Turbo Legend",
      name: "Ford Falcon XR6",
      icon: "\ud83c\udfce\ufe0f",
      model: "Ford Falcon XR6 Turbo 4.0L Barra 310T",
      shortModel: "Falcon XR6 Turbo",
      shortLabel: "\ud83c\udfce\ufe0f Falcon XR6",
      powertrain: "4.0L Barra 270T DOHC Turbo Inline-6 (362 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Legendary Aussie Inline-6)`,
      driverMode: "ZF 6-Speed Sports Auto \u00b7 LSD Rear Differential",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Kia",
      category: "Dynamic Crossover",
      name: "Kia Sportage",
      icon: "\ud83d\ude99",
      model: "Kia Sportage GT-Line 2.0L Diesel AWD",
      shortModel: "Kia Sportage",
      shortLabel: "\ud83d\ude99 Kia Sportage",
      powertrain: "2.0L CRDi 4-Cylinder Turbo Diesel (183 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (6.3 L/100km)`,
      driverMode: "DriveWise Active Safety \u00b7 Highway Driving Assist",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Subaru",
      category: "All-Wheel Drive SUV",
      name: "Subaru Forester",
      icon: "\ud83d\ude99",
      model: "Subaru Forester 2.5i-S Symmetrical AWD",
      shortModel: "Subaru Forester",
      shortLabel: "\ud83d\ude99 Forester AWD",
      powertrain: "2.5L Boxer 4-Cylinder Direct Injection (182 hp)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.4 L/100km)`,
      driverMode: "EyeSight 4.0 Driver Assist \u00b7 Dual X-Mode",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Toyota",
      category: "Family Bush Tourer",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota LandCruiser Prado Kakadu 2.8L Turbo Diesel",
      shortModel: "Toyota Prado",
      shortLabel: "\ud83d\ude99 Prado Kakadu",
      powertrain: "2.8L Turbo Diesel 4-Cylinder (201 hp, 500 Nm)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel Tanks (150 L Extended Range)`,
      driverMode: "Full-Time 4WD with Multi-Terrain Select",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Nissan",
      category: "Rugged Aussie Ute",
      name: "Nissan Navara",
      icon: "\ud83d\udefb",
      model: "Nissan Navara PRO-4X Warrior by Premcar 4x4",
      shortModel: "Navara Warrior",
      shortLabel: "\ud83d\udefb Navara Warrior",
      powertrain: "2.3L Twin-Turbo Diesel (188 hp, 450 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Premcar Tuned Aussie Off-Road Suspension`,
      driverMode: "Front Winch-Compatible Bullbar \u00b7 All-Terrain Cooper Tyres",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Volkswagen",
      category: "Premium V6 Ute",
      name: "VW Amarok V6",
      icon: "\ud83d\udefb",
      model: "Volkswagen Amarok PanAmericana 3.0 V6 TDI 4MOTION",
      shortModel: "Amarok V6",
      shortLabel: "\ud83d\udefb Amarok V6",
      powertrain: "3.0L V6 Turbo Diesel 4MOTION (247 hp, 600 Nm)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (8.4 L/100km)`,
      driverMode: "10-Speed Auto \u00b7 IQ.LIGHT Matrix LED \u00b7 3.5T Towing",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Hyundai",
      category: "Hot Hatch Performance",
      name: "Hyundai i30 N",
      icon: "\ud83c\udfce\ufe0f",
      model: "Hyundai i30 N Premium 2.0 T-GDi 8-DCT Hatch",
      shortModel: "Hyundai i30 N",
      shortLabel: "\ud83c\udfce\ufe0f i30 N",
      powertrain: "2.0L T-GDi Turbocharged 4-Cylinder (276 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (8.5 L/100km)`,
      driverMode: "N Grin Shift (NGS) \u00b7 Electronic Limited Slip Diff (e-LSD)",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "BYD",
      category: "Electric Sports Sedan",
      name: "BYD Seal",
      icon: "\u26a1",
      model: "BYD Seal Performance AWD 523 hp Blade Battery",
      shortModel: "BYD Seal AWD",
      shortLabel: "\u26a1 BYD Seal",
      powertrain: "Dual-Motor Electric All-Wheel Drive (523 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 82.5 kWh Blade Battery LFP (520 km WLTP)`,
      driverMode: "iTAC Intelligent Torque Adaption Control",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
    {
      brand: "Tesla",
      category: "Electric Sports Saloon",
      name: "Tesla Model 3",
      icon: "\u26a1",
      model: "Tesla Model 3 Highland Long Range AWD",
      shortModel: "Model 3 AWD",
      shortLabel: "\u26a1 Model 3",
      powertrain: "Dual Motor Electric AWD (498 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 78.1 kWh Battery (629 km WLTP)`,
      driverMode: "Autopilot \u00b7 360-degree Acoustic Glass Cabin",
      destinationList: ["Sydney Opera House / Circular Quay", "Federation Square, Melbourne", "Queen Street Mall, Brisbane", "Surfers Paradise, Gold Coast", "Cottesloe Beach, Perth", "Hume Highway Sydney-Melbourne"],
    },
  ],
  // ==========================================
  // NZ (20 Vehicles)
  // ==========================================
  NZ: [
    {
      brand: "Ford",
      category: "New Zealand's Top Ute",
      name: "Ford Ranger Wildtrak",
      icon: "\ud83d\udefb",
      model: "Ford Ranger Wildtrak 2.0L Bi-Turbo 4x4 NZ Spec",
      shortModel: "Ranger Wildtrak",
      shortLabel: "\ud83d\udefb Ranger NZ",
      powertrain: "2.0L Bi-Turbo Diesel Panther (207 hp, 500 Nm)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (7.6 L/100km)`,
      driverMode: "Full-Time 4WD with Terrain Management System",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Toyota",
      category: "Kiwi Farm and City Favorite",
      name: "Toyota HiLux SR5",
      icon: "\ud83d\udefb",
      model: "Toyota HiLux SR5 Cruiser 2.8 Turbo Diesel 4WD",
      shortModel: "HiLux SR5",
      shortLabel: "\ud83d\udefb HiLux Kiwi",
      powertrain: "2.8L Turbodiesel 1GD-FTV (201 hp, 500 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Built for rugged NZ backcountry)`,
      driverMode: "Downhill Assist Control \u00b7 3500kg Towing Capacity",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Toyota",
      category: "Kiwi Hybrid Bestseller",
      name: "Toyota RAV4 Hybrid",
      icon: "\ud83d\ude99",
      model: "Toyota RAV4 Limited Hybrid AWD New Zealand",
      shortModel: "Toyota RAV4",
      shortLabel: "\ud83d\ude99 RAV4 Hybrid",
      powertrain: "2.5L Hybrid System with E-Four All-Wheel Drive (219 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel System (4.8 L/100km Clean Car)`,
      driverMode: "Toyota Safety Sense \u00b7 Electric On-Demand E-Four AWD",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Mitsubishi",
      category: "PHEV Ski & Country SUV",
      name: "Mitsubishi Outlander PHEV",
      icon: "\ud83d\ude99",
      model: "Mitsubishi Outlander VRX PHEV AWD 4WD",
      shortModel: "Outlander PHEV",
      shortLabel: "\ud83d\ude99 Outlander PHEV",
      powertrain: "2.4L MIVEC Petrol + Twin Electric Motors S-AWC",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 20 kWh Battery + Fuel Tank (84 km pure EV range)`,
      driverMode: "Super All-Wheel Control with Mud/Snow/Tarmac Modes",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "BYD",
      category: "Top Selling Kiwi EV",
      name: "BYD Atto 3",
      icon: "\u26a1",
      model: "BYD Atto 3 Extended Range 60 kWh Blade",
      shortModel: "BYD Atto 3",
      shortLabel: "\u26a1 BYD Atto 3",
      powertrain: "Front Permanent Magnet Synchronous Motor (201 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 60.5 kWh Blade Battery LFP (420 km WLTP)`,
      driverMode: "DiPilot ADAS \u00b7 Rotating 15.6-inch Touchscreen",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Tesla",
      category: "Electric Crossover",
      name: "Tesla Model Y",
      icon: "\u26a1",
      model: "Tesla Model Y RWD Clean Car Discount Spec",
      shortModel: "Model Y RWD",
      shortLabel: "\u26a1 Model Y",
      powertrain: "Single-Motor RWD Electric (299 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 60 kWh Battery (455 km WLTP)`,
      driverMode: "Autopilot \u00b7 Ski Mountain Route Planning",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "MG",
      category: "Affordable Kiwi EV",
      name: "MG 4 EV",
      icon: "\u26a1",
      model: "MG 4 EV Excite 64 kWh 5-Door Hatch",
      shortModel: "MG 4 EV",
      shortLabel: "\u26a1 MG 4 EV",
      powertrain: "Rear-Wheel Drive Electric Motor (201 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 64 kWh Battery (450 km WLTP)`,
      driverMode: "MG Pilot Safety Suite \u00b7 50:50 Weight Distribution",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Suzuki",
      category: "Kiwi Compact Hybrid",
      name: "Suzuki Swift Hybrid",
      icon: "\ud83d\ude97",
      model: "Suzuki Swift GLX Hybrid 1.2 Dualjet CVT",
      shortModel: "Suzuki Swift",
      shortLabel: "\ud83d\ude97 Swift Hybrid",
      powertrain: "1.2L Dualjet Mild-Hybrid 12V System (82 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (4.1 L/100km Clean Car Rebate)`,
      driverMode: "Dual Sensor Brake Support \u00b7 Adaptive Cruise Control",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Kia",
      category: "Spacious Crossover",
      name: "Kia Sportage",
      icon: "\ud83d\ude99",
      model: "Kia Sportage Deluxe 2.0L Diesel AWD",
      shortModel: "Kia Sportage",
      shortLabel: "\ud83d\ude99 Kia Sportage",
      powertrain: "2.0L CRDi 4-Cylinder Turbo Diesel AWD (183 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (6.3 L/100km)`,
      driverMode: "Drive Wise Suite \u00b7 Multi-Terrain AWD Lock",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Toyota",
      category: "Mountain & Towing 4WD",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota LandCruiser Prado VX 2.8L Turbo Diesel",
      shortModel: "Toyota Prado",
      shortLabel: "\ud83d\ude99 Prado VX NZ",
      powertrain: "2.8L 4-Cylinder D-4D Turbo Diesel (201 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (87 L + Sub Tank)`,
      driverMode: "Full-Time 4WD with Kinetic Dynamic Suspension System",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Mitsubishi",
      category: "Workhorse Kiwi Ute",
      name: "Mitsubishi Triton",
      icon: "\ud83d\udefb",
      model: "Mitsubishi Triton VRX 4WD Double Cab 2.4L Bi-Turbo",
      shortModel: "Mitsu Triton",
      shortLabel: "\ud83d\udefb Triton 4WD",
      powertrain: "2.4L Bi-Turbo Diesel Clean Engine (201 hp, 470 Nm)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Super Select 4WD-II)`,
      driverMode: "Super Select II 4WD with Terrain Control",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Hyundai",
      category: "Midsize Kiwi SUV",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson Elite 1.6 T-GDi AWD N Line",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Tucson AWD",
      powertrain: "1.6L Turbo Gasoline Direct Injection (177 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.2 L/100km)`,
      driverMode: "HTRAC All-Wheel Drive \u00b7 SmartSense Active Safety",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Mazda",
      category: "Kiwi Family Cruiser",
      name: "Mazda CX-5",
      icon: "\ud83d\ude99",
      model: "Mazda CX-5 GSX 2.5L i-Activ AWD",
      shortModel: "Mazda CX-5",
      shortLabel: "\ud83d\ude99 Mazda CX-5",
      powertrain: "2.5L Skyactiv-G 4-Cylinder AWD (187 hp)",
      paintColor: "#991b1b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.4 L/100km)`,
      driverMode: "i-Activ AWD with Off-Road Traction Assist",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Nissan",
      category: "e-POWER Family SUV",
      name: "Nissan X-Trail",
      icon: "\ud83d\ude99",
      model: "Nissan X-Trail Ti-L e-POWER e-4ORCE AWD",
      shortModel: "X-Trail e-POWER",
      shortLabel: "\ud83d\ude99 X-Trail AWD",
      powertrain: "1.5L VC-Turbo + Dual Electric Motors e-4ORCE (211 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank with 100% Electric Motor Drive (6.1 L/100km)`,
      driverMode: "e-4ORCE All-Wheel Drive \u00b7 ProPILOT with Navi-link",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Tesla",
      category: "Electric Sedan",
      name: "Tesla Model 3",
      icon: "\u26a1",
      model: "Tesla Model 3 Highland RWD NZ Edition",
      shortModel: "Model 3 RWD",
      shortLabel: "\u26a1 Model 3",
      powertrain: "Single-Motor RWD Electric (279 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 60 kWh LFP Battery (513 km WLTP)`,
      driverMode: "Autopilot \u00b7 Enhanced Regenerative Braking",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Isuzu",
      category: "Rural Kiwi Ute",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max LS-U 4x4 Double Cab 3.0L Diesel",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb D-Max Kiwi",
      powertrain: "3.0L 4JJ3-TCX Turbo Diesel (190 hp, 450 Nm)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Heavy Rural / Farm Spec)`,
      driverMode: "Terrain Command 4WD with Rear Differential Lock",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Volkswagen",
      category: "Classic Kiwi Hatch",
      name: "VW Golf",
      icon: "\ud83d\ude97",
      model: "Volkswagen Golf R-Line 1.4 TSI 8-Speed Auto",
      shortModel: "VW Golf",
      shortLabel: "\ud83d\ude97 VW Golf",
      powertrain: "1.4L TSI 4-Cylinder Turbo (148 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (5.8 L/100km)`,
      driverMode: "Travel Assist \u00b7 IQ.Drive Active Safety",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Subaru",
      category: "All-Road Ski Wagon",
      name: "Subaru Outback",
      icon: "\ud83d\ude99",
      model: "Subaru Outback Touring 2.5i Symmetrical AWD",
      shortModel: "Subaru Outback",
      shortLabel: "\ud83d\ude99 Outback NZ",
      powertrain: "2.5L Direct Injection Boxer Symmetrical AWD (185 hp)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.3 L/100km)`,
      driverMode: "Dual-Function X-MODE for Mount Cook and Queenstown Snow",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Toyota",
      category: "Reliable Fleet Hatch",
      name: "Toyota Corolla",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla GX 1.8L Hybrid E-CVT",
      shortModel: "Toyota Corolla",
      shortLabel: "\ud83d\ude97 Corolla NZ",
      powertrain: "1.8L Petrol Hybrid System (138 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel System (4.0 L/100km Clean Car)`,
      driverMode: "Toyota Safety Sense 3.0 \u00b7 Pre-Collision Safety",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
    {
      brand: "Haval",
      category: "Kiwi Value Crossover",
      name: "Haval Jolion",
      icon: "\ud83d\ude99",
      model: "Haval Jolion Ultra Hybrid 1.5L DHT",
      shortModel: "Haval Jolion",
      shortLabel: "\ud83d\ude99 Jolion Hybrid",
      powertrain: "1.5L Dedicated Hybrid Transmission (188 hp, 375 Nm)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery + Fuel Tank (5.0 L/100km)`,
      driverMode: "360 Panoramic View \u00b7 Blind Spot Detection",
      destinationList: ["Queen Street / Waitemat\u0101, Auckland", "Te Papa / Oriental Parade, Wellington", "Cathedral Square, Christchurch", "Queenstown Lake Wakatipu", "Mount Maunganui, Tauranga", "State Highway 1 Desert Road"],
    },
  ],
};
