// Generated authentic vehicle fleets for REGIONAL_FLEETS

export const REGIONAL_FLEETS = {
  // ==========================================
  // GLOBAL (20 Vehicles)
  // ==========================================
  GLOBAL: [
    {
      brand: "Toyota",
      category: "World's Bestselling Sedan",
      name: "Toyota Corolla",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla 1.8L Hybrid Synergy Drive",
      shortModel: "Toyota Corolla",
      shortLabel: "\ud83d\ude97 Toyota Corolla",
      powertrain: "1.8L 4-Cylinder Hybrid System (138 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery + Fuel Tank (4.5 L/100km)`,
      driverMode: "Toyota Safety Sense \u00b7 Adaptive Cruise Control",
      destinationList: ["Metropolitan City Center", "International Airport", "Central Railway Hub", "Suburban Business Park"],
    },
    {
      brand: "Toyota",
      category: "World's Bestselling SUV",
      name: "Toyota RAV4",
      icon: "\ud83d\ude99",
      model: "Toyota RAV4 2.5L Hybrid All-Wheel Drive",
      shortModel: "Toyota RAV4",
      shortLabel: "\ud83d\ude99 Toyota RAV4",
      powertrain: "2.5L Dynamic Force Hybrid AWD (219 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (5.2 L/100km)`,
      driverMode: "Trail Mode AWD \u00b7 Lane Tracing Assist",
      destinationList: ["Harbor Waterfront", "University District", "Shopping Mall Ring Road", "Highway Interchange"],
    },
    {
      brand: "Honda",
      category: "Global Compact SUV",
      name: "Honda CR-V",
      icon: "\ud83d\ude99",
      model: "Honda CR-V 2.0L e:HEV Hybrid All-Wheel Drive",
      shortModel: "Honda CR-V",
      shortLabel: "\ud83d\ude99 Honda CR-V",
      powertrain: "2.0L Atkinson Cycle Hybrid (204 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel Tank (5.4 L/100km)`,
      driverMode: "Honda Sensing Safety Suite \u00b7 Real Time AWD",
      destinationList: ["Civic Square", "Commercial Boulevard", "Hospital District", "Suburban Expressway"],
    },
    {
      brand: "Tesla",
      category: "World's Bestselling EV",
      name: "Tesla Model Y",
      icon: "\u26a1",
      model: "Tesla Model Y Long Range All-Wheel Drive",
      shortModel: "Model Y AWD",
      shortLabel: "\u26a1 Model Y",
      powertrain: "Dual Motor All-Wheel Drive Electric (384 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 78.1 kWh Battery (533 km WLTP)`,
      driverMode: "Autopilot \u00b7 Route Planning with Supercharger stops",
      destinationList: ["Tech Park Campus", "Downtown Charging Hub", "Convention Center", "Financial District"],
    },
    {
      brand: "Toyota",
      category: "Global Midsize Sedan",
      name: "Toyota Camry",
      icon: "\ud83d\ude97",
      model: "Toyota Camry 2.5L Dynamic Force Hybrid",
      shortModel: "Toyota Camry",
      shortLabel: "\ud83d\ude97 Toyota Camry",
      powertrain: "2.5L 4-Cylinder Full Hybrid (218 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel Tank (4.4 L/100km)`,
      driverMode: "Dynamic Radar Cruise \u00b7 Blind Spot Monitor",
      destinationList: ["Government Secretariat", "Diplomatic Quarter", "Grand Hotel Entrance", "Business Express Route"],
    },
    {
      brand: "Honda",
      category: "Global Benchmark Compact",
      name: "Honda Civic",
      icon: "\ud83d\ude97",
      model: "Honda Civic 2.0L e:HEV Full Hybrid Hatchback",
      shortModel: "Honda Civic",
      shortLabel: "\ud83d\ude97 Honda Civic",
      powertrain: "2.0L Direct Injection e:HEV (181 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (4.7 L/100km)`,
      driverMode: "Traffic Jam Assist \u00b7 Agile Handling Assist",
      destinationList: ["High Street Promenade", "City Sports Complex", "West End District", "North Loop Highway"],
    },
    {
      brand: "Hyundai",
      category: "Global Compact SUV",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson 1.6 T-GDi Smartstream Hybrid",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Hyundai Tucson",
      powertrain: "1.6L Turbo Hybrid AWD (230 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Fuel Tank (5.6 L/100km)`,
      driverMode: "Highway Driving Assist \u00b7 Forward Collision Avoidance",
      destinationList: ["Metro Center Station", "East Gate Gateway", "Business Boulevard", "Lakeside Parkway"],
    },
    {
      brand: "Volkswagen",
      category: "Global Benchmark Hatchback",
      name: "VW Golf",
      icon: "\ud83d\ude97",
      model: "Volkswagen Golf 1.5 eTSI Mild-Hybrid DSG",
      shortModel: "VW Golf",
      shortLabel: "\ud83d\ude97 VW Golf",
      powertrain: "1.5L eTSI 4-Cylinder Turbo (150 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (5.2 L/100km)`,
      driverMode: "Travel Assist \u00b7 IQ.DRIVE Autonomous Braking",
      destinationList: ["Old Town Plaza", "Central Station", "Arts District", "Riverside Parkway"],
    },
    {
      brand: "Kia",
      category: "Global Family Crossover",
      name: "Kia Sportage",
      icon: "\ud83d\ude99",
      model: "Kia Sportage 1.6 T-GDi Turbo Hybrid AWD",
      shortModel: "Kia Sportage",
      shortLabel: "\ud83d\ude99 Kia Sportage",
      powertrain: "1.6L Turbo Hybrid (226 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (5.5 L/100km)`,
      driverMode: "Drive Wise Safety \u00b7 Lane Keeping Assist",
      destinationList: ["Main Street Interchange", "South Market Terminal", "Suburban Plaza", "Express Ringway"],
    },
    {
      brand: "Nissan",
      category: "Global Compact Sedan",
      name: "Nissan Sentra",
      icon: "\ud83d\ude97",
      model: "Nissan Sentra 2.0L DOHC Intelligent Mobility",
      shortModel: "Nissan Sentra",
      shortLabel: "\ud83d\ude97 Nissan Sentra",
      powertrain: "2.0L 4-Cylinder DOHC (149 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (6.7 L/100km)`,
      driverMode: "Nissan Safety Shield 360 \u00b7 Intelligent Forward Collision",
      destinationList: ["Crossroads Junction", "Grand Avenue", "North Terminal", "University Park"],
    },
    {
      brand: "BMW",
      category: "Global Executive Benchmark",
      name: "BMW 3 Series",
      icon: "\ud83d\ude97",
      model: "BMW 320i M Sport Steptronic Saloon",
      shortModel: "BMW 320i",
      shortLabel: "\ud83d\ude97 BMW 3 Series",
      powertrain: "2.0L TwinPower Turbo 4-Cylinder (184 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (6.4 L/100km)`,
      driverMode: "BMW Live Cockpit \u00b7 Driving Assistant",
      destinationList: ["Financial Plaza", "Grand Hotel Avenue", "Embassy Boulevard", "Airport Express Freeway"],
    },
    {
      brand: "Mercedes-Benz",
      category: "Global Luxury Saloon",
      name: "Mercedes C-Class",
      icon: "\ud83d\ude97",
      model: "Mercedes-Benz C 200 AMG Line Mild-Hybrid",
      shortModel: "Mercedes C 200",
      shortLabel: "\ud83d\ude97 Mercedes C-Class",
      powertrain: "1.5L Turbo + 48V Integrated Starter Generator (204 hp)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (6.3 L/100km)`,
      driverMode: "Active Distance Assist DISTRONIC \u00b7 MBUX Navigation",
      destinationList: ["Palace Promenade", "Executive Tower Square", "Central Banking District", "Harbor View Drive"],
    },
    {
      brand: "Audi",
      category: "Global Premium Saloon",
      name: "Audi A4",
      icon: "\ud83d\ude97",
      model: "Audi A4 40 TFSI S line S tronic",
      shortModel: "Audi A4",
      shortLabel: "\ud83d\ude97 Audi A4",
      powertrain: "2.0L TFSI 4-Cylinder Turbo Mild-Hybrid (204 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (6.2 L/100km)`,
      driverMode: "Audi Pre Sense \u00b7 Virtual Cockpit Plus",
      destinationList: ["Diplomatic Quarter", "Business Park Hub", "Opera House Square", "Northside Freeway"],
    },
    {
      brand: "Mazda",
      category: "Global Compact Crossover",
      name: "Mazda CX-5",
      icon: "\ud83d\ude99",
      model: "Mazda CX-5 2.5L Skyactiv-G All-Wheel Drive",
      shortModel: "Mazda CX-5",
      shortLabel: "\ud83d\ude99 Mazda CX-5",
      powertrain: "2.5L Skyactiv-G 4-Cylinder DOHC (187 hp)",
      paintColor: "#991b1b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.5 L/100km)`,
      driverMode: "G-Vectoring Control Plus \u00b7 i-Activ AWD",
      destinationList: ["Central Gardens", "Grand Boulevard", "West Hills Route", "Sunset Boulevard"],
    },
    {
      brand: "BYD",
      category: "Global Electric Crossover",
      name: "BYD Atto 3",
      icon: "\u26a1",
      model: "BYD Atto 3 Extended Range 60.5 kWh Blade EV",
      shortModel: "BYD Atto 3",
      shortLabel: "\u26a1 BYD Atto 3",
      powertrain: "Single Permanent Magnet Motor (201 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 60.5 kWh Blade Battery LFP (420 km WLTP)`,
      driverMode: "DiPilot Level 2 Driving Assist \u00b7 V2L Power Function",
      destinationList: ["Green Tech Hub", "Solar Park Boulevard", "Central Charging Superhub", "Metro Mall Terminal"],
    },
    {
      brand: "Volvo",
      category: "Global Safe Luxury SUV",
      name: "Volvo XC60",
      icon: "\ud83d\ude99",
      model: "Volvo XC60 B5 AWD Mild-Hybrid Plus",
      shortModel: "Volvo XC60",
      shortLabel: "\ud83d\ude99 Volvo XC60",
      powertrain: "2.0L Turbocharged 4-Cylinder 48V (247 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.4 L/100km)`,
      driverMode: "City Safety Collision Avoidance \u00b7 Pilot Assist",
      destinationList: ["Nordic Embassy", "Harbor Promenade", "Suburban Lake District", "Cross-Country Highway"],
    },
    {
      brand: "Subaru",
      category: "Global All-Weather Wagon",
      name: "Subaru Outback",
      icon: "\ud83d\ude99",
      model: "Subaru Outback 2.5i Symmetrical All-Wheel Drive",
      shortModel: "Subaru Outback",
      shortLabel: "\ud83d\ude99 Subaru Outback",
      powertrain: "2.5L SUBARU BOXER Direct Injection (182 hp)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (7.3 L/100km)`,
      driverMode: "EyeSight Driver Assist \u00b7 Symmetrical AWD X-MODE",
      destinationList: ["Mountain Gateway", "National Forest Route", "River Valley Highway", "Outer Beltway"],
    },
    {
      brand: "Ford",
      category: "Global Midsize Pickup",
      name: "Ford Ranger",
      icon: "\ud83d\udefb",
      model: "Ford Ranger XLT 2.0L Bi-Turbo 4x4 Double Cab",
      shortModel: "Ford Ranger",
      shortLabel: "\ud83d\udefb Ford Ranger",
      powertrain: "2.0L Bi-Turbo EcoBlue Diesel (207 hp, 500 Nm)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Global Tough Spec)`,
      driverMode: "Terrain Management System \u00b7 3.5-Ton Towing",
      destinationList: ["Industrial Depot", "Port Logistics Terminal", "Regional Freight Way", "Outlying Mining Highway"],
    },
    {
      brand: "Peugeot",
      category: "Global Chic Compact",
      name: "Peugeot 208",
      icon: "\ud83d\ude97",
      model: "Peugeot 208 Allure PureTech 100 EAT8",
      shortModel: "Peugeot 208",
      shortLabel: "\ud83d\ude97 Peugeot 208",
      powertrain: "1.2L PureTech 3-Cylinder Turbo (100 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (5.3 L/100km)`,
      driverMode: "Peugeot 3D i-Cockpit \u00b7 Active Safety Brake",
      destinationList: ["Fashion Avenue", "Historic Old Town", "Boutique Quarter", "Riverside Promenade"],
    },
    {
      brand: "Lexus",
      category: "Global Luxury Crossover",
      name: "Lexus RX",
      icon: "\ud83d\ude99",
      model: "Lexus RX 350h Luxury Self-Charging Hybrid AWD",
      shortModel: "Lexus RX 350h",
      shortLabel: "\ud83d\ude99 Lexus RX",
      powertrain: "2.5L 4-Cylinder Full Hybrid AWD (246 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (6.0 L/100km)`,
      driverMode: "Lexus Safety System+ 3.0 \u00b7 Mark Levinson Audio",
      destinationList: ["Country Club Drive", "Luxury Shopping Galleria", "Executive Airport Terminal", "Grand Waterfront Way"],
    },
  ],
  // ==========================================
  // EU_REGIONAL (20 Vehicles)
  // ==========================================
  EU_REGIONAL: [
    {
      brand: "Volkswagen",
      category: "European Benchmark",
      name: "VW Golf",
      icon: "\ud83d\ude97",
      model: "Volkswagen Golf 1.5 eTSI R-Line DSG",
      shortModel: "VW Golf",
      shortLabel: "\ud83d\ude97 VW Golf",
      powertrain: "1.5L eTSI Mild Hybrid (150 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (5.1 l/100km)`,
      driverMode: "Travel Assist \u00b7 IQ.LIGHT Matrix LED",
      destinationList: ["EU Boulevard", "Central Train Station", "Airport Expressway", "Historic Old Quarter"],
    },
    {
      brand: "Renault",
      category: "European Urban Hatchback",
      name: "Renault Clio",
      icon: "\ud83d\ude97",
      model: "Renault Clio E-Tech Full Hybrid 145",
      shortModel: "Renault Clio",
      shortLabel: "\ud83d\ude97 Renault Clio",
      powertrain: "1.6L 4-Cylinder E-Tech Hybrid (145 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (4.2 l/100km)`,
      driverMode: "Active Emergency Braking \u00b7 Easy Park Assist",
      destinationList: ["Grand Avenue", "River Promenade", "Shopping Mall Ring", "Inner Ringway"],
    },
    {
      brand: "Peugeot",
      category: "Modern European Compact",
      name: "Peugeot 208",
      icon: "\ud83d\ude97",
      model: "Peugeot 208 GT Hybrid 136 e-DCS6",
      shortModel: "Peugeot 208",
      shortLabel: "\ud83d\ude97 Peugeot 208",
      powertrain: "1.2L PureTech 48V Hybrid (136 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (4.6 l/100km)`,
      driverMode: "i-Cockpit 3D \u00b7 Lane Keeping Assist",
      destinationList: ["Historic Town Center", "Fashion Boulevard", "North Gate Station", "University Campus"],
    },
    {
      brand: "Dacia",
      category: "European Value Leader",
      name: "Dacia Sandero",
      icon: "\ud83d\ude97",
      model: "Dacia Sandero Stepway TCe 90",
      shortModel: "Dacia Sandero",
      shortLabel: "\ud83d\ude97 Dacia Sandero",
      powertrain: "1.0L Turbo 3-Cylinder (90 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (5.3 l/100km)`,
      driverMode: "Cruise Control with Speed Limiter \u00b7 Hill Start",
      destinationList: ["Market Square", "Industrial Zone", "Train Terminal", "Suburban Parkway"],
    },
    {
      brand: "Skoda",
      category: "European Family Estate",
      name: "Skoda Octavia",
      icon: "\ud83d\ude97",
      model: "Skoda Octavia Combi 2.0 TDI Ambition",
      shortModel: "Skoda Octavia",
      shortLabel: "\ud83d\ude97 Octavia Combi",
      powertrain: "2.0L TDI CleanDiesel (150 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (4.4 l/100km)`,
      driverMode: "Front Assist \u00b7 Adaptive Cruise Control",
      destinationList: ["Interstate Motorway", "Logistics Hub", "Central Station", "Business District"],
    },
    {
      brand: "Toyota",
      category: "European Hybrid Compact",
      name: "Toyota Yaris",
      icon: "\ud83d\ude97",
      model: "Toyota Yaris 1.5 Hybrid Dynamic Force",
      shortModel: "Toyota Yaris",
      shortLabel: "\ud83d\ude97 Toyota Yaris",
      powertrain: "1.5L 3-Cylinder Hybrid System (116 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Battery (3.9 l/100km)`,
      driverMode: "Toyota Safety Sense \u00b7 Road Sign Assist",
      destinationList: ["Old Town Lane", "City Center Plaza", "West Terminal", "Riverside Parkway"],
    },
    {
      brand: "Ford",
      category: "European Urban Crossover",
      name: "Ford Puma",
      icon: "\ud83d\ude97",
      model: "Ford Puma ST-Line 1.0 EcoBoost mHEV",
      shortModel: "Ford Puma",
      shortLabel: "\ud83d\ude97 Ford Puma",
      powertrain: "1.0L EcoBoost Mild Hybrid (125 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (5.4 l/100km)`,
      driverMode: "Ford Co-Pilot360 \u00b7 MegaBox Storage",
      destinationList: ["Ring Road Interchange", "Sports Complex", "Suburban Plaza", "North Bypass"],
    },
    {
      brand: "Fiat",
      category: "European City Icon",
      name: "Fiat 500",
      icon: "\ud83d\ude97",
      model: "Fiat 500 Dolcevita 1.0 GSE Hybrid",
      shortModel: "Fiat 500",
      shortLabel: "\ud83d\ude97 Fiat 500",
      powertrain: "1.0L FireFly 3-Cylinder Mild Hybrid (70 hp)",
      paintColor: "#0ea5e9",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (4.6 l/100km)`,
      driverMode: "City Steering Mode \u00b7 Start&Stop",
      destinationList: ["Duomo Square", "Cobblestone Lane", "Caf\u00e9 District", "Boutique Quarter"],
    },
    {
      brand: "Volkswagen",
      category: "European Family SUV",
      name: "VW Tiguan",
      icon: "\ud83d\ude99",
      model: "Volkswagen Tiguan 2.0 TDI 4MOTION",
      shortModel: "VW Tiguan",
      shortLabel: "\ud83d\ude99 VW Tiguan",
      powertrain: "2.0L TDI Turbodiesel AWD (193 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (5.9 l/100km)`,
      driverMode: "IQ.DRIVE Travel Assist \u00b7 Lane Assist",
      destinationList: ["Motorway Junction", "Airport Road", "Suburban Park", "Business Center"],
    },
    {
      brand: "CUPRA",
      category: "European Sport Crossover",
      name: "Cupra Formentor",
      icon: "\ud83d\ude99",
      model: "CUPRA Formentor VZ 2.0 TSI DSG 4Drive",
      shortModel: "Cupra Formentor",
      shortLabel: "\ud83d\ude99 Cupra Formentor",
      powertrain: "2.0L TSI Turbocharged 4-Cylinder (310 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (8.5 l/100km)`,
      driverMode: "CUPRA Drive Profile \u00b7 Brembo Brakes",
      destinationList: ["Olympic Stadium", "Financial Center", "Coastal Highway", "Ring Expressway"],
    },
    {
      brand: "Kia",
      category: "European Crossover Favorite",
      name: "Kia Sportage",
      icon: "\ud83d\ude99",
      model: "Kia Sportage 1.6 T-GDi MHEV GT-Line",
      shortModel: "Kia Sportage",
      shortLabel: "\ud83d\ude99 Kia Sportage",
      powertrain: "1.6L T-GDi Mild Hybrid (150 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (6.5 l/100km)`,
      driverMode: "Forward Collision Avoidance \u00b7 Highway Driving Assist",
      destinationList: ["Central Interchange", "Suburban Hub", "Tech Park", "East Parkway"],
    },
    {
      brand: "BMW",
      category: "European Executive Saloon",
      name: "BMW 3 Series",
      icon: "\ud83d\ude97",
      model: "BMW 320d M Sport Steptronic",
      shortModel: "BMW 320d",
      shortLabel: "\ud83d\ude97 BMW 3 Series",
      powertrain: "2.0L TwinPower Turbo Diesel (190 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (4.9 l/100km)`,
      driverMode: "BMW Operating System 8 \u00b7 Driving Assistant",
      destinationList: ["Banking Center", "Diplomatic Quarter", "Airport VIP Loop", "Freeway Corridor"],
    },
    {
      brand: "Audi",
      category: "European Premium Compact",
      name: "Audi A3",
      icon: "\ud83d\ude97",
      model: "Audi A3 Sportback 35 TDI S line",
      shortModel: "Audi A3",
      shortLabel: "\ud83d\ude97 Audi A3",
      powertrain: "2.0L TDI 4-Cylinder Turbodiesel (150 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (4.7 l/100km)`,
      driverMode: "Audi Pre Sense \u00b7 Virtual Cockpit",
      destinationList: ["Financial Boulevard", "Opera Plaza", "Harbor Promenade", "North Highway"],
    },
    {
      brand: "Mercedes-Benz",
      category: "European Compact Luxury",
      name: "Mercedes A-Class",
      icon: "\ud83d\ude97",
      model: "Mercedes-Benz A 200 AMG Line",
      shortModel: "Mercedes A 200",
      shortLabel: "\ud83d\ude97 Mercedes A-Class",
      powertrain: "1.3L 4-Cylinder Turbo Petrol (163 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (5.8 l/100km)`,
      driverMode: "MBUX Voice Control \u00b7 Active Brake Assist",
      destinationList: ["Luxury Quarter", "Central Plaza", "Grand Hotel Avenue", "Outer Ringway"],
    },
    {
      brand: "Volvo",
      category: "European Premium SUV",
      name: "Volvo XC40",
      icon: "\ud83d\ude99",
      model: "Volvo XC40 B4 AWD Mild Hybrid",
      shortModel: "Volvo XC40",
      shortLabel: "\ud83d\ude99 Volvo XC40",
      powertrain: "2.0L Turbo 4-Cylinder AWD (197 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (7.1 l/100km)`,
      driverMode: "Google Built-In \u00b7 City Safety System",
      destinationList: ["Convention Center", "Waterfront Boulevard", "Lake Highway", "Suburban Center"],
    },
    {
      brand: "Nissan",
      category: "European Pioneer Crossover",
      name: "Nissan Qashqai",
      icon: "\ud83d\ude99",
      model: "Nissan Qashqai e-POWER Tekna",
      shortModel: "Nissan Qashqai",
      shortLabel: "\ud83d\ude99 Nissan Qashqai",
      powertrain: "1.5L e-POWER Series Hybrid (190 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid System (5.3 l/100km)`,
      driverMode: "ProPILOT Assist \u00b7 Around View Monitor",
      destinationList: ["South Transit Hub", "Shopping Mall Ring", "Family Park", "City Ringway"],
    },
    {
      brand: "Tesla",
      category: "European Electric Leader",
      name: "Tesla Model Y",
      icon: "\u26a1",
      model: "Tesla Model Y Long Range AWD Berlin Gigafactory",
      shortModel: "Model Y Berlin",
      shortLabel: "\u26a1 Model Y",
      powertrain: "Dual-Motor Electric AWD (514 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 78.1 kWh Pack (533 km WLTP)`,
      driverMode: "Autopilot \u00b7 Giga Berlin Structural Battery",
      destinationList: ["Gigafactory Loop", "Supercharger Hub", "Tech Campus", "Express Motorway"],
    },
    {
      brand: "Hyundai",
      category: "European Family SUV",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson 1.6 T-GDi Hybrid",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Hyundai Tucson",
      powertrain: "1.6L Smartstream Turbo Hybrid (230 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Hybrid Tank (5.6 l/100km)`,
      driverMode: "SmartSense Safety \u00b7 Blind Spot Detection",
      destinationList: ["Valley Parkway", "Metro Plaza", "East Gate", "University Hub"],
    },
    {
      brand: "Opel",
      category: "European Compact",
      name: "Opel Corsa",
      icon: "\ud83d\ude97",
      model: "Opel Corsa 1.2 Turbo GS Line",
      shortModel: "Opel Corsa",
      shortLabel: "\ud83d\ude97 Opel Corsa",
      powertrain: "1.2L Turbo PureTech 3-Cylinder (100 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (5.4 l/100km)`,
      driverMode: "IntelliLux LED Matrix \u00b7 Lane Assist",
      destinationList: ["Central Market", "Old Bridge", "Suburban Way", "North Ring"],
    },
    {
      brand: "Citro\u00ebn",
      category: "European Comfort Hatch",
      name: "Citro\u00ebn C3",
      icon: "\ud83d\ude97",
      model: "Citro\u00ebn C3 PureTech 100 Max",
      shortModel: "Citro\u00ebn C3",
      shortLabel: "\ud83d\ude97 Citro\u00ebn C3",
      powertrain: "1.2L PureTech 3-Cylinder Turbo (100 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (5.4 l/100km)`,
      driverMode: "Advanced Comfort Suspension \u00b7 Cruise Control",
      destinationList: ["Square Promenade", "Cobbled Quarter", "Suburban Rail Link", "City Bypass"],
    },
  ],
  // ==========================================
  // AS_REGIONAL (20 Vehicles)
  // ==========================================
  AS_REGIONAL: [
    {
      brand: "Toyota",
      category: "Pan-Asian Benchmark Sedan",
      name: "Toyota Corolla Altis",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla Altis 1.8 Dual VVT-i",
      shortModel: "Corolla Altis",
      shortLabel: "\ud83d\ude97 Corolla Altis",
      powertrain: "1.8L 2ZR-FE DOHC Dual VVT-i (138 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.5 km/l)`,
      driverMode: "Toyota Safety Sense \u00b7 Vehicle Stability Control",
      destinationList: ["City Business Center", "International Airport", "Railway Station", "Suburban Commercial Loop"],
    },
    {
      brand: "Honda",
      category: "Pan-Asian Benchmark Sedan",
      name: "Honda Civic",
      icon: "\ud83d\ude97",
      model: "Honda Civic 1.5 VTEC Turbo RS",
      shortModel: "Honda Civic RS",
      shortLabel: "\ud83d\ude97 Honda Civic",
      powertrain: "1.5L DOHC VTEC Turbo (178 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.2 km/l)`,
      driverMode: "Honda SENSING \u00b7 LaneWatch Camera",
      destinationList: ["Main Boulevard", "Port Expressway", "Tech Center", "Grand Ringway"],
    },
    {
      brand: "Toyota",
      category: "Pan-Asian Indestructible Ute",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux 2.4 D-4D Double Cab 4x4",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Toyota Hilux",
      powertrain: "2.4L 2GD-FTV Turbodiesel (150 hp, 400 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Built for rugged Asian roads)`,
      driverMode: "Rear Differential Lock \u00b7 Heavy Duty Leaf Springs",
      destinationList: ["Agricultural Trading Post", "Port Container Terminal", "Regional Highway", "Industrial Complex"],
    },
    {
      brand: "Suzuki",
      category: "Pan-Asian Compact Hatch",
      name: "Suzuki Swift",
      icon: "\ud83d\ude97",
      model: "Suzuki Swift 1.2 Dualjet AGS",
      shortModel: "Suzuki Swift",
      shortLabel: "\ud83d\ude97 Suzuki Swift",
      powertrain: "1.2L K12M 4-Cylinder Dualjet (83 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (23.5 km/l Asian City Saver)`,
      driverMode: "Heartect Platform \u00b7 Dual Airbags & ABS",
      destinationList: ["Old Market Quarter", "High Street", "Transit Station", "Central Mall"],
    },
    {
      brand: "Hyundai",
      category: "Pan-Asian Executive Sedan",
      name: "Hyundai Elantra",
      icon: "\ud83d\ude97",
      model: "Hyundai Elantra 1.6L Smartstream MPI",
      shortModel: "Hyundai Elantra",
      shortLabel: "\ud83d\ude97 Hyundai Elantra",
      powertrain: "1.6L Smartstream 4-Cylinder (123 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15.5 km/l)`,
      driverMode: "Hyundai SmartSense \u00b7 Forward Collision Avoidance",
      destinationList: ["Financial District", "Embassy Lane", "Grand Boulevard", "Airport Expressway"],
    },
    {
      brand: "BYD",
      category: "Pan-Asian Electric Dolphin",
      name: "BYD Dolphin",
      icon: "\u26a1",
      model: "BYD Dolphin EV Blade 44.9 kWh",
      shortModel: "BYD Dolphin",
      shortLabel: "\u26a1 BYD Dolphin",
      powertrain: "Single Permanent Magnet Motor (95 hp)",
      paintColor: "#06b6d4",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 44.9 kWh Blade Battery (410 km NEDC)`,
      driverMode: "DiPilot Driver Assist \u00b7 VTOL Discharge",
      destinationList: ["Eco Tech Hub", "City Center Charging Station", "Convention Grounds", "Ring Parkway"],
    },
    {
      brand: "Wuling",
      category: "Urban Micro EV",
      name: "Wuling Hongguang Mini",
      icon: "\u26a1",
      model: "Wuling Hongguang Mini EV Macaron 27 hp",
      shortModel: "Wuling Mini EV",
      shortLabel: "\u26a1 Wuling Mini",
      powertrain: "Rear Electric Motor (27 hp)",
      paintColor: "#ec4899",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 13.9 kWh LFP Battery (170 km range)`,
      driverMode: "Super Compact City Weaving \u00b7 Easy Parking",
      destinationList: ["Local Community Market", "Subway Station Entrance", "Shopping Alley", "High-Density Residential"],
    },
    {
      brand: "Toyota",
      category: "Pan-Asian Subcompact Sedan",
      name: "Toyota Vios",
      icon: "\ud83d\ude97",
      model: "Toyota Vios 1.5 Dual VVT-i CVT",
      shortModel: "Toyota Vios",
      shortLabel: "\ud83d\ude97 Toyota Vios",
      powertrain: "1.5L 2NR-VE 4-Cylinder (106 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (21 km/l)`,
      driverMode: "7 SRS Airbags \u00b7 Vehicle Stability Control",
      destinationList: ["Central Plaza", "Commercial Road", "North Suburb", "City Ring Loop"],
    },
    {
      brand: "Isuzu",
      category: "Pan-Asian Diesel Ute",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max 1.9 Ddi BluePower 4x4",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb Isuzu D-Max",
      powertrain: "1.9L RZ4E-TC Ddi BluePower Diesel (150 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Heavy Duty Asian Hauler)`,
      driverMode: "Terrain Command 4WD \u00b7 High Payload Bed",
      destinationList: ["Provincial Highway", "Industrial Estate", "Wholesale Market", "Cross-Country Route"],
    },
    {
      brand: "Kia",
      category: "Pan-Asian Compact SUV",
      name: "Kia Seltos",
      icon: "\ud83d\ude99",
      model: "Kia Seltos 1.5 MPI IVT EX",
      shortModel: "Kia Seltos",
      shortLabel: "\ud83d\ude99 Kia Seltos",
      powertrain: "1.5L Smartstream MPI 4-Cylinder (115 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.8 km/l)`,
      driverMode: "Drive Mode Select \u00b7 Blind Spot Collision Warning",
      destinationList: ["Tech Park Boulevard", "North Gate Mall", "City Interchange", "Outer Ringway"],
    },
    {
      brand: "Nissan",
      category: "Pan-Asian Reliable Sedan",
      name: "Nissan Sunny",
      icon: "\ud83d\ude97",
      model: "Nissan Sunny 1.6L SV Xtronic CVT",
      shortModel: "Nissan Sunny",
      shortLabel: "\ud83d\ude97 Nissan Sunny",
      powertrain: "1.6L HR16DE 4-Cylinder (118 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (19.3 km/l)`,
      driverMode: "Nissan Intelligent Mobility \u00b7 Rear Parking Sensors",
      destinationList: ["Residential Quarter", "Hospital Road", "Central Market", "Express Corridor"],
    },
    {
      brand: "Mitsubishi",
      category: "Pan-Asian Family 7-Seater",
      name: "Mitsubishi Xpander",
      icon: "\ud83d\ude90",
      model: "Mitsubishi Xpander 1.5L MIVEC Cross 7-Seat",
      shortModel: "Mitsu Xpander",
      shortLabel: "\ud83d\ude90 Mitsu Xpander",
      powertrain: "1.5L 4A91 MIVEC 4-Cylinder (105 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (205mm High Ground Clearance)`,
      driverMode: "Active Stability Control \u00b7 Hill Start Assist",
      destinationList: ["Family Entertainment Center", "Ferry Terminal", "Interstate Bus Station", "Suburban Plaza"],
    },
    {
      brand: "Toyota",
      category: "Pan-Asian Executive Luxury",
      name: "Toyota Camry",
      icon: "\ud83d\ude97",
      model: "Toyota Camry 2.5 Dynamic Force Luxury",
      shortModel: "Toyota Camry",
      shortLabel: "\ud83d\ude97 Toyota Camry",
      powertrain: "2.5L Dynamic Force 4-Cylinder (209 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.5 km/l)`,
      driverMode: "Toyota Safety Sense 2.5 \u00b7 Executive Rear Reclining Seats",
      destinationList: ["Government House", "Diplomatic Enclave", "Five-Star Hotel Entrance", "Airport VIP Lane"],
    },
    {
      brand: "Honda",
      category: "Pan-Asian City Sedan",
      name: "Honda City",
      icon: "\ud83d\ude97",
      model: "Honda City 1.5 i-VTEC V-Grade CVT",
      shortModel: "Honda City",
      shortLabel: "\ud83d\ude97 Honda City",
      powertrain: "1.5L DOHC i-VTEC 4-Cylinder (121 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18.4 km/l)`,
      driverMode: "Honda Sensing Suite \u00b7 Walk Away Auto Lock",
      destinationList: ["Commercial Center", "Outer Ring Road", "University Gateway", "East Terminal"],
    },
    {
      brand: "Mazda",
      category: "Pan-Asian Premium Compact",
      name: "Mazda 3",
      icon: "\ud83d\ude97",
      model: "Mazda 3 Sedan 2.0 Skyactiv-G SP",
      shortModel: "Mazda 3",
      shortLabel: "\ud83d\ude97 Mazda 3",
      powertrain: "2.0L Skyactiv-G Direct Injection (153 hp)",
      paintColor: "#991b1b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.4 km/l)`,
      driverMode: "i-Activesense Safety \u00b7 G-Vectoring Control Plus",
      destinationList: ["Harbor Boulevard", "Arts Center", "Riverside Parkway", "City Expressway"],
    },
    {
      brand: "Geely",
      category: "Pan-Asian Compact Crossover",
      name: "Geely Coolray",
      icon: "\ud83d\ude99",
      model: "Geely Coolray 1.5T Sport DCT",
      shortModel: "Geely Coolray",
      shortLabel: "\ud83d\ude99 Geely Coolray",
      powertrain: "1.5L Turbo 3-Cylinder (177 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15.5 km/l)`,
      driverMode: "Level 2 Autonomous Driving \u00b7 Auto Parking",
      destinationList: ["Youth Shopping Hub", "Metro Center", "Tech Campus", "Suburban Way"],
    },
    {
      brand: "Changan",
      category: "Pan-Asian Urban Crossover",
      name: "Changan CS35",
      icon: "\ud83d\ude99",
      model: "Changan CS35 Plus 1.4T BlueCore",
      shortModel: "Changan CS35",
      shortLabel: "\ud83d\ude99 Changan CS35",
      powertrain: "1.4L Turbocharged BlueCore (158 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15.8 km/l)`,
      driverMode: "Adaptive Cruise Control \u00b7 Panoramic Sunroof",
      destinationList: ["Transit Station", "Central Market", "Suburban Plaza", "North Bypass"],
    },
    {
      brand: "Hyundai",
      category: "Pan-Asian Bestselling Crossover",
      name: "Hyundai Creta",
      icon: "\ud83d\ude99",
      model: "Hyundai Creta 1.5 Smartstream Prime",
      shortModel: "Hyundai Creta",
      shortLabel: "\ud83d\ude99 Hyundai Creta",
      powertrain: "1.5L Smartstream 4-Cylinder (115 hp)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17 km/l)`,
      driverMode: "Hyundai SmartSense \u00b7 Bose Premium Sound",
      destinationList: ["City Center Hub", "Family Park", "South Terminal", "Airport Road"],
    },
    {
      brand: "Toyota",
      category: "Pan-Asian 7-Seater 4x4",
      name: "Toyota Fortuner",
      icon: "\ud83d\ude99",
      model: "Toyota Fortuner 2.8 D-4D 4x4 Legender",
      shortModel: "Toyota Fortuner",
      shortLabel: "\ud83d\ude99 Fortuner 4x4",
      powertrain: "2.8L 1GD-FTV Turbodiesel (201 hp, 500 Nm)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Heavy Asian 4WD)`,
      driverMode: "Part-Time 4WD with Rear Differential Lock",
      destinationList: ["Provincial Gateway", "Mountain Pass Route", "VIP Escort Way", "High Speed Tollway"],
    },
    {
      brand: "BYD",
      category: "Pan-Asian Electric Sports Sedan",
      name: "BYD Seal",
      icon: "\u26a1",
      model: "BYD Seal Design 82.5 kWh RWD",
      shortModel: "BYD Seal EV",
      shortLabel: "\u26a1 BYD Seal",
      powertrain: "Rear Permanent Magnet Motor (313 hp)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% 82.5 kWh Blade Battery (570 km WLTP)`,
      driverMode: "CTB Cell-to-Body Technology \u00b7 DiLink 4.0",
      destinationList: ["Innovation Park", "Financial Center", "Airport Express", "Coastal Boulevard"],
    },
  ],
  // ==========================================
  // LATAM_REGIONAL (20 Vehicles)
  // ==========================================
  LATAM_REGIONAL: [
    {
      brand: "Toyota",
      category: "Latin America's #1 Pickup",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux SRV 2.8 TDI 4x4 Doble Cabina",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Toyota Hilux",
      powertrain: "2.8L Turbodi\u00e9sel Intercooler (204 CV, 500 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Diésel (80 Litros de uso pesado)`,
      driverMode: "Bloqueo de diferencial trasero \u00b7 Tracci\u00f3n 4x4 reductora",
      destinationList: ["Centro Urbano", "Terminal Portuaria", "Ruta Nacional", "Zona Agroindustrial"],
    },
    {
      brand: "Fiat",
      category: "Picape Mais Vendida da Am\u00e9rica Latina",
      name: "Fiat Strada",
      icon: "\ud83d\udefb",
      model: "Fiat Strada Volcano 1.3 Firefly Flex Cabine Dupla",
      shortModel: "Fiat Strada",
      shortLabel: "\ud83d\udefb Fiat Strada",
      powertrain: "1.3L Firefly 8V Flex (107 CV)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Flex (Consumo equilibrado)`,
      driverMode: "Sistema TC+ Locker de tra\u00e7\u00e3o avan\u00e7ada",
      destinationList: ["Mercado Central", "Avenida Comercial", "Distrito Industrial", "Rodovia Regional"],
    },
    {
      brand: "Chevrolet",
      category: "Hatch Bestseller Regional",
      name: "Chevrolet Onix",
      icon: "\ud83d\ude97",
      model: "Chevrolet Onix Premier 1.0 Turbo 6-Vel",
      shortModel: "Chevy Onix",
      shortLabel: "\ud83d\ude97 Chevy Onix",
      powertrain: "1.0L Turbo 3 Cilindros Ecotec (116 CV)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina/Flex (17 km/l)`,
      driverMode: "6 Airbags de s\u00e9rie \u00b7 Wi-Fi Nativo OnStar",
      destinationList: ["Plaza de la Independencia", "Paseo Comercial", "Avenida Principal", "Acceso Autopista"],
    },
    {
      brand: "Volkswagen",
      category: "Hatch Robusto Regional",
      name: "VW Polo",
      icon: "\ud83d\ude97",
      model: "Volkswagen Polo Track 1.0 Flex Robusto",
      shortModel: "VW Polo Track",
      shortLabel: "\ud83d\ude97 Polo Track",
      powertrain: "1.0L MPI 3 Cilindros Flex (84 CV)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Flex (Alta durabilidade em estradas latinas)`,
      driverMode: "Suspens\u00e3o refor\u00e7ada e controle de estabilidade ESC",
      destinationList: ["Esta\u00e7\u00e3o Central", "Terminal Rodovi\u00e1rio", "Bairro Universit\u00e1rio", "Anel Vi\u00e1rio"],
    },
    {
      brand: "Renault",
      category: "SUV Conquistadora de Trochas",
      name: "Renault Duster",
      icon: "\ud83d\ude99",
      model: "Renault Duster 1.3 Turbo 4x4 Iconic",
      shortModel: "Renault Duster",
      shortLabel: "\ud83d\ude99 Renault Duster",
      powertrain: "1.3L TCe Turbo 4x4 (154 CV, 270 Nm)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Combustível (Alta altura livre ao solo)`,
      driverMode: "Tra\u00e7\u00e3o 4x4 com seletor All-Mode e monitor 4x4",
      destinationList: ["Camino Real", "Cruce Fronterizo", "Zona Cordillerana", "Avenida Central"],
    },
    {
      brand: "Fiat",
      category: "Sed\u00e1n Bestseller Mercosur",
      name: "Fiat Cronos",
      icon: "\ud83d\ude97",
      model: "Fiat Cronos Precision 1.3 GSE 16V",
      shortModel: "Fiat Cronos",
      shortLabel: "\ud83d\ude97 Fiat Cronos",
      powertrain: "1.3L Firefly 8V 4 Cilindros (99 CV)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Nafta/Flex (15.5 km/l)`,
      driverMode: "Ba\u00fal generoso de 525L y pantalla t\u00e1ctil Uconnect",
      destinationList: ["Plaza de Mayo", "Avenida 9 de Julio", "Centro Financiero", "Ruta de Circunvalaci\u00f3n"],
    },
    {
      brand: "Hyundai",
      category: "Hatch Compacto Latino",
      name: "Hyundai HB20",
      icon: "\ud83d\ude97",
      model: "Hyundai HB20 Platinum 1.0 TGDI Turbo",
      shortModel: "Hyundai HB20",
      shortLabel: "\ud83d\ude97 Hyundai HB20",
      powertrain: "1.0L Kappa Turbo TGDI Flex (120 CV)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Flex (14 km/l)`,
      driverMode: "Frenagem aut\u00f4noma de emerg\u00eancia e 6 airbags",
      destinationList: ["Avenida Paulista", "Centro Empresarial", "Terminal Sul", "Via Expressa"],
    },
    {
      brand: "Nissan",
      category: "Sed\u00e1n Econ\u00f3mico de Entrada",
      name: "Nissan Versa",
      icon: "\ud83d\ude97",
      model: "Nissan Versa Exclusive 1.6L DOHC 16V",
      shortModel: "Nissan Versa",
      shortLabel: "\ud83d\ude97 Nissan Versa",
      powertrain: "1.6L 4 Cilindros DOHC (118 CV)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina (18.5 km/l)`,
      driverMode: "Frenado inteligente de emergencia \u00b7 Monitor 360",
      destinationList: ["Paseo de la Reforma", "Boulevard Norte", "Centro C\u00edvico", "Autopista Urbana"],
    },
    {
      brand: "Peugeot",
      category: "Hatchback con Estilo",
      name: "Peugeot 208",
      icon: "\ud83d\ude97",
      model: "Peugeot 208 Style 1.0 Turbo 200 CVT",
      shortModel: "Peugeot 208",
      shortLabel: "\ud83d\ude97 Peugeot 208",
      powertrain: "1.0L Turbo 200 Flex Stellantis (130 CV)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Flex/Nafta (15 km/l)`,
      driverMode: "i-Cockpit 3D con volante deportivo y techo panor\u00e1mico",
      destinationList: ["Boulevard Cultural", "Plaza Central", "Avenida Costanera", "Ruta Radial"],
    },
    {
      brand: "Ford",
      category: "Pickup Mediana Regional",
      name: "Ford Ranger",
      icon: "\ud83d\udefb",
      model: "Ford Ranger Limited 3.0 V6 4WD",
      shortModel: "Ford Ranger",
      shortLabel: "\ud83d\udefb Ford Ranger",
      powertrain: "3.0L V6 EcoBlue Turbodi\u00e9sel (250 CV, 600 Nm)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Diésel (Capacidad de arrastre de 3.5T)`,
      driverMode: "Caja autom\u00e1tica de 10 velocidades y tracci\u00f3n 4WD inteligente",
      destinationList: ["Ruta Panamericana", "Puerto Fluvial", "Parque Industrial", "Corredor Bioce\u00e1nico"],
    },
    {
      brand: "Volkswagen",
      category: "Pickup V6 Robusta",
      name: "VW Amarok",
      icon: "\ud83d\udefb",
      model: "Volkswagen Amarok Highline 3.0 V6 4Motion",
      shortModel: "VW Amarok V6",
      shortLabel: "\ud83d\udefb Amarok V6",
      powertrain: "3.0L V6 TDI Turbodi\u00e9sel (258 CV)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Diésel (Tracción integral 4Motion permanente)`,
      driverMode: "Caja autom\u00e1tica ZF de 8 velocidades \u00b7 Modo Off-Road",
      destinationList: ["Ruta del Mercosur", "Terminal de Cargas", "Avenida de Acceso", "Polo Log\u00edstico"],
    },
    {
      brand: "Toyota",
      category: "SUV Familiar Regional",
      name: "Toyota Corolla Cross",
      icon: "\ud83d\ude99",
      model: "Toyota Corolla Cross XEI 2.0 Dual VVT-iE",
      shortModel: "Corolla Cross",
      shortLabel: "\ud83d\ude99 Corolla Cross",
      powertrain: "2.0L Dynamic Force Dual VVT-iE (170 CV)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Nafta (14.5 km/l)`,
      driverMode: "Toyota Safety Sense con control crucero adaptativo",
      destinationList: ["Avenida Los Conquistadores", "Mall Costanera", "Distrito Ejecutivo", "Bypass Urbano"],
    },
    {
      brand: "Fiat",
      category: "Subcompacto Accesible",
      name: "Fiat Mobi",
      icon: "\ud83d\ude97",
      model: "Fiat Mobi Trekking 1.0 Fire EVO",
      shortModel: "Fiat Mobi",
      shortLabel: "\ud83d\ude97 Fiat Mobi",
      powertrain: "1.0L Fire 8V Flex (74 CV)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Flex (Alta economía de combustible)`,
      driverMode: "Suspensi\u00f3n elevada y dimensiones reducidas para tr\u00e1fico pesado",
      destinationList: ["Barrio Hist\u00f3rico", "Plaza de Mercado", "Terminal de Autobuses", "Avenida Santander"],
    },
    {
      brand: "Chevrolet",
      category: "SUV Compacto Turbo",
      name: "Chevrolet Tracker",
      icon: "\ud83d\ude99",
      model: "Chevrolet Tracker Premier 1.2 Turbo",
      shortModel: "Chevy Tracker",
      shortLabel: "\ud83d\ude99 Chevy Tracker",
      powertrain: "1.2L Turbo 3 Cilindros Ecotec (132 CV)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina/Flex (15.5 km/l)`,
      driverMode: "Alerta de colisi\u00f3n frontal con frenado aut\u00f3nomo",
      destinationList: ["Paseo Las Palmas", "Centro Comercial", "Avenida El Dorado", "Circuito Perif\u00e9rico"],
    },
    {
      brand: "Nissan",
      category: "Pickup Utilitaria Doble Cabina",
      name: "Nissan Frontier",
      icon: "\ud83d\udefb",
      model: "Nissan Frontier PRO-4X Bi-Turbo Di\u00e9sel 4x4",
      shortModel: "Nissan Frontier",
      shortLabel: "\ud83d\udefb Frontier 4x4",
      powertrain: "2.3L Bi-Turbo Di\u00e9sel Intercooler (190 CV)",
      paintColor: "#047857",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Diésel para faenas agrícolas y mineras`,
      driverMode: "Suspensi\u00f3n trasera multilink con eje r\u00edgido",
      destinationList: ["Ruta Minera", "Terminal de Granos", "Parque Agropecuario", "Carretera Austral"],
    },
    {
      brand: "Suzuki",
      category: "Hatchback H\u00edbrido Liviano",
      name: "Suzuki Swift",
      icon: "\ud83d\ude97",
      model: "Suzuki Swift Boostergreen 1.2 H\u00edbrido",
      shortModel: "Suzuki Swift",
      shortLabel: "\ud83d\ude97 Suzuki Swift",
      powertrain: "1.2L Dualjet SHVS H\u00edbrido Ligero (82 CV)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Nafta Híbrido (22 km/l)`,
      driverMode: "Gran eficiencia en congesti\u00f3n urbana latinoamericana",
      destinationList: ["Avenida Insurgentes", "Paseo del Valle", "Zona Universitaria", "Ruta Expresa"],
    },
    {
      brand: "Renault",
      category: "SUV de los Compactos",
      name: "Renault Kwid",
      icon: "\ud83d\ude97",
      model: "Renault Kwid Outsider 1.0 SCe",
      shortModel: "Renault Kwid",
      shortLabel: "\ud83d\ude97 Renault Kwid",
      powertrain: "1.0L SCe 3 Cilindros 12V (66 CV)",
      paintColor: "#d97706",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina Ultraeconómico (20 km/l)`,
      driverMode: "Despeje al suelo de 18.5 cm y 4 airbags de serie",
      destinationList: ["Calle Real", "Plaza de Armas", "Sector Comercial", "Paso a Desnivel"],
    },
    {
      brand: "Jeep",
      category: "SUV Compacto Conquistador",
      name: "Jeep Renegade",
      icon: "\ud83d\ude99",
      model: "Jeep Renegade Longitude 1.3 Turbo T270",
      shortModel: "Jeep Renegade",
      shortLabel: "\ud83d\ude99 Jeep Renegade",
      powertrain: "1.3L T270 Turbo 16V GSE (175 CV)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Nafta/Flex (13.5 km/l)`,
      driverMode: "Selec-Terrain con asistente para el arranque en pendiente",
      destinationList: ["Avenida Las Am\u00e9ricas", "Bulevar del R\u00edo", "Zona Rosa", "Ruta de Acceso"],
    },
    {
      brand: "Toyota",
      category: "Hatch / Sed\u00e1n Confiable",
      name: "Toyota Yaris",
      icon: "\ud83d\ude97",
      model: "Toyota Yaris XLS 1.5 Dual VVT-i CVT",
      shortModel: "Toyota Yaris",
      shortLabel: "\ud83d\ude97 Toyota Yaris",
      powertrain: "1.5L 2NR-FE 16V Dual VVT-i (107 CV)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina (16 km/l)`,
      driverMode: "7 Airbags y control de estabilidad VSC",
      destinationList: ["Plaza San Mart\u00edn", "Avenida Bolivariana", "Polo M\u00e9dico", "Autopista Central"],
    },
    {
      brand: "Hyundai",
      category: "SUV Confortable",
      name: "Hyundai Creta",
      icon: "\ud83d\ude99",
      model: "Hyundai Creta Limited 1.5 Smartstream",
      shortModel: "Hyundai Creta",
      shortLabel: "\ud83d\ude99 Hyundai Creta",
      powertrain: "1.5L MPI 4 Cilindros Atkinson (113 CV)",
      paintColor: "#7c3aed",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Tanque Gasolina (16.8 km/l)`,
      driverMode: "Hyundai SmartSense con asistente de mantenimiento de carril",
      destinationList: ["Avenida Libertador", "Zona Financiera", "Terminal Norte", "Autov\u00eda del Este"],
    },
  ],
  // ==========================================
  // AFRICA_REGIONAL (20 Vehicles)
  // ==========================================
  AFRICA_REGIONAL: [
    {
      brand: "Toyota",
      category: "Indisputable African Workhorse",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux 2.4 D-4D 4x4 Double Cab Safari Spec",
      shortModel: "Toyota Hilux",
      shortLabel: "\ud83d\udefb Toyota Hilux",
      powertrain: "2.4L D-4D Turbo Diesel 4x4 (148 hp, 400 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Built for African bush roads)`,
      driverMode: "Rear Differential Lock \u00b7 Snorkel \u00b7 Bull Bar",
      destinationList: ["Central Business District", "Interstate Border Post", "Mining Concession Road", "Trans-African Highway"],
    },
    {
      brand: "Isuzu",
      category: "Heavy Duty African Bakkie",
      name: "Isuzu D-Max",
      icon: "\ud83d\udefb",
      model: "Isuzu D-Max 2.5 Turbo Diesel 4x4 Heavy Duty",
      shortModel: "Isuzu D-Max",
      shortLabel: "\ud83d\udefb Isuzu D-Max",
      powertrain: "2.5L 4-Cylinder Turbo Diesel Intercooler (136 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (High Reliability for Rural Transit)`,
      driverMode: "Heavy Duty Suspension for Unpaved Corridors",
      destinationList: ["Provincial Gateway", "Agricultural Market Hub", "Regional Haulage Yard", "Northern Trunk Road"],
    },
    {
      brand: "Toyota",
      category: "Dignitary and NGO Cruiser",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser Prado TX 2.8 D-4D 4x4",
      shortModel: "Toyota Prado",
      shortLabel: "\ud83d\ude99 Toyota Prado",
      powertrain: "2.8L 1GD-FTV Turbodiesel 4x4 (201 hp, 500 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel Tanks (150 L Remote Range)`,
      driverMode: "Full-Time 4WD with Kinetic Dynamic Suspension",
      destinationList: ["Diplomatic Enclave", "UN Agency Headquarters", "State House Avenue", "Airport VIP Concourse"],
    },
    {
      brand: "Toyota",
      category: "King of African City Roads",
      name: "Toyota Corolla",
      icon: "\ud83d\ude97",
      model: "Toyota Corolla 1.6L Dual VVT-i Tropical Spec",
      shortModel: "Toyota Corolla",
      shortLabel: "\ud83d\ude97 Toyota Corolla",
      powertrain: "1.6L 1ZR-FE 4-Cylinder Dual VVT-i (120 hp)",
      paintColor: "#2563eb",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Reinforced for African Fuel Conditions)`,
      driverMode: "Heavy-Duty Tropicalized Radiator and Air Conditioner",
      destinationList: ["National Bank Square", "Commercial Avenue", "Central Post Office", "University Junction"],
    },
    {
      brand: "Ford",
      category: "Modern Heavy Bakkie",
      name: "Ford Ranger",
      icon: "\ud83d\udefb",
      model: "Ford Ranger 2.2 TDCi XL 4x4 Double Cab",
      shortModel: "Ford Ranger",
      shortLabel: "\ud83d\udefb Ford Ranger",
      powertrain: "2.2L Duratorq TDCi 4-Cylinder (158 hp, 385 Nm)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (3.5T Towing Capacity)`,
      driverMode: "Electronic Shift-On-The-Fly 4WD System",
      destinationList: ["Industrial Free Zone", "Harbor Container Terminal", "Mining Base Camp", "Cross-Country Corridor"],
    },
    {
      brand: "Toyota",
      category: "The African Transit Minibus",
      name: "Toyota HiAce Minibus",
      icon: "\ud83d\ude90",
      model: "Toyota HiAce 2.5 D-4D 15-Seater Commercial Shuttle",
      shortModel: "HiAce Minibus",
      shortLabel: "\ud83d\ude90 HiAce Minibus",
      powertrain: "2.5L 2KD-FTV D-4D Turbo Diesel (101 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Lifeblood of Public Transport Across Africa)`,
      driverMode: "Reinforced Commercial Chassis \u00b7 Dual Sliding Passenger Doors",
      destinationList: ["Central Bus Interchange", "Market Bus Terminal", "Border Crossing Rank", "Inter-City Highway Stop"],
    },
    {
      brand: "Suzuki",
      category: "African Economy Hatch",
      name: "Suzuki Swift",
      icon: "\ud83d\ude97",
      model: "Suzuki Swift 1.2 Dualjet GA 5-Speed",
      shortModel: "Suzuki Swift",
      shortLabel: "\ud83d\ude97 Suzuki Swift",
      powertrain: "1.2L K12M 4-Cylinder Dualjet (82 hp)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (20.5 km/l Low Maintenance)`,
      driverMode: "ABS with EBD \u00b7 High Resale Value Across Continents",
      destinationList: ["Town Center Lane", "Shopping Mall Gate", "Railway Square", "Hospital Road"],
    },
    {
      brand: "Nissan",
      category: "Accessible Family Sedan",
      name: "Nissan Sunny",
      icon: "\ud83d\ude97",
      model: "Nissan Sunny 1.5L SV DOHC 16V",
      shortModel: "Nissan Sunny",
      shortLabel: "\ud83d\ude97 Nissan Sunny",
      powertrain: "1.5L HR15DE 4-Cylinder (108 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17 km/l)`,
      driverMode: "Air Conditioning with Rear Passenger Vents",
      destinationList: ["Independence Avenue", "City Council Roundabout", "Trade Fair Grounds", "Residential Boulevard"],
    },
    {
      brand: "Chery",
      category: "Rising African Crossover",
      name: "Chery Tiggo 4 Pro",
      icon: "\ud83d\ude99",
      model: "Chery Tiggo 4 Pro 1.5L Comfort",
      shortModel: "Chery Tiggo 4",
      shortLabel: "\ud83d\ude99 Tiggo 4 Pro",
      powertrain: "1.5L Naturally Aspirated 4-Cylinder (113 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15 km/l)`,
      driverMode: "Dual Front Airbags \u00b7 10.25-inch Touchscreen Infotainment",
      destinationList: ["Tech Park Plaza", "Stadium Way", "North Bypass", "Commercial Boulevard"],
    },
    {
      brand: "Volkswagen",
      category: "Southern African Classic",
      name: "VW Polo Vivo",
      icon: "\ud83d\ude97",
      model: "Volkswagen Polo Vivo 1.4 Trendline",
      shortModel: "VW Polo Vivo",
      shortLabel: "\ud83d\ude97 Polo Vivo",
      powertrain: "1.4L MPI 4-Cylinder (75 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16 km/l)`,
      driverMode: "Electronic Stability Programme \u00b7 Tyre Pressure Sensor",
      destinationList: ["City Center Arcade", "Suburban Mall", "University Road", "Outer Ring Road"],
    },
    {
      brand: "Toyota",
      category: "Unbreakable Estate Workhorse",
      name: "Toyota Probox",
      icon: "\ud83d\ude97",
      model: "Toyota Probox DX 1.5L VVT-i Cargo Hauler",
      shortModel: "Toyota Probox",
      shortLabel: "\ud83d\ude97 Toyota Probox",
      powertrain: "1.5L 1NZ-FE 4-Cylinder (109 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (Legendary Carrying Capacity)`,
      driverMode: "Heavy Duty Solid Axle with Flat Rear Cargo Floor",
      destinationList: ["Wholesale Produce Market", "Rural Trading Hub", "Depot Entrance", "Trunk Road Way"],
    },
    {
      brand: "Renault",
      category: "All-Terrain Crossover",
      name: "Renault Duster",
      icon: "\ud83d\ude99",
      model: "Renault Duster 1.5 dCi 4x4 Adventure",
      shortModel: "Renault Duster",
      shortLabel: "\ud83d\ude99 Renault Duster",
      powertrain: "1.5L dCi Turbodiesel 4x4 (110 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (18.5 km/l)`,
      driverMode: "High 210mm Ground Clearance \u00b7 Engine Underbody Sump Guard",
      destinationList: ["Mountain Pass Road", "Savannah Trail", "Regional Trading Post", "District Headquarters"],
    },
    {
      brand: "Haval",
      category: "Modern Family SUV",
      name: "Haval Jolion",
      icon: "\ud83d\ude99",
      model: "Haval Jolion 1.5T City 7DCT",
      shortModel: "Haval Jolion",
      shortLabel: "\ud83d\ude99 Haval Jolion",
      powertrain: "1.5L Turbocharged 4-Cylinder (141 hp)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.5 km/l)`,
      driverMode: "Electric Power Steering \u00b7 Reverse Camera with Dynamic Guidelines",
      destinationList: ["Diplomatic Crescent", "National Theatre Square", "Business Expressway", "Golf Club Way"],
    },
    {
      brand: "Toyota",
      category: "7-Seater Bush 4x4",
      name: "Toyota Fortuner",
      icon: "\ud83d\ude99",
      model: "Toyota Fortuner 2.4 GD-6 4x4 Double Cab",
      shortModel: "Toyota Fortuner",
      shortLabel: "\ud83d\ude99 Fortuner 4x4",
      powertrain: "2.4L GD-6 Turbodiesel Intercooler (148 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Bush Spec)`,
      driverMode: "Part-Time 4WD with Hill-Start Assist Control",
      destinationList: ["Provincial Administration", "Wildlife Reserve Gate", "Highland Highway", "Safari Junction"],
    },
    {
      brand: "Hyundai",
      category: "Compact City Hatch",
      name: "Hyundai Grand i10",
      icon: "\ud83d\ude97",
      model: "Hyundai Grand i10 Motion 1.0L Manual",
      shortModel: "Grand i10",
      shortLabel: "\ud83d\ude97 Grand i10",
      powertrain: "1.0L 3-Cylinder Kappa Engine (66 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (18 km/l)`,
      driverMode: "Dual Airbags \u00b7 Keyless Entry and Bluetooth Hands-Free",
      destinationList: ["Market Roundabout", "Suburban Plaza", "Town Hall Lane", "Eastern Bypass"],
    },
    {
      brand: "Mitsubishi",
      category: "Rugged Off-Road Icon",
      name: "Mitsubishi Pajero",
      icon: "\ud83d\ude99",
      model: "Mitsubishi Pajero 3.2 DI-D GLS 4x4 Field Spec",
      shortModel: "Mitsu Pajero",
      shortLabel: "\ud83d\ude99 Pajero 4x4",
      powertrain: "3.2L 4M41 Common-Rail Turbo Diesel (190 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Diesel Tank (Dual Battery Heavy Off-Road Spec)`,
      driverMode: "Super Select 4WD-II with Rear Differential Lock",
      destinationList: ["Mining Camp Gate", "Game Reserve Track", "Border Post Lane", "Coastal Trunk Road"],
    },
    {
      brand: "Bajaj",
      category: "African Auto-Rickshaw",
      name: "Bajaj Auto-Rickshaw",
      icon: "\ud83d\udefa",
      model: "Bajaj RE 205cc Commercial Passenger Tricycle",
      shortModel: "Bajaj Tricycle",
      shortLabel: "\ud83d\udefa Bajaj Rickshaw",
      powertrain: "205cc 4-Stroke Air-Cooled DTS-i (10 hp)",
      paintColor: "#eab308",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Petrol Tank (Navigates Dense African Urban Traffic)`,
      driverMode: "Weatherproof Canopy \u00b7 Heavy Duty Passenger Benches",
      destinationList: ["City Market Gate", "Commuter Motor Park", "Subway Terminal", "Neighborhood Square"],
    },
    {
      brand: "Toyota",
      category: "Untamable Bush LC70",
      name: "Land Cruiser 70",
      icon: "\ud83d\udefb",
      model: "Toyota Land Cruiser 70 Series 4.2L Diesel 4x4",
      shortModel: "Land Cruiser 70",
      shortLabel: "\ud83d\udefb LC70 Bush 4x4",
      powertrain: "4.2L 1HZ Naturally Aspirated Inline-6 Diesel (129 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual 90L Diesel Tanks (180 L Total African Expedition)`,
      driverMode: "Solid Beam Live Axles \u00b7 Heavy-Duty Snorkel and Mechanical Winch",
      destinationList: ["Remote Wildlife Conservation Area", "Sahara Sahel Route", "Great Rift Valley Track", "Bush Hospital Landing"],
    },
    {
      brand: "Hyundai",
      category: "Family Crossover",
      name: "Hyundai Tucson",
      icon: "\ud83d\ude99",
      model: "Hyundai Tucson 2.0 Smartstream Executive",
      shortModel: "Hyundai Tucson",
      shortLabel: "\ud83d\ude99 Hyundai Tucson",
      powertrain: "2.0L MPI 4-Cylinder DOHC (154 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (14 km/l)`,
      driverMode: "Blind Spot Detection \u00b7 8-inch Touchscreen Audio",
      destinationList: ["Central Boulevard", "Convention Center", "Waterfront Drive", "Ring Expressway"],
    },
    {
      brand: "Isuzu",
      category: "Heavy Cargo King",
      name: "Isuzu Forward Truck",
      icon: "\ud83d\ude9b",
      model: "Isuzu F-Series Forward Medium Freight Hauler",
      shortModel: "Isuzu Forward",
      shortLabel: "\ud83d\ude9b Isuzu Truck",
      powertrain: "7.8L 6HK1-TCN 6-Cylinder Turbo Diesel (240 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Heavy Commercial Diesel (Inter-African Freight Transit)`,
      driverMode: "Air Over Hydraulic Brakes \u00b7 Reinforced Long Wheelbase Chassis",
      destinationList: ["Mombasa-Nairobi-Kampala Corridor", "Lagos-Kano Highway", "Durban-Harare Corridor", "Port Logistics Terminal"],
    },
  ],
  // ==========================================
  // ME_REGIONAL (20 Vehicles)
  // ==========================================
  ME_REGIONAL: [
    {
      brand: "Toyota",
      category: "King of the Arabian Desert",
      name: "Land Cruiser 300",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser 300 3.5L Twin-Turbo 4x4",
      shortModel: "Land Cruiser 300",
      shortLabel: "\ud83d\ude99 Land Cruiser",
      powertrain: "3.5L V6 Twin-Turbo DOHC (409 hp, 650 Nm)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (110 L Dual Fuel)`,
      driverMode: "Multi-Terrain Select \u00b7 Crawl Control \u00b7 Dune Mode",
      destinationList: ["King Fahd Boulevard", "Corniche Waterfront", "Financial Center", "Airport VIP Highway"],
    },
    {
      brand: "Nissan",
      category: "Hero of the Middle East",
      name: "Nissan Patrol V8",
      icon: "\ud83d\ude99",
      model: "Nissan Patrol Titanium 5.6L V8 Desert Spec",
      shortModel: "Nissan Patrol",
      shortLabel: "\ud83d\ude99 Patrol V8",
      powertrain: "5.6L V8 Naturally Aspirated DIG (400 hp, 560 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (140 L Dual Fuel)`,
      driverMode: "Hydraulic Body Motion Control \u00b7 Sand/Rock Terrain Mode",
      destinationList: ["Royal Palace Avenue", "Grand Mosque Plaza", "Dune Recreation Area", "Express Highway"],
    },
    {
      brand: "Lexus",
      category: "VIP Middle Eastern Luxury",
      name: "Lexus LX 600",
      icon: "\ud83d\ude99",
      model: "Lexus LX 600 VIP 4-Seater Ultra Luxury AWD",
      shortModel: "Lexus LX 600",
      shortLabel: "\ud83d\ude99 Lexus LX 600",
      powertrain: "3.5L V6 Twin-Turbo Intercooler (409 hp)",
      paintColor: "#1e293b",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (110 L)`,
      driverMode: "Active Height Control Suspension \u00b7 Mark Levinson 25-Speaker",
      destinationList: ["Diplomatic Quarter", "Five-Star Marina", "Emirates Gateway", "Luxury Galleria"],
    },
    {
      brand: "Toyota",
      category: "Bestselling Executive Sedan",
      name: "Toyota Camry",
      icon: "\ud83d\ude97",
      model: "Toyota Camry 2.5L DOHC Dual VVT-i Gulf Spec",
      shortModel: "Toyota Camry",
      shortLabel: "\ud83d\ude97 Toyota Camry",
      powertrain: "2.5L 4-Cylinder DOHC (204 hp)",
      paintColor: "#ffffff",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.9 km/l High-Ambient Spec)`,
      driverMode: "Toyota Safety Sense \u00b7 Dynamic Radar Cruise",
      destinationList: ["Ministry Boulevard", "City Central Interchange", "University Square", "Airport Expressway"],
    },
    {
      brand: "Hyundai",
      category: "Popular Regional Sedan",
      name: "Hyundai Elantra",
      icon: "\ud83d\ude97",
      model: "Hyundai Elantra Smart 2.0L MPI Gulf Spec",
      shortModel: "Hyundai Elantra",
      shortLabel: "\ud83d\ude97 Hyundai Elantra",
      powertrain: "2.0L Nu Smartstream MPI (159 hp)",
      paintColor: "#475569",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (16.3 km/l)`,
      driverMode: "SmartSense Blind-Spot View Monitor \u00b7 Cooled Front Seats",
      destinationList: ["Commercial Avenue", "North Corniche", "Business Park Gate", "Ring Boulevard"],
    },
    {
      brand: "Toyota",
      category: "Desert Tough Bakkie",
      name: "Toyota Hilux",
      icon: "\ud83d\udefb",
      model: "Toyota Hilux Adventure 4.0L V6 4x4 Petrol",
      shortModel: "Hilux 4.0 V6",
      shortLabel: "\ud83d\udefb Hilux V6 Gulf",
      powertrain: "4.0L 1GR-FE V6 Petrol (235 hp, 376 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L Heavy Desert Cooling)`,
      driverMode: "Rear Differential Lock \u00b7 Heavy Duty Suspension",
      destinationList: ["Desert Camp Route", "Industrial Trading Zone", "Coastal Highway", "Port Entrance"],
    },
    {
      brand: "Mercedes-AMG",
      category: "Iconic Middle East Luxury",
      name: "Mercedes G 63 AMG",
      icon: "\ud83d\ude99",
      model: "Mercedes-AMG G 63 V8 Biturbo Desert King",
      shortModel: "AMG G 63",
      shortLabel: "\ud83d\ude99 AMG G 63",
      powertrain: "4.0L V8 Biturbo Handcrafted AMG (577 hp, 850 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (100 L Super 98)`,
      driverMode: "AMG RIDE CONTROL \u00b7 3 Independent Locking Differentials",
      destinationList: ["Marina Boardwalk", "Luxury Shopping Mall", "Exclusive Hotel Gate", "Grand Corniche"],
    },
    {
      brand: "Ford",
      category: "Regional Executive Sedan",
      name: "Ford Taurus",
      icon: "\ud83d\ude97",
      model: "Ford Taurus Titanium 2.0L EcoBoost FWD",
      shortModel: "Ford Taurus",
      shortLabel: "\ud83d\ude97 Ford Taurus",
      powertrain: "2.0L EcoBoost GTDI 4-Cylinder (232 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (15.5 km/l)`,
      driverMode: "Blind Spot Information System \u00b7 13.2-inch Touchscreen",
      destinationList: ["Government Secretariat", "Diplomatic Avenue", "Trade Center", "Airport Expressway"],
    },
    {
      brand: "Nissan",
      category: "Everyday Middle East Sedan",
      name: "Nissan Sunny",
      icon: "\ud83d\ude97",
      model: "Nissan Sunny SV 1.6L Xtronic CVT",
      shortModel: "Nissan Sunny",
      shortLabel: "\ud83d\ude97 Nissan Sunny",
      powertrain: "1.6L DOHC 16-Valve (118 hp)",
      paintColor: "#334155",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (19.3 km/l)`,
      driverMode: "Nissan Intelligent Mobility \u00b7 Forward Collision Warning",
      destinationList: ["Market Square", "Residential District", "City Hospital", "Central Station"],
    },
    {
      brand: "Changan",
      category: "Sporty Regional Crossover",
      name: "Changan CS85",
      icon: "\ud83d\ude99",
      model: "Changan CS85 Coupe 2.0T BlueCore 8AT",
      shortModel: "Changan CS85",
      shortLabel: "\ud83d\ude99 Changan CS85",
      powertrain: "2.0L Turbo Direct Injection (233 hp, 360 Nm)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (14.1 km/l)`,
      driverMode: "Aisin 8-Speed Automatic \u00b7 Panoramic Sunroof",
      destinationList: ["Tech Boulevard", "City Center Mall", "Suburban Plaza", "Outer Ringway"],
    },
    {
      brand: "Geely",
      category: "Flagship Luxury Crossover",
      name: "Geely Monjaro",
      icon: "\ud83d\ude99",
      model: "Geely Monjaro 2.0T 4WD Flagship Edition",
      shortModel: "Geely Monjaro",
      shortLabel: "\ud83d\ude99 Geely Monjaro",
      powertrain: "2.0L Turbo Direct Injection AWD (238 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.8 km/l)`,
      driverMode: "Triple High-Resolution Display \u00b7 Level 2 ADAS",
      destinationList: ["Innovation Campus", "East Waterfront", "Grand Gateway", "Airport Freeway"],
    },
    {
      brand: "Toyota",
      category: "Desert Adventure 4x4",
      name: "Toyota Prado",
      icon: "\ud83d\ude99",
      model: "Toyota Land Cruiser Prado 4.0L V6 VX 4x4",
      shortModel: "Toyota Prado",
      shortLabel: "\ud83d\ude99 Prado V6 Gulf",
      powertrain: "4.0L 1GR-FE V6 Dual VVT-i (271 hp)",
      paintColor: "#059669",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Dual Fuel Tanks (150 L Extended Desert Range)`,
      driverMode: "Full-Time 4WD with Kinetic Dynamic Suspension (KDSS)",
      destinationList: ["Desert Oasis Trail", "Coastal Resort Road", "Suburban Estate", "Ring Highway"],
    },
    {
      brand: "Chevrolet",
      category: "Full-Size Family SUV",
      name: "Chevrolet Tahoe",
      icon: "\ud83d\ude99",
      model: "Chevrolet Tahoe Premier 5.3L V8 4WD Gulf Spec",
      shortModel: "Chevy Tahoe",
      shortLabel: "\ud83d\ude99 Chevy Tahoe",
      powertrain: "5.3L EcoTec3 V8 with 10-Speed Auto (355 hp)",
      paintColor: "#1e3a8a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (91 L Large Family Tank)`,
      driverMode: "Magnetic Ride Control \u00b7 10.2-inch Touchscreen with Apple CarPlay",
      destinationList: ["Family Leisure Park", "Private Beach Resort", "Grand Shopping Boulevard", "Express Highway"],
    },
    {
      brand: "Kia",
      category: "Accessible Subcompact Sedan",
      name: "Kia Pegas",
      icon: "\ud83d\ude97",
      model: "Kia Pegas EX 1.4L Automatic Gulf Spec",
      shortModel: "Kia Pegas",
      shortLabel: "\ud83d\ude97 Kia Pegas",
      powertrain: "1.4L Kappa MPI 4-Cylinder (95 hp)",
      paintColor: "#ca8a04",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (17.8 km/l)`,
      driverMode: "Electronic Stability Control \u00b7 Rear View Camera",
      destinationList: ["Local Souq", "Town Square", "Residential Lane", "Community Center"],
    },
    {
      brand: "GMC",
      category: "Apex Middle Eastern SUV",
      name: "GMC Yukon Denali",
      icon: "\ud83d\ude99",
      model: "GMC Yukon Denali 6.2L V8 4WD Gulf Spec",
      shortModel: "Yukon Denali",
      shortLabel: "\ud83d\ude99 Yukon Denali",
      powertrain: "6.2L EcoTec3 V8 Dynamic Fuel Management (420 hp)",
      paintColor: "#0f172a",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (91 L)`,
      driverMode: "Air Ride Adaptive Suspension \u00b7 Bose 14-Speaker Centerpoint",
      destinationList: ["Royal Protocol Way", "Luxury Hotel Entrance", "VIP Terminal", "Grand Waterfront"],
    },
    {
      brand: "MG",
      category: "Popular Value Sedan",
      name: "MG 5",
      icon: "\ud83d\ude97",
      model: "MG 5 Deluxe 1.5L CVT Sedan Gulf Edition",
      shortModel: "MG 5 Sedan",
      shortLabel: "\ud83d\ude97 MG 5",
      powertrain: "1.5L DOHC 4-Cylinder (118 hp)",
      paintColor: "#ea580c",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (19.5 km/l)`,
      driverMode: "360-degree Panoramic Camera \u00b7 Electric Sunroof",
      destinationList: ["Shopping Galleria", "Transit Station", "University Parkway", "North Ring Road"],
    },
    {
      brand: "Haval",
      category: "Family Midsize SUV",
      name: "Haval H6",
      icon: "\ud83d\ude99",
      model: "Haval H6 Supreme 2.0L Turbo 4WD",
      shortModel: "Haval H6",
      shortLabel: "\ud83d\ude99 Haval H6",
      powertrain: "2.0L Turbo 4-Cylinder GDI (201 hp, 320 Nm)",
      paintColor: "#0891b2",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.7 km/l)`,
      driverMode: "Level 2 Autonomous Driving Assist \u00b7 Wireless Charging",
      destinationList: ["Business Hub", "Metro Center", "Suburban Ring", "East Gate"],
    },
    {
      brand: "Lexus",
      category: "Executive Luxury Cruiser",
      name: "Lexus ES 350",
      icon: "\ud83d\ude97",
      model: "Lexus ES 350 F-Sport 3.5L V6 Gulf Edition",
      shortModel: "Lexus ES 350",
      shortLabel: "\ud83d\ude97 Lexus ES 350",
      powertrain: "3.5L V6 24-Valve DOHC Dual VVT-i (302 hp)",
      paintColor: "#0284c7",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (13.6 km/l)`,
      driverMode: "Lexus Safety System+ 2.5 \u00b7 Mark Levinson Audio",
      destinationList: ["Diplomatic Quarter", "Executive Tower", "Convention Center", "Grand Highway"],
    },
    {
      brand: "Genesis",
      category: "Korean Prestige SUV",
      name: "Genesis GV80",
      icon: "\ud83d\ude99",
      model: "Genesis GV80 3.5T Prestige AWD",
      shortModel: "Genesis GV80",
      shortLabel: "\ud83d\ude99 Genesis GV80",
      powertrain: "3.5L Twin-Turbo V6 (375 hp, 530 Nm)",
      paintColor: "#111827",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (80 L)`,
      driverMode: "Road Preview Electronic Suspension \u00b7 Ergo Motion Seats",
      destinationList: ["VIP Marina", "Cultural District", "Luxury Boutique Avenue", "Airport Express"],
    },
    {
      brand: "Porsche",
      category: "High-Performance SUV",
      name: "Porsche Cayenne",
      icon: "\ud83d\ude99",
      model: "Porsche Cayenne 3.0L Turbo V6 AWD Gulf Spec",
      shortModel: "Porsche Cayenne",
      shortLabel: "\ud83d\ude99 Porsche Cayenne",
      powertrain: "3.0L Single Turbo V6 (348 hp, 500 Nm)",
      paintColor: "#dc2626",
      batteryFuel: (s) => `${Math.floor(48 + (s % 48))}% Fuel Tank (90 L Super Plus)`,
      driverMode: "Porsche Active Suspension Management (PASM) \u00b7 Matrix LED",
      destinationList: ["Yacht Club Marina", "Fashion Boulevard", "Private Island Way", "Express Highway Corridor"],
    },
  ],
};
